# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_miles_per_hour(value): 
	return value * 1.15078
def to_kilometres_per_hour(value): 
	return value * 1.852
def to_feet_per_second(value): 
	return value * 1.68781
def to_metres_per_second(value): 
	return value / 1.94384

