# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_kilometres_per_hour(value): 
	return value * 1.60934
def to_feet_per_second(value): 
	return value * 1.46667
def to_metres_per_second(value): 
	return value / 2.23694
def to_knots(value): 
	return value / 1.15078
