# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_millilitres(value): 
	return value * 16.3871
def to_litres(value): 
	return value / 61.0237
def to_kilolitres(value): 
	return value / 61023.7
def to_teaspoons(value): 
	return value * 2.76837
def to_tablespoons(value): 
	return value / 1.08367
def to_quarts(value): 
	return value / 69.3549
def to_pints(value): 
	return value / 34.6774
def to_gallons(value): 
	return value / 277.419
def to_fluid_ounces(value): 
	return value / 1.73387
def to_u_s_teaspoons(value): 
	return value * 3.32468
def to_u_s_tablespoons(value): 
	return value * 1.10823
def to_u_s_quarts(value): 
	return value / 57.75
def to_u_s_pints(value): 
	return value / 28.875
def to_u_s_gallons(value): 
	return value / 231.0
def to_u_s_fluid_ounces(value): 
	return value / 1.80469
def to_u_s_cups(value): 
	return value / 14.6457
def to_cubic_metres(value): 
	return value / 61023.7
def to_cubic_feet(value): 
	return value / 1728.0
def to_oil_barrels(value): 
	return value / 9702.0

