# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_millilitres(value): 
	return value * 28316.8
def to_litres(value): 
	return value * 28.3168
def to_kilolitres(value): 
	return value / 35.3147
def to_teaspoons(value): 
	return value * 4783.74
def to_tablespoons(value): 
	return value * 1594.58
def to_quarts(value): 
	return value * 24.9153
def to_pints(value): 
	return value * 49.8307
def to_gallons(value): 
	return value * 6.22884
def to_fluid_ounces(value): 
	return value * 996.614
def to_u_s_teaspoons(value): 
	return value * 5745.04
def to_u_s_tablespoons(value): 
	return value * 1915.01
def to_u_s_quarts(value): 
	return value * 29.9221
def to_u_s_pints(value): 
	return value * 59.8442
def to_u_s_gallons(value): 
	return value * 7.48052
def to_u_s_fluid_ounces(value): 
	return value * 957.506
def to_u_s_cups(value): 
	return value * 117.987
def to_cubic_metres(value): 
	return value / 35.3147
def to_cubic_inches(value): 
	return value * 1728.0
def to_oil_barrels(value): 
	return value / 5.61458

