# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_millilitres(value): 
	return value * 1000000.0
def to_litres(value): 
	return value * 1000.0
def to_kilolitres(value): 
	return value * 1.0
def to_teaspoons(value): 
	return value * 168936.0
def to_tablespoons(value): 
	return value * 56312.1
def to_quarts(value): 
	return value * 879.877
def to_pints(value): 
	return value * 1759.75
def to_gallons(value): 
	return value * 219.969
def to_fluid_ounces(value): 
	return value * 35195.1
def to_u_s_teaspoons(value): 
	return value * 202884.0
def to_u_s_tablespoons(value): 
	return value * 67628.0
def to_u_s_quarts(value): 
	return value * 1056.69
def to_u_s_pints(value): 
	return value * 2113.38
def to_u_s_gallons(value): 
	return value * 264.172
def to_u_s_fluid_ounces(value): 
	return value * 33814.0
def to_u_s_cups(value): 
	return value * 4166.67
def to_cubic_feet(value): 
	return value * 35.3147
def to_cubic_inches(value): 
	return value * 61023.7
def to_oil_barrels(value): 
	return value * 6.28981

