# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_millilitres(value): 
	return value * 28.413074243749994496
def to_litres(value): 
	return value * 0.028413074243749994496
def to_kilolitres(value): 
	return value * 0.000028413074243749994
def to_teaspoons(value): 
	return value * 4.8
def to_tablespoons(value): 
	return value * 1.6
def to_quarts(value): 
	return value / 40.0
def to_pints(value): 
	return value / 20.0
def to_gallons(value): 
	return value / 160.0
def to_u_s_teaspoons(value): 
	return value / 0.1734737167638313984
def to_u_s_tablespoons(value): 
	return value / 0.52042115029149417472
def to_u_s_quarts(value): 
	return value / 33.306953618655629312
def to_u_s_pints(value): 
	return value / 16.653476809327814656
def to_u_s_gallons(value): 
	return value / 133.22781447462252544
def to_u_s_fluid_ounces(value): 
	return value / 1.0408423005829883904
def to_u_s_cups(value): 
	return value / 8.3267384046639071232

