# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_millilitres(value): 
	return value * 4546.091879
def to_litres(value): 
	return value * 4.546091879
def to_kilolitres(value): 
	return value * 0.0045460918799
def to_teaspoons(value): 
	return value * 768.0
def to_tablespoons(value): 
	return value * 256.0
def to_quarts(value): 
	return value * 4.0
def to_pints(value): 
	return value * 8.0
def to_fluid_ounces(value): 
	return value * 160.0
def to_u_s_teaspoons(value): 
	return value / 0.00108421072977394606
def to_u_s_tablespoons(value): 
	return value / 0.003252632189321838592
def to_u_s_quarts(value): 
	return value / 0.20816846011659767808
def to_u_s_pints(value): 
	return value / 0.10408423005829883904
def to_u_s_gallons(value): 
	return value / 0.83267384046639071232
def to_u_s_fluid_ounces(value): 
	return value / 0.006505264378643677184
def to_u_s_cups(value): 
	return value / 0.052042115029149417472

