# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_millilitres(value): 
	return value * 1000000.0
def to_litres(value): 
	return value * 1000.0
def to_teaspoons(value): 
	return value / 0.000005919390467447916
def to_tablespoons(value): 
	return value / 0.000017758171402343747
def to_quarts(value): 
	return value / 0.00113652296975
def to_pints(value): 
	return value / 0.000568261484874999889
def to_gallons(value): 
	return value / 0.0045460918799
def to_fluid_ounces(value): 
	return value / 0.0000284130742437499946
def to_u_s_teaspoons(value): 
	return value / 0.000004928921593749999
def to_u_s_tablespoons(value): 
	return value / 0.000014786764781249998
def to_u_s_quarts(value): 
	return value / 0.000946352945999999959
def to_u_s_pints(value): 
	return value / 0.000473176472999999979
def to_u_s_gallons(value): 
	return value / 0.003785411784
def to_u_s_fluid_ounces(value): 
	return value / 0.0000295735296
def to_u_s_cups(value): 
	return value / 0.000236588236499999989

