# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_millilitres(value): 
	return value * 1000.0
def to_kilolitres(value): 
	return value / 1000.0
def to_teaspoons(value): 
	return value / 0.005919390467447916134
def to_tablespoons(value): 
	return value / 0.017758171402343747584
def to_quarts(value): 
	return value / 1.13652296975
def to_pints(value): 
	return value / 0.56826148487499988992
def to_gallons(value): 
	return value / 4.546091879
def to_fluid_ounces(value): 
	return value / 0.028413074243749994496
def to_u_s_teaspoons(value): 
	return value / 0.004928921593749999616
def to_u_s_tablespoons(value): 
	return value / 0.014786764781249998848
def to_u_s_quarts(value): 
	return value / 0.94635294599999995904
def to_u_s_pints(value): 
	return value / 0.47317647299999997952
def to_u_s_gallons(value): 
	return value / 3.785411784
def to_u_s_fluid_ounces(value): 
	return value / 0.029573529562499997696
def to_u_s_cups(value): 
	return value / 0.23658823649999998976
def to_cubic_metres(value): 
	return value / 1000.0
def to_cubic_feet(value): 
	return value / 28.3168
def to_cubic_inches(value): 
	return value * 61.0237
def to_oil_barrels(value): 
	return value / 158.987

