# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_litres(value): 
	return value / 1000.0
def to_kilolitres(value): 
	return value / 1000000.0
def to_teaspoons(value): 
	return value / 5.9193904674479161344
def to_tablespoons(value): 
	return value / 17.758171402343747584
def to_quarts(value): 
	return value / 1136.52296975
def to_pints(value): 
	return value / 568.26148487499988992
def to_gallons(value): 
	return value / 4546.091879
def to_fluid_ounces(value): 
	return value / 28.413074243749994496
def to_u_s_teaspoons(value): 
	return value / 4.928921593749999616
def to_u_s_tablespoons(value): 
	return value / 14.786764781249998848
def to_u_s_quarts(value): 
	return value / 946.35294599999995904
def to_u_s_pints(value): 
	return value / 473.17647299999997952
def to_u_s_gallons(value): 
	return value / 3785.411784
def to_u_s_fluid_ounces(value): 
	return value / 29.573529562499997696
def to_u_s_cups(value): 
	return value / 236.58823649999998976
def to_cubic_metres(value): 
	return value / 1000000.0
def to_cubic_feet(value): 
	return value / 28316.8
def to_cubic_inches(value): 
	return value / 16.3871
def to_oil_barrels(value): 
	return value / 158987.0

