# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_millilitres(value): 
	return value * 158987.0
def to_litres(value): 
	return value * 158.987
def to_kilolitres(value): 
	return value / 6.28981
def to_teaspoons(value): 
	return value * 26858.7
def to_tablespoons(value): 
	return value * 8952.91
def to_quarts(value): 
	return value * 139.889
def to_pints(value): 
	return value * 279.779
def to_gallons(value): 
	return value * 34.9723
def to_fluid_ounces(value): 
	return value * 5595.57
def to_u_s_teaspoons(value): 
	return value * 32256.0
def to_u_s_tablespoons(value): 
	return value * 10752.0
def to_u_s_quarts(value): 
	return value * 168.0
def to_u_s_pints(value): 
	return value * 336.0
def to_u_s_gallons(value): 
	return value * 42.0
def to_u_s_fluid_ounces(value): 
	return value * 5376.0
def to_u_s_cups(value): 
	return value * 662.447
def to_cubic_metres(value): 
	return value / 6.28981
def to_cubic_feet(value): 
	return value * 5.61458
def to_cubic_inches(value): 
	return value * 9702.0

