# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_millilitres(value): 
	return value * 568.26148487499988992
def to_litres(value): 
	return value * 0.56826148487499988992
def to_kilolitres(value): 
	return value * 0.000568261484874999889
def to_teaspoons(value): 
	return value * 96.0
def to_tablespoons(value): 
	return value * 32.0
def to_quarts(value): 
	return value  / 2.0
def to_gallons(value): 
	return value / 8.0
def to_fluid_ounces(value): 
	return value * 20.0
def to_u_s_teaspoons(value): 
	return value / 0.008673685838191568486
def to_u_s_tablespoons(value): 
	return value / 0.026021057514574708736
def to_u_s_quarts(value): 
	return value / 1.6653476809327814656
def to_u_s_pints(value): 
	return value / 0.83267384046639071232
def to_u_s_gallons(value): 
	return value / 6.6613907237311258624
def to_u_s_fluid_ounces(value): 
	return value / 0.052042115029149417472
def to_u_s_cups(value): 
	return value / 0.41633692023319535616
def to_cubic_metres(value): 
	return value / 1759.75
def to_cubic_feet(value): 
	return value / 49.8307
def to_cubic_inches(value): 
	return value * 34.6774
def to_oil_barrels(value): 
	return value / 279.779

