# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_millilitres(value): 
	return value * 1136.52296975
def to_litres(value): 
	return value * 1.13652296975
def to_kilolitres(value): 
	return value * 0.00113652296975
def to_teaspoons(value): 
	return value * 192.0
def to_tablespoons(value): 
	return value * 64.0
def to_pints(value): 
	return value * 2.0
def to_gallons(value): 
	return value / 4.0
def to_fluid_ounces(value): 
	return value * 40.0
def to_u_s_teaspoons(value): 
	return value / 0.004336842919095784243
def to_u_s_tablespoons(value): 
	return value / 0.013010528757287354368
def to_u_s_quarts(value): 
	return value / 0.83267384046639071232
def to_u_s_pints(value): 
	return value / 0.41633692023319535616
def to_u_s_gallons(value): 
	return value / 3.3306953618655629312
def to_u_s_fluid_ounces(value): 
	return value / 0.026021057514574708736
def to_u_s_cups(value): 
	return value / 0.20816846011659767808

