# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_millilitres(value): 
	return value * 17.758171402343747584
def to_litres(value): 
	return value * 0.017758171402343747584
def to_kilolitres(value): 
	return value * 0.000017758171402343747
def to_teaspoons(value): 
	return value * 3.0
def to_quarts(value): 
	return value / 64.0
def to_pints(value): 
	return value / 32.0
def to_gallons(value): 
	return value / 256.0
def to_fluid_ounces(value): 
	return value / 1.6
def to_u_s_teaspoons(value): 
	return value / 0.27755794682213023744
def to_u_s_tablespoons(value): 
	return value / 0.83267384046639071232
def to_u_s_quarts(value): 
	return value / 53.291125789849001984
def to_u_s_pints(value): 
	return value / 26.645562894924500992
def to_u_s_gallons(value): 
	return value / 213.16450315939602432
def to_u_s_fluid_ounces(value): 
	return value / 1.6653476809327814656
def to_u_s_cups(value): 
	return value / 13.322781447462250496

