# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_millilitres(value): 
	return value * 5.9193904674479161344
def to_litres(value): 
	return value * 0.005919390467447916134
def to_kilolitres(value): 
	return value * 0.000005919390467447916
def to_tablespoons(value): 
	return value / 3.0
def to_quarts(value): 
	return value / 192.0
def to_pints(value): 
	return value / 96.0
def to_gallons(value): 
	return value / 768.0
def to_fluid_ounces(value): 
	return value / 4.8
def to_u_s_teaspoons(value): 
	return value / 0.83267384046639071232
def to_u_s_tablespoons(value): 
	return value / 2.4980215213991718912
def to_u_s_quarts(value): 
	return value / 159.87337736954701824
def to_u_s_pints(value): 
	return value / 79.936688684773507072
def to_u_s_gallons(value): 
	return value / 639.49350947818807296
def to_u_s_fluid_ounces(value): 
	return value / 4.9960430427983437824
def to_u_s_cups(value): 
	return value / 39.968344342386753536

