# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_millilitres(value): 
	return value * 14.786764781249998848
def to_litres(value): 
	return value * 0.014786764781249998848
def to_kilolitres(value): 
	return value * 0.000014786764781249998
def to_teaspoons(value): 
	return value * 2.4980215213991718912
def to_tablespoons(value): 
	return value * 0.83267384046639071232
def to_quarts(value): 
	return value * 0.013010528757287354368
def to_pints(value): 
	return value * 0.026021057514574708736
def to_gallons(value): 
	return value * 0.003252632189321838592
def to_fluid_ounces(value): 
	return value * 0.52042115029149417472
def to_u_s_teaspoons(value): 
	return value * 3.0
def to_u_s_quarts(value): 
	return value / 64.0
def to_u_s_pints(value): 
	return value / 32.0
def to_u_s_gallons(value): 
	return value / 256.0
def to_u_s_fluid_ounces(value): 
	return value / 2.0
def to_u_s_cups(value): 
	return value / 16.0
def to_cubic_metres(value): 
	return value / 67628.0
def to_cubic_feet(value): 
	return value / 1915.01
def to_cubic_inches(value): 
	return value / 1.10823
def to_oil_barrels(value): 
	return value / 10752.0

