# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_millilitres(value): 
	return value * 3785.411784
def to_litres(value): 
	return value * 3.785411784
def to_kilolitres(value): 
	return value * 0.003785411784
def to_teaspoons(value): 
	return value * 639.49350947818807296
def to_tablespoons(value): 
	return value * 213.16450315939602432
def to_quarts(value): 
	return value * 3.3306953618655629312
def to_pints(value): 
	return value * 6.6613907237311258624
def to_gallons(value): 
	return value * 0.83267384046639071232
def to_fluid_ounces(value): 
	return value * 133.22781447462252544
def to_u_s_teaspoons(value): 
	return value * 768.0
def to_u_s_tablespoons(value): 
	return value * 256.0
def to_u_s_quarts(value): 
	return value * 4.0
def to_u_s_pints(value): 
	return value * 8.0
def to_u_s_fluid_ounces(value): 
	return value * 128.0
def to_u_s_cups(value): 
	return value * 16.0
def to_cubic_metres(value): 
	return value / 264.172
def to_cubic_feet(value): 
	return value / 7.48052
def to_cubic_inches(value): 
	return value * 231.0
def to_oil_barrels(value): 
	return value / 42.0

