# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_millilitres(value): 
	return value * 473.17647299999997952
def to_litres(value): 
	return value * 0.47317647299999997952
def to_kilolitres(value): 
	return value * 0.000473176472999999979
def to_teaspoons(value): 
	return value * 79.936688684773507072
def to_tablespoons(value): 
	return value * 26.645562894924500992
def to_quarts(value): 
	return value * 0.41633692023319535616
def to_pints(value): 
	return value * 0.83267384046639071232
def to_gallons(value): 
	return value * 0.10408423005829883904
def to_fluid_ounces(value): 
	return value * 16.653476809327814656
def to_u_s_teaspoons(value): 
	return value * 96.0
def to_u_s_tablespoons(value): 
	return value * 32.0
def to_u_s_quarts(value): 
	return value / 2.0
def to_u_s_gallons(value): 
	return value / 8.0
def to_u_s_fluid_ounces(value): 
	return value * 16.0
def to_u_s_cups(value): 
	return value * 2.0

