# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_millilitres(value): 
	return value * 29.573529562499997696
def to_litres(value): 
	return value * 0.029573529562499997696
def to_kilolitres(value): 
	return value * 0.0000295735296
def to_teaspoons(value): 
	return value * 4.9960430427983437824
def to_tablespoons(value): 
	return value * 1.6653476809327814656
def to_quarts(value): 
	return value * 0.026021057514574708736
def to_pints(value): 
	return value * 0.052042115029149417472
def to_gallons(value): 
	return value * 0.006505264378643677184
def to_fluid_ounces(value): 
	return value * 1.0408423005829883904
def to_u_s_teaspoons(value): 
	return value * 6.0
def to_u_s_tablespoons(value): 
	return value * 2.0
def to_u_s_quarts(value): 
	return value / 32.0
def to_u_s_pints(value): 
	return value / 16.0
def to_u_s_gallons(value): 
	return value / 128.0
def to_u_s_cups(value): 
	return value / 8.0
def to_cubic_metres(value): 
	return value / 33814.0
def to_cubic_feet(value): 
	return value / 957.506
def to_cubic_inches(value): 
	return value * 1.80469
def to_oil_barrels(value): 
	return value / 5376.0

