# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_millilitres(value): 
	return value * 236.58823649999998976
def to_litres(value): 
	return value * 0.23658823649999998976
def to_kilolitres(value): 
	return value * 0.000236588236499999989
def to_teaspoons(value): 
	return value * 39.968344342386753536
def to_tablespoons(value): 
	return value * 13.322781447462250496
def to_quarts(value): 
	return value * 0.20816846011659767808
def to_pints(value): 
	return value * 0.41633692023319535616
def to_gallons(value): 
	return value * 0.052042115029149417472
def to_fluid_ounces(value): 
	return value * 8.3267384046639071232
def to_u_s_teaspoons(value): 
	return value * 48.0
def to_u_s_tablespoons(value): 
	return value * 16.0
def to_u_s_quarts(value): 
	return value / 4.0
def to_u_s_pints(value): 
	return value / 2.0
def to_u_s_gallons(value): 
	return value / 16.0
def to_u_s_fluid_ounces(value): 
	return value * 8.0

