# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_millilitres(value): 
	return value * 4.928921593749999616
def to_litres(value): 
	return value * 0.004928921593749999616
def to_kilolitres(value): 
	return value * 0.000004928921593749999
def to_teaspoons(value): 
	return value * 0.83267384046639071232
def to_tablespoons(value): 
	return value * 0.27755794682213023744
def to_quarts(value): 
	return value * 0.004336842919095784243
def to_pints(value): 
	return value * 0.008673685838191568486
def to_gallons(value): 
	return value * 0.00108421072977394606
def to_fluid_ounces(value): 
	return value * 0.1734737167638313984
def to_u_s_tablespoons(value): 
	return value / 3.0
def to_u_s_quarts(value): 
	return value / 192.0
def to_u_s_pints(value): 
	return value / 96.0
def to_u_s_gallons(value): 
	return value / 768.0
def to_u_s_fluid_ounces(value): 
	return value / 6.0
def to_u_s_cups(value): 
	return value / 48.0
def to_cubic_metres(value): 
	return value / 202884.0
def to_cubic_feet(value): 
	return value / 5745.04
def to_cubic_inches(value): 
	return value / 3.32468
def to_oil_barrels(value): 
	return value / 32256.0
