# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_millilitres(value): 
	return value * 946.35294599999995904
def to_litres(value): 
	return value * 0.94635294599999995904
def to_kilolitres(value): 
	return value * 0.000946352945999999959
def to_teaspoons(value): 
	return value * 159.87337736954701824
def to_tablespoons(value): 
	return value * 53.291125789849001984
def to_quarts(value): 
	return value * 0.83267384046639071232
def to_pints(value): 
	return value * 1.6653476809327814656
def to_gallons(value): 
	return value * 0.20816846011659767808
def to_fluid_ounces(value): 
	return value * 33.306953618655629312
def to_u_s_teaspoons(value): 
	return value * 192.0
def to_u_s_tablespoons(value): 
	return value * 64.0
def to_u_s_pints(value): 
	return value * 2.0
def to_u_s_gallons(value): 
	return value / 4.0
def to_u_s_fluid_ounces(value): 
	return value * 32.0
def to_u_s_cups(value): 
	return value * 4.0
def to_cubic_metres(value): 
	return value / 1056.69
def to_cubic_feet(value): 
	return value / 29.9221
def to_cubic_inches(value): 
	return value * 57.75
def to_oil_barrels(value): 
	return value / 168.0

