# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_fahrenheit(value): 
	return value * 1.8 + 32.0
def to_kelvin(value): 
	return value + 273.15
def to_rankine(value): 
	return value * 9.0/5.0 + 491.67

