# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_celsius(value): 
	return ((value - 32.0) * 5.0) / 9.0
def to_kelvin(value): 
	return (((value - 32.0) * 5.0) / 9.0) + 273.15
def to_rankine(value): 
	return value + 459.67

