# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_celsius(value): 
	return (value - 491.67) * 5.0/9.0
def to_fahrenheit(value): 
	return value - 459.67
def to_kelvin(value): 
	return value / 1.8
