# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.energy.calories

class TestCaloriesMethods(unittest.TestCase):

	def test_convert_known_calories_to_kilojoules(self):
		self.assertAlmostEqual(0.456056, units.energy.calories.to_kilojoules(109.0), places=1)
		self.assertAlmostEqual(0.0514632, units.energy.calories.to_kilojoules(12.3), places=1)
		self.assertAlmostEqual(41.32118, units.energy.calories.to_kilojoules(9876.0), places=1)

	def test_convert_known_calories_to_kilocalories(self):
		self.assertAlmostEqual(0.9, units.energy.calories.to_kilocalories(900.0), places=1)
		self.assertAlmostEqual(1.782, units.energy.calories.to_kilocalories(1782.0), places=1)
		self.assertAlmostEqual(900.8, units.energy.calories.to_kilocalories(900800.0), places=1)

	def test_convert_known_calories_to_joules(self):
		self.assertAlmostEqual(410.032, units.energy.calories.to_joules(98.0), places=1)
		self.assertAlmostEqual(6.98728, units.energy.calories.to_joules(1.67), places=1)
		self.assertAlmostEqual(230.12, units.energy.calories.to_joules(55.0), places=1)

	def test_convert_known_calories_to_btu(self):
		self.assertAlmostEqual(2.18112, units.energy.calories.to_btu(550.0), places=1)
		self.assertAlmostEqual(4.893633, units.energy.calories.to_btu(1234.0), places=1)
		self.assertAlmostEqual(3.5726692, units.energy.calories.to_btu(900.9), places=1)

	def test_convert_known_calories_to_u_s_therms(self):
		self.assertAlmostEqual(0.356995242, units.energy.calories.to_u_s_therms(9000000.0), places=1)
		self.assertAlmostEqual(0.475993657, units.energy.calories.to_u_s_therms(12e6), places=1)
		self.assertAlmostEqual(3.974558932, units.energy.calories.to_u_s_therms(100200300.0), places=1)

	def test_convert_known_calories_to_watt_hours(self):
		self.assertAlmostEqual(0.697333, units.energy.calories.to_watt_hours(600.0), places=1)
		self.assertAlmostEqual(1.43476333, units.energy.calories.to_watt_hours(1234.5), places=1)
		self.assertAlmostEqual(0.1030891, units.energy.calories.to_watt_hours(88.7), places=1)

	def test_convert_known_calories_to_kilowatt_hours(self):
		self.assertAlmostEqual(0.117268222, units.energy.calories.to_kilowatt_hours(100900.0), places=1)
		self.assertAlmostEqual(1.14787343, units.energy.calories.to_kilowatt_hours(987654.0), places=1)
		self.assertAlmostEqual(0.588098391, units.energy.calories.to_kilowatt_hours(506012.0), places=1)

	def test_convert_known_calories_to_foot_pounds(self):
		self.assertAlmostEqual(379.573, units.energy.calories.to_foot_pounds(123.0), places=1)
		self.assertAlmostEqual(27.8045, units.energy.calories.to_foot_pounds(9.01), places=1)
		self.assertAlmostEqual(8.64069, units.energy.calories.to_foot_pounds(2.8), places=1)

if __name__ == '__main__':
    unittest.main()
