# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.area.acres

class TestAcresMethods(unittest.TestCase):

	def test_convert_known_acres_to_square_kilometres(self):
		self.assertAlmostEqual(0.404686, units.area.acres.to_square_kilometres(100.0), places=1)
		self.assertAlmostEqual(0.364217, units.area.acres.to_square_kilometres(90.0), places=1)
		self.assertAlmostEqual(7.284342, units.area.acres.to_square_kilometres(1800.0), places=1)

	def test_convert_known_acres_to_square_metres(self):
		self.assertAlmostEqual(4856.23, units.area.acres.to_square_metres(1.2), places=1)
		self.assertAlmostEqual(3237.49, units.area.acres.to_square_metres(0.8), places=1)
		self.assertAlmostEqual(22662.416, units.area.acres.to_square_metres(5.6), places=1)

	def test_convert_known_acres_to_square_miles(self):
		self.assertAlmostEqual(1.576562, units.area.acres.to_square_miles(1009.0), places=1)
		self.assertAlmostEqual(0.140625, units.area.acres.to_square_miles(90.0), places=1)
		self.assertAlmostEqual(1.19531, units.area.acres.to_square_miles(765.0), places=1)

	def test_convert_known_acres_to_square_yards(self):
		self.assertAlmostEqual(16456.0, units.area.acres.to_square_yards(3.4), places=1)
		self.assertAlmostEqual(3388.0, units.area.acres.to_square_yards(0.7), places=1)
		self.assertAlmostEqual(48.4, units.area.acres.to_square_yards(0.01), places=1)

	def test_convert_known_acres_to_square_feet(self):
		self.assertAlmostEqual(435.6, units.area.acres.to_square_feet(0.01), places=1)
		self.assertAlmostEqual(522720.0, units.area.acres.to_square_feet(12.0), places=1)
		self.assertAlmostEqual(29185.2, units.area.acres.to_square_feet(0.67), places=1)

	def test_convert_known_acres_to_square_inches(self):
		self.assertAlmostEqual(564537.6, units.area.acres.to_square_inches(0.09), places=1)
		self.assertAlmostEqual(31363.2, units.area.acres.to_square_inches(0.005), places=1)
		self.assertAlmostEqual(75271.68, units.area.acres.to_square_inches(0.012), places=1)

	def test_convert_known_acres_to_hectares(self):
		self.assertAlmostEqual(448.7964, units.area.acres.to_hectares(1109.0), places=1)
		self.assertAlmostEqual(2.26624, units.area.acres.to_hectares(5.6), places=1)
		self.assertAlmostEqual(0.4977633, units.area.acres.to_hectares(1.23), places=1)

if __name__ == '__main__':
    unittest.main()
