# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.fuel_economy.miles_per_gallon

class TestMilesPerGallonMethods(unittest.TestCase):

	def test_convert_known_miles_per_gallon_to_kilometre_per_litre(self):
		self.assertAlmostEqual(4.24807, units.fuel_economy.miles_per_gallon.to_kilometre_per_litre(12.0), places=1)
		self.assertAlmostEqual(2.90285, units.fuel_economy.miles_per_gallon.to_kilometre_per_litre(8.2), places=1)
		self.assertAlmostEqual(0.177003, units.fuel_economy.miles_per_gallon.to_kilometre_per_litre(0.5), places=1)

	def test_convert_known_miles_per_gallon_to_u_s_miles_per_gallon(self):
		self.assertAlmostEqual(1.16574, units.fuel_economy.miles_per_gallon.to_u_s_miles_per_gallon(1.4), places=1)
		self.assertAlmostEqual(590.36575, units.fuel_economy.miles_per_gallon.to_u_s_miles_per_gallon(709.0), places=1)
		self.assertAlmostEqual(0.74941, units.fuel_economy.miles_per_gallon.to_u_s_miles_per_gallon(0.9), places=1)

if __name__ == '__main__':
    unittest.main()
