# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.luminous_energy.talbot

class TestTalbotMethods(unittest.TestCase):

	def test_convert_known_talbot_to_lumen_second(self):
		self.assertAlmostEqual(100.0, units.luminous_energy.talbot.to_lumen_second(100.0), places=1)
		self.assertAlmostEqual(0.9, units.luminous_energy.talbot.to_lumen_second(0.9), places=1)
		self.assertAlmostEqual(23.1, units.luminous_energy.talbot.to_lumen_second(23.1), places=1)

	def test_convert_known_talbot_to_lumen_hour(self):
		self.assertAlmostEqual(0.222, units.luminous_energy.talbot.to_lumen_hour(800.0), places=1)
		self.assertAlmostEqual(1.885833, units.luminous_energy.talbot.to_lumen_hour(6789.0), places=1)
		self.assertAlmostEqual(3.027778, units.luminous_energy.talbot.to_lumen_hour(10900.0), places=1)

	def test_convert_known_talbot_to_lumen_minute(self):
		self.assertAlmostEqual(15.0, units.luminous_energy.talbot.to_lumen_minute(900.0), places=1)
		self.assertAlmostEqual(1.315, units.luminous_energy.talbot.to_lumen_minute(78.9), places=1)
		self.assertAlmostEqual(25.0, units.luminous_energy.talbot.to_lumen_minute(1500.0), places=1)

if __name__ == '__main__':
    unittest.main()
