# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.angle.minute_of_arc

class TestMinuteOfArcMethods(unittest.TestCase):

	def test_convert_known_minute_of_arc_to_degrees(self):
		self.assertAlmostEqual(1.48333, units.angle.minute_of_arc.to_degrees(89.0), places=1)
		self.assertAlmostEqual(2.675, units.angle.minute_of_arc.to_degrees(160.5), places=1)
		self.assertAlmostEqual(0.015, units.angle.minute_of_arc.to_degrees(0.9), places=1)

	def test_convert_known_minute_of_arc_to_radians(self):
		self.assertAlmostEqual(0.5206899, units.angle.minute_of_arc.to_radians(1790.0), places=1)
		self.assertAlmostEqual(2.908591, units.angle.minute_of_arc.to_radians(9999.0), places=1)
		self.assertAlmostEqual(3.5910149, units.angle.minute_of_arc.to_radians(12345.0), places=1)

	def test_convert_known_minute_of_arc_to_gradians(self):
		self.assertAlmostEqual(5.55556, units.angle.minute_of_arc.to_gradians(300.0), places=1)
		self.assertAlmostEqual(18.68519, units.angle.minute_of_arc.to_gradians(1009.0), places=1)
		self.assertAlmostEqual(124.083335, units.angle.minute_of_arc.to_gradians(6700.5), places=1)

	def test_convert_known_minute_of_arc_to_milliradians(self):
		self.assertAlmostEqual(174.533, units.angle.minute_of_arc.to_milliradians(600.0), places=1)
		self.assertAlmostEqual(26.38356, units.angle.minute_of_arc.to_milliradians(90.7), places=1)
		self.assertAlmostEqual(494.51, units.angle.minute_of_arc.to_milliradians(1700.0), places=1)

	def test_convert_known_minute_of_arc_to_seconds_of_arc(self):
		self.assertAlmostEqual(54.0, units.angle.minute_of_arc.to_seconds_of_arc(0.9), places=1)
		self.assertAlmostEqual(4200.0, units.angle.minute_of_arc.to_seconds_of_arc(70.0), places=1)
		self.assertAlmostEqual(54096.0, units.angle.minute_of_arc.to_seconds_of_arc(901.6), places=1)

if __name__ == '__main__':
    unittest.main()
