# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.speed.feet_per_second

class TestFeetPerSecondMethods(unittest.TestCase):

	def test_convert_known_feet_per_second_to_miles_per_hour(self):
		self.assertAlmostEqual(9.886364, units.speed.feet_per_second.to_miles_per_hour(14.5), places=1)
		self.assertAlmostEqual(68.1818, units.speed.feet_per_second.to_miles_per_hour(100.0), places=1)
		self.assertAlmostEqual(1.09091, units.speed.feet_per_second.to_miles_per_hour(1.6), places=1)

	def test_convert_known_feet_per_second_to_kilometres_per_hour(self):
		self.assertAlmostEqual(1.64592, units.speed.feet_per_second.to_kilometres_per_hour(1.5), places=1)
		self.assertAlmostEqual(74.50531, units.speed.feet_per_second.to_kilometres_per_hour(67.9), places=1)
		self.assertAlmostEqual(119.604, units.speed.feet_per_second.to_kilometres_per_hour(109.0), places=1)

	def test_convert_known_feet_per_second_to_metres_per_second(self):
		self.assertAlmostEqual(3.29184, units.speed.feet_per_second.to_metres_per_second(10.8), places=1)
		self.assertAlmostEqual(20.1168, units.speed.feet_per_second.to_metres_per_second(66.0), places=1)
		self.assertAlmostEqual(0.70104, units.speed.feet_per_second.to_metres_per_second(2.3), places=1)

	def test_convert_known_feet_per_second_to_knots(self):
		self.assertAlmostEqual(1.36271, units.speed.feet_per_second.to_knots(2.3), places=1)
		self.assertAlmostEqual(394.594, units.speed.feet_per_second.to_knots(666.0), places=1)
		self.assertAlmostEqual(10.13147, units.speed.feet_per_second.to_knots(17.1), places=1)

if __name__ == '__main__':
    unittest.main()
