# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.volume.u_s_pints

class TestUSPintsMethods(unittest.TestCase):

	def test_convert_known_u_s_pints_to_millilitres(self):
		self.assertAlmostEqual(312.2965, units.volume.u_s_pints.to_millilitres(0.66), places=1)
		self.assertAlmostEqual(4305.91, units.volume.u_s_pints.to_millilitres(9.1), places=1)
		self.assertAlmostEqual(378.541, units.volume.u_s_pints.to_millilitres(0.8), places=1)

	def test_convert_known_u_s_pints_to_litres(self):
		self.assertAlmostEqual(0.709765, units.volume.u_s_pints.to_litres(1.5), places=1)
		self.assertAlmostEqual(0.283906, units.volume.u_s_pints.to_litres(0.6), places=1)
		self.assertAlmostEqual(646.8322, units.volume.u_s_pints.to_litres(1367.0), places=1)

	def test_convert_known_u_s_pints_to_kilolitres(self):
		self.assertAlmostEqual(0.8990353, units.volume.u_s_pints.to_kilolitres(1900.0), places=1)
		self.assertAlmostEqual(4.205592, units.volume.u_s_pints.to_kilolitres(8888.0), places=1)
		self.assertAlmostEqual(58.4164747, units.volume.u_s_pints.to_kilolitres(123456.0), places=1)

	def test_convert_known_u_s_pints_to_teaspoons(self):
		self.assertAlmostEqual(479.62, units.volume.u_s_pints.to_teaspoons(6.0), places=1)
		self.assertAlmostEqual(6.394935, units.volume.u_s_pints.to_teaspoons(0.08), places=1)
		self.assertAlmostEqual(247.804, units.volume.u_s_pints.to_teaspoons(3.1), places=1)

	def test_convert_known_u_s_pints_to_tablespoons(self):
		self.assertAlmostEqual(53.2911, units.volume.u_s_pints.to_tablespoons(2.0), places=1)
		self.assertAlmostEqual(2.398101, units.volume.u_s_pints.to_tablespoons(0.09), places=1)
		self.assertAlmostEqual(44711.25, units.volume.u_s_pints.to_tablespoons(1678.0), places=1)

	def test_convert_known_u_s_pints_to_quarts(self):
		self.assertAlmostEqual(4.99605, units.volume.u_s_pints.to_quarts(12.0), places=1)
		self.assertAlmostEqual(209.75063, units.volume.u_s_pints.to_quarts(503.8), places=1)
		self.assertAlmostEqual(0.2706191, units.volume.u_s_pints.to_quarts(0.65), places=1)

	def test_convert_known_u_s_pints_to_pints(self):
		self.assertAlmostEqual(0.749407, units.volume.u_s_pints.to_pints(0.9), places=1)
		self.assertAlmostEqual(84.9328, units.volume.u_s_pints.to_pints(102.0), places=1)
		self.assertAlmostEqual(6661.97635, units.volume.u_s_pints.to_pints(8000.7), places=1)

	def test_convert_known_u_s_pints_to_gallons(self):
		self.assertAlmostEqual(8.32674, units.volume.u_s_pints.to_gallons(80.0), places=1)
		self.assertAlmostEqual(0.645322, units.volume.u_s_pints.to_gallons(6.2), places=1)
		self.assertAlmostEqual(0.072859, units.volume.u_s_pints.to_gallons(0.7), places=1)

	def test_convert_known_u_s_pints_to_fluid_ounces(self):
		self.assertAlmostEqual(199.842, units.volume.u_s_pints.to_fluid_ounces(12.0), places=1)
		self.assertAlmostEqual(161.539, units.volume.u_s_pints.to_fluid_ounces(9.7), places=1)
		self.assertAlmostEqual(2065.03, units.volume.u_s_pints.to_fluid_ounces(124.0), places=1)

	def test_convert_known_u_s_pints_to_u_s_teaspoons(self):
		self.assertAlmostEqual(384.0, units.volume.u_s_pints.to_u_s_teaspoons(4.0), places=1)
		self.assertAlmostEqual(240.0, units.volume.u_s_pints.to_u_s_teaspoons(2.5), places=1)
		self.assertAlmostEqual(768182.4, units.volume.u_s_pints.to_u_s_teaspoons(8001.9), places=1)

	def test_convert_known_u_s_pints_to_u_s_tablespoons(self):
		self.assertAlmostEqual(2560.0, units.volume.u_s_pints.to_u_s_tablespoons(80.0), places=1)
		self.assertAlmostEqual(406.4, units.volume.u_s_pints.to_u_s_tablespoons(12.7), places=1)
		self.assertAlmostEqual(19.2, units.volume.u_s_pints.to_u_s_tablespoons(0.6), places=1)

	def test_convert_known_u_s_pints_to_u_s_quarts(self):
		self.assertAlmostEqual(0.3, units.volume.u_s_pints.to_u_s_quarts(0.6), places=1)
		self.assertAlmostEqual(5045.0, units.volume.u_s_pints.to_u_s_quarts(10090.0), places=1)
		self.assertAlmostEqual(2.28, units.volume.u_s_pints.to_u_s_quarts(4.56), places=1)

	def test_convert_known_u_s_pints_to_u_s_gallons(self):
		self.assertAlmostEqual(0.57, units.volume.u_s_pints.to_u_s_gallons(4.56), places=1)
		self.assertAlmostEqual(1125.0, units.volume.u_s_pints.to_u_s_gallons(9000.0), places=1)
		self.assertAlmostEqual(5.9, units.volume.u_s_pints.to_u_s_gallons(47.2), places=1)

	def test_convert_known_u_s_pints_to_u_s_fluid_ounces(self):
		self.assertAlmostEqual(755.2, units.volume.u_s_pints.to_u_s_fluid_ounces(47.2), places=1)
		self.assertAlmostEqual(16016.0, units.volume.u_s_pints.to_u_s_fluid_ounces(1001.0), places=1)
		self.assertAlmostEqual(382.4, units.volume.u_s_pints.to_u_s_fluid_ounces(23.9), places=1)

	def test_convert_known_u_s_pints_to_u_s_cups(self):
		self.assertAlmostEqual(47.8, units.volume.u_s_pints.to_u_s_cups(23.9), places=1)
		self.assertAlmostEqual(2018.0, units.volume.u_s_pints.to_u_s_cups(1009.0), places=1)
		self.assertAlmostEqual(91.8, units.volume.u_s_pints.to_u_s_cups(45.9), places=1)

if __name__ == '__main__':
    unittest.main()
