# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.fuel_economy.litresper100_kilometres

class TestLitresper100KilometresMethods(unittest.TestCase):

	def test_convert_known_litresper100_kilometres_to_kilometre_per_litre(self):
		self.assertAlmostEqual(142.857, units.fuel_economy.litresper100_kilometres.to_kilometre_per_litre(0.7), places=1)
		self.assertAlmostEqual(0.917431, units.fuel_economy.litresper100_kilometres.to_kilometre_per_litre(109.0), places=1)
		self.assertAlmostEqual(8333.3333, units.fuel_economy.litresper100_kilometres.to_kilometre_per_litre(0.012), places=1)

	def test_convert_known_litresper100_kilometres_to_miles_per_gallon(self):
		self.assertAlmostEqual(2.64001, units.fuel_economy.litresper100_kilometres.to_miles_per_gallon(107.0), places=1)
		self.assertAlmostEqual(353.101, units.fuel_economy.litresper100_kilometres.to_miles_per_gallon(0.8), places=1)
		self.assertAlmostEqual(14124.05, units.fuel_economy.litresper100_kilometres.to_miles_per_gallon(0.02), places=1)

	def test_convert_known_litresper100_kilometres_to_u_s_miles_per_gallon(self):
		self.assertAlmostEqual(19.6012, units.fuel_economy.litresper100_kilometres.to_u_s_miles_per_gallon(12.0), places=1)
		self.assertAlmostEqual(784.049, units.fuel_economy.litresper100_kilometres.to_u_s_miles_per_gallon(0.3), places=1)
		self.assertAlmostEqual(156.81, units.fuel_economy.litresper100_kilometres.to_u_s_miles_per_gallon(1.5), places=1)

if __name__ == '__main__':
    unittest.main()
