# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.mass.carats

class TestCaratsMethods(unittest.TestCase):

	def test_convert_known_carats_to_milligrams(self):
		self.assertAlmostEqual(420.0, units.mass.carats.to_milligrams(2.1), places=1)
		self.assertAlmostEqual(24600.0, units.mass.carats.to_milligrams(123.0), places=1)
		self.assertAlmostEqual(160.0, units.mass.carats.to_milligrams(0.8), places=1)

	def test_convert_known_carats_to_grams(self):
		self.assertAlmostEqual(0.16, units.mass.carats.to_grams(0.8), places=1)
		self.assertAlmostEqual(0.3, units.mass.carats.to_grams(1.5), places=1)
		self.assertAlmostEqual(2.4, units.mass.carats.to_grams(12.0), places=1)

	def test_convert_known_carats_to_kilograms(self):
		self.assertAlmostEqual(0.2018, units.mass.carats.to_kilograms(1009.0), places=1)
		self.assertAlmostEqual(0.1998, units.mass.carats.to_kilograms(999.0), places=1)
		self.assertAlmostEqual(0.2469, units.mass.carats.to_kilograms(1234.5), places=1)

	def test_convert_known_carats_to_tonnes(self):
		self.assertAlmostEqual(0.2469134, units.mass.carats.to_tonnes(1234567.0), places=1)
		self.assertAlmostEqual(1.9999998, units.mass.carats.to_tonnes(9999999.0), places=1)
		self.assertAlmostEqual(0.199775598, units.mass.carats.to_tonnes(998877.99), places=1)

	def test_convert_known_carats_to_ounces(self):
		self.assertAlmostEqual(6.34931, units.mass.carats.to_ounces(900.0), places=1)
		self.assertAlmostEqual(0.870914121, units.mass.carats.to_ounces(123.45), places=1)
		self.assertAlmostEqual(5.64383, units.mass.carats.to_ounces(800.0), places=1)

	def test_convert_known_carats_to_pounds(self):
		self.assertAlmostEqual(0.440925, units.mass.carats.to_pounds(1000.0), places=1)
		self.assertAlmostEqual(54.4347781, units.mass.carats.to_pounds(123456.0), places=1)
		self.assertAlmostEqual(0.35274, units.mass.carats.to_pounds(800.0), places=1)

	def test_convert_known_carats_to_stones(self):
		self.assertAlmostEqual(0.2834515, units.mass.carats.to_stones(9000.0), places=1)
		self.assertAlmostEqual(3.88819843, units.mass.carats.to_stones(123456.0), places=1)
		self.assertAlmostEqual(2.519593906, units.mass.carats.to_stones(80000.8), places=1)

if __name__ == '__main__':
    unittest.main()
