# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.data_transfer_rate.mega_bits_per_second

class TestMegaBitsPerSecondMethods(unittest.TestCase):

	def test_convert_known_mega_bits_per_second_to_bits_per_second(self):
		self.assertAlmostEqual(340000.0, units.data_transfer_rate.mega_bits_per_second.to_bits_per_second(0.34), places=1)
		self.assertAlmostEqual(9120000.0, units.data_transfer_rate.mega_bits_per_second.to_bits_per_second(9.12), places=1)
		self.assertAlmostEqual(987000.0, units.data_transfer_rate.mega_bits_per_second.to_bits_per_second(0.987), places=1)

	def test_convert_known_mega_bits_per_second_to_kilo_bits_per_second(self):
		self.assertAlmostEqual(770.0, units.data_transfer_rate.mega_bits_per_second.to_kilo_bits_per_second(0.77), places=1)
		self.assertAlmostEqual(5000.0, units.data_transfer_rate.mega_bits_per_second.to_kilo_bits_per_second(5.0), places=1)
		self.assertAlmostEqual(987.0, units.data_transfer_rate.mega_bits_per_second.to_kilo_bits_per_second(0.987), places=1)

	def test_convert_known_mega_bits_per_second_to_giga_bits_per_second(self):
		self.assertAlmostEqual(0.9, units.data_transfer_rate.mega_bits_per_second.to_giga_bits_per_second(900.0), places=1)
		self.assertAlmostEqual(12.345, units.data_transfer_rate.mega_bits_per_second.to_giga_bits_per_second(12345.0), places=1)
		self.assertAlmostEqual(0.1891, units.data_transfer_rate.mega_bits_per_second.to_giga_bits_per_second(189.1), places=1)

	def test_convert_known_mega_bits_per_second_to_tera_bits_per_second(self):
		self.assertAlmostEqual(100.2003, units.data_transfer_rate.mega_bits_per_second.to_tera_bits_per_second(100200300.0), places=1)
		self.assertAlmostEqual(99.887777, units.data_transfer_rate.mega_bits_per_second.to_tera_bits_per_second(99887777.0), places=1)
		self.assertAlmostEqual(0.080009, units.data_transfer_rate.mega_bits_per_second.to_tera_bits_per_second(80009.0), places=1)

	def test_convert_known_mega_bits_per_second_to_kilo_bytes_per_second(self):
		self.assertAlmostEqual(1125.0, units.data_transfer_rate.mega_bits_per_second.to_kilo_bytes_per_second(9.0), places=1)
		self.assertAlmostEqual(153.75, units.data_transfer_rate.mega_bits_per_second.to_kilo_bytes_per_second(1.23), places=1)
		self.assertAlmostEqual(12262.5, units.data_transfer_rate.mega_bits_per_second.to_kilo_bytes_per_second(98.1), places=1)

	def test_convert_known_mega_bits_per_second_to_mega_bytes_per_second(self):
		self.assertAlmostEqual(12.2625, units.data_transfer_rate.mega_bits_per_second.to_mega_bytes_per_second(98.1), places=1)
		self.assertAlmostEqual(1.3625, units.data_transfer_rate.mega_bits_per_second.to_mega_bytes_per_second(10.9), places=1)
		self.assertAlmostEqual(111.015375, units.data_transfer_rate.mega_bits_per_second.to_mega_bytes_per_second(888.123), places=1)

	def test_convert_known_mega_bits_per_second_to_giga_bytes_per_second(self):
		self.assertAlmostEqual(0.1125, units.data_transfer_rate.mega_bits_per_second.to_giga_bytes_per_second(900.0), places=1)
		self.assertAlmostEqual(1.265375, units.data_transfer_rate.mega_bits_per_second.to_giga_bytes_per_second(10123.0), places=1)
		self.assertAlmostEqual(1.2485, units.data_transfer_rate.mega_bits_per_second.to_giga_bytes_per_second(9988.0), places=1)

	def test_convert_known_mega_bits_per_second_to_tera_bytes_per_second(self):
		self.assertAlmostEqual(0.124859625, units.data_transfer_rate.mega_bits_per_second.to_tera_bytes_per_second(998877.0), places=1)
		self.assertAlmostEqual(12.5250375, units.data_transfer_rate.mega_bits_per_second.to_tera_bytes_per_second(100200400.0), places=1)
		self.assertAlmostEqual(1.126109625, units.data_transfer_rate.mega_bits_per_second.to_tera_bytes_per_second(9008877.0), places=1)

	def test_convert_known_mega_bits_per_second_to_kibibits_per_second(self):
		self.assertAlmostEqual(11718.756, units.data_transfer_rate.mega_bits_per_second.to_kibibits_per_second(12.0), places=1)
		self.assertAlmostEqual(878.906, units.data_transfer_rate.mega_bits_per_second.to_kibibits_per_second(0.9), places=1)
		self.assertAlmostEqual(1201.172, units.data_transfer_rate.mega_bits_per_second.to_kibibits_per_second(1.23), places=1)

	def test_convert_known_mega_bits_per_second_to_mebibits_per_second(self):
		self.assertAlmostEqual(4.29153, units.data_transfer_rate.mega_bits_per_second.to_mebibits_per_second(4.5), places=1)
		self.assertAlmostEqual(0.762939, units.data_transfer_rate.mega_bits_per_second.to_mebibits_per_second(0.8), places=1)
		self.assertAlmostEqual(858.307, units.data_transfer_rate.mega_bits_per_second.to_mebibits_per_second(900.0), places=1)

if __name__ == '__main__':
    unittest.main()
