# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.area.square_feet

class TestSquareFeetMethods(unittest.TestCase):

	def test_convert_known_square_feet_to_square_kilometres(self):
		self.assertAlmostEqual(8.2681630146, units.area.square_feet.to_square_kilometres(88997766.0), places=1)
		self.assertAlmostEqual(0.92986671317, units.area.square_feet.to_square_kilometres(10009002.0), places=1)
		self.assertAlmostEqual(91.75608889, units.area.square_feet.to_square_kilometres(987654321.0), places=1)

	def test_convert_known_square_feet_to_square_metres(self):
		self.assertAlmostEqual(83.6127, units.area.square_feet.to_square_metres(900.0), places=1)
		self.assertAlmostEqual(74.24095603, units.area.square_feet.to_square_metres(799.123), places=1)
		self.assertAlmostEqual(46.4515, units.area.square_feet.to_square_metres(500.0), places=1)

	def test_convert_known_square_feet_to_square_miles(self):
		self.assertAlmostEqual(0.43044077135, units.area.square_feet.to_square_miles(12000000.0), places=1)
		self.assertAlmostEqual(35.4272239799, units.area.square_feet.to_square_miles(987654321.0), places=1)
		self.assertAlmostEqual(32.3117790117, units.area.square_feet.to_square_miles(900800700.0), places=1)

	def test_convert_known_square_feet_to_square_yards(self):
		self.assertAlmostEqual(101.0, units.area.square_feet.to_square_yards(909.0), places=1)
		self.assertAlmostEqual(13.71733333, units.area.square_feet.to_square_yards(123.456), places=1)
		self.assertAlmostEqual(889.8889, units.area.square_feet.to_square_yards(8009.0), places=1)

	def test_convert_known_square_feet_to_square_inches(self):
		self.assertAlmostEqual(964.8, units.area.square_feet.to_square_inches(6.7), places=1)
		self.assertAlmostEqual(216.0, units.area.square_feet.to_square_inches(1.5), places=1)
		self.assertAlmostEqual(129.6, units.area.square_feet.to_square_inches(0.9), places=1)

	def test_convert_known_square_feet_to_hectares(self):
		self.assertAlmostEqual(0.83612736, units.area.square_feet.to_hectares(90000.0), places=1)
		self.assertAlmostEqual(1.11595132, units.area.square_feet.to_hectares(120120.0), places=1)
		self.assertAlmostEqual(0.83678697, units.area.square_feet.to_hectares(90071.0), places=1)

	def test_convert_known_square_feet_to_acres(self):
		self.assertAlmostEqual(2.0661157, units.area.square_feet.to_acres(90000.0), places=1)
		self.assertAlmostEqual(2.83415978, units.area.square_feet.to_acres(123456.0), places=1)
		self.assertAlmostEqual(0.2022268, units.area.square_feet.to_acres(8809.0), places=1)

if __name__ == '__main__':
    unittest.main()
