# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.frequency.gigahertz

class TestGigahertzMethods(unittest.TestCase):

	def test_convert_known_gigahertz_to_hertz(self):
		self.assertAlmostEqual(9000000.0, units.frequency.gigahertz.to_hertz(0.009), places=1)
		self.assertAlmostEqual(123000.0, units.frequency.gigahertz.to_hertz(0.000123), places=1)
		self.assertAlmostEqual(45600.0, units.frequency.gigahertz.to_hertz(0.0000456), places=1)

	def test_convert_known_gigahertz_to_kilohertz(self):
		self.assertAlmostEqual(9000.0, units.frequency.gigahertz.to_kilohertz(0.009), places=1)
		self.assertAlmostEqual(10.0, units.frequency.gigahertz.to_kilohertz(1e-5), places=1)
		self.assertAlmostEqual(65.0, units.frequency.gigahertz.to_kilohertz(0.000065), places=1)

	def test_convert_known_gigahertz_to_megahertz(self):
		self.assertAlmostEqual(900.0, units.frequency.gigahertz.to_megahertz(0.9), places=1)
		self.assertAlmostEqual(12.3, units.frequency.gigahertz.to_megahertz(0.0123), places=1)
		self.assertAlmostEqual(5000.0, units.frequency.gigahertz.to_megahertz(5.0), places=1)

if __name__ == '__main__':
    unittest.main()
