# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.volume.gallons

class TestGallonsMethods(unittest.TestCase):

	def test_convert_known_gallons_to_millilitres(self):
		self.assertAlmostEqual(5909.92, units.volume.gallons.to_millilitres(1.3), places=1)
		self.assertAlmostEqual(2045.741, units.volume.gallons.to_millilitres(0.45), places=1)
		self.assertAlmostEqual(8182.96, units.volume.gallons.to_millilitres(1.8), places=1)

	def test_convert_known_gallons_to_litres(self):
		self.assertAlmostEqual(559.169, units.volume.gallons.to_litres(123.0), places=1)
		self.assertAlmostEqual(42.2786, units.volume.gallons.to_litres(9.3), places=1)
		self.assertAlmostEqual(3.04588, units.volume.gallons.to_litres(0.67), places=1)

	def test_convert_known_gallons_to_kilolitres(self):
		self.assertAlmostEqual(4.587005, units.volume.gallons.to_kilolitres(1009.0), places=1)
		self.assertAlmostEqual(0.0436425, units.volume.gallons.to_kilolitres(9.6), places=1)
		self.assertAlmostEqual(561.242087, units.volume.gallons.to_kilolitres(123456.0), places=1)

	def test_convert_known_gallons_to_teaspoons(self):
		self.assertAlmostEqual(4608.0, units.volume.gallons.to_teaspoons(6.0), places=1)
		self.assertAlmostEqual(59996.16, units.volume.gallons.to_teaspoons(78.12), places=1)
		self.assertAlmostEqual(261.1199, units.volume.gallons.to_teaspoons(0.34), places=1)

	def test_convert_known_gallons_to_tablespoons(self):
		self.assertAlmostEqual(230.4, units.volume.gallons.to_tablespoons(0.9), places=1)
		self.assertAlmostEqual(409.6, units.volume.gallons.to_tablespoons(1.6), places=1)
		self.assertAlmostEqual(84.47997, units.volume.gallons.to_tablespoons(0.33), places=1)

	def test_convert_known_gallons_to_quarts(self):
		self.assertAlmostEqual(436.0, units.volume.gallons.to_quarts(109.0), places=1)
		self.assertAlmostEqual(23.2, units.volume.gallons.to_quarts(5.8), places=1)
		self.assertAlmostEqual(0.92, units.volume.gallons.to_quarts(0.23), places=1)

	def test_convert_known_gallons_to_pints(self):
		self.assertAlmostEqual(1.84, units.volume.gallons.to_pints(0.23), places=1)
		self.assertAlmostEqual(1520.0, units.volume.gallons.to_pints(190.0), places=1)
		self.assertAlmostEqual(197.6, units.volume.gallons.to_pints(24.7), places=1)

	def test_convert_known_gallons_to_fluid_ounces(self):
		self.assertAlmostEqual(3952.0, units.volume.gallons.to_fluid_ounces(24.7), places=1)
		self.assertAlmostEqual(2094.4, units.volume.gallons.to_fluid_ounces(13.09), places=1)
		self.assertAlmostEqual(928.0, units.volume.gallons.to_fluid_ounces(5.8), places=1)

	def test_convert_known_gallons_to_u_s_teaspoons(self):
		self.assertAlmostEqual(5349.51, units.volume.gallons.to_u_s_teaspoons(5.8), places=1)
		self.assertAlmostEqual(405.8251, units.volume.gallons.to_u_s_teaspoons(0.44), places=1)
		self.assertAlmostEqual(1752.43, units.volume.gallons.to_u_s_teaspoons(1.9), places=1)

	def test_convert_known_gallons_to_u_s_tablespoons(self):
		self.assertAlmostEqual(553.398, units.volume.gallons.to_u_s_tablespoons(1.8), places=1)
		self.assertAlmostEqual(101.4562, units.volume.gallons.to_u_s_tablespoons(0.33), places=1)
		self.assertAlmostEqual(30744.33080, units.volume.gallons.to_u_s_tablespoons(100.0), places=1)

	def test_convert_known_gallons_to_u_s_quarts(self):
		self.assertAlmostEqual(374.696, units.volume.gallons.to_u_s_quarts(78.0), places=1)
		self.assertAlmostEqual(8.16646, units.volume.gallons.to_u_s_quarts(1.7), places=1)
		self.assertAlmostEqual(81.18421, units.volume.gallons.to_u_s_quarts(16.9), places=1)

	def test_convert_known_gallons_to_u_s_pints(self):
		self.assertAlmostEqual(128.7418, units.volume.gallons.to_u_s_pints(13.4), places=1)
		self.assertAlmostEqual(78.01371, units.volume.gallons.to_u_s_pints(8.12), places=1)
		self.assertAlmostEqual(9.511523, units.volume.gallons.to_u_s_pints(0.99), places=1)

	def test_convert_known_gallons_to_u_s_gallons(self):
		self.assertAlmostEqual(1.80142, units.volume.gallons.to_u_s_gallons(1.5), places=1)
		self.assertAlmostEqual(0.9367409, units.volume.gallons.to_u_s_gallons(0.78), places=1)
		self.assertAlmostEqual(123.698, units.volume.gallons.to_u_s_gallons(103.0), places=1)

	def test_convert_known_gallons_to_u_s_fluid_ounces(self):
		self.assertAlmostEqual(17063.1, units.volume.gallons.to_u_s_fluid_ounces(111.0), places=1)
		self.assertAlmostEqual(13819.57, units.volume.gallons.to_u_s_fluid_ounces(89.9), places=1)
		self.assertAlmostEqual(184.466, units.volume.gallons.to_u_s_fluid_ounces(1.2), places=1)

	def test_convert_known_gallons_to_u_s_cups(self):
		self.assertAlmostEqual(23.0582, units.volume.gallons.to_u_s_cups(1.2), places=1)
		self.assertAlmostEqual(10.56836, units.volume.gallons.to_u_s_cups(0.55), places=1)
		self.assertAlmostEqual(17101.534007630, units.volume.gallons.to_u_s_cups(890.0), places=1)

if __name__ == '__main__':
    unittest.main()
