# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.luminous_energy.lumen_minute

class TestLumenMinuteMethods(unittest.TestCase):

	def test_convert_known_lumen_minute_to_talbot(self):
		self.assertAlmostEqual(42.0, units.luminous_energy.lumen_minute.to_talbot(0.7), places=1)
		self.assertAlmostEqual(40680.0, units.luminous_energy.lumen_minute.to_talbot(678.0), places=1)
		self.assertAlmostEqual(5340.0, units.luminous_energy.lumen_minute.to_talbot(89.0), places=1)

	def test_convert_known_lumen_minute_to_lumen_hour(self):
		self.assertAlmostEqual(1.4833, units.luminous_energy.lumen_minute.to_lumen_hour(89.0), places=1)
		self.assertAlmostEqual(0.15, units.luminous_energy.lumen_minute.to_lumen_hour(9.0), places=1)
		self.assertAlmostEqual(0.00205, units.luminous_energy.lumen_minute.to_lumen_hour(0.123), places=1)

	def test_convert_known_lumen_minute_to_lumen_second(self):
		self.assertAlmostEqual(7.38, units.luminous_energy.lumen_minute.to_lumen_second(0.123), places=1)
		self.assertAlmostEqual(480000.0, units.luminous_energy.lumen_minute.to_lumen_second(8000.0), places=1)
		self.assertAlmostEqual(2046.0, units.luminous_energy.lumen_minute.to_lumen_second(34.1), places=1)

if __name__ == '__main__':
    unittest.main()
