# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.data_transfer_rate.kibibits_per_second

class TestKibibitsPerSecondMethods(unittest.TestCase):

	def test_convert_known_kibibits_per_second_to_bits_per_second(self):
		self.assertAlmostEqual(2048.0, units.data_transfer_rate.kibibits_per_second.to_bits_per_second(2.0), places=1)
		self.assertAlmostEqual(9216.0, units.data_transfer_rate.kibibits_per_second.to_bits_per_second(9.0), places=1)
		self.assertAlmostEqual(18227.2, units.data_transfer_rate.kibibits_per_second.to_bits_per_second(17.8), places=1)

	def test_convert_known_kibibits_per_second_to_kilo_bits_per_second(self):
		self.assertAlmostEqual(6.3488, units.data_transfer_rate.kibibits_per_second.to_kilo_bits_per_second(6.2), places=1)
		self.assertAlmostEqual(0.9216, units.data_transfer_rate.kibibits_per_second.to_kilo_bits_per_second(0.9), places=1)
		self.assertAlmostEqual(89.088, units.data_transfer_rate.kibibits_per_second.to_kilo_bits_per_second(87.0), places=1)

	def test_convert_known_kibibits_per_second_to_mega_bits_per_second(self):
		self.assertAlmostEqual(0.089088, units.data_transfer_rate.kibibits_per_second.to_mega_bits_per_second(87.0), places=1)
		self.assertAlmostEqual(0.01263616, units.data_transfer_rate.kibibits_per_second.to_mega_bits_per_second(12.34), places=1)
		self.assertAlmostEqual(126.418879, units.data_transfer_rate.kibibits_per_second.to_mega_bits_per_second(123456.0), places=1)

	def test_convert_known_kibibits_per_second_to_giga_bits_per_second(self):
		self.assertAlmostEqual(0.126418944, units.data_transfer_rate.kibibits_per_second.to_giga_bits_per_second(123456.0), places=1)
		self.assertAlmostEqual(8.192, units.data_transfer_rate.kibibits_per_second.to_giga_bits_per_second(8000000.0), places=1)
		self.assertAlmostEqual(1.307521024, units.data_transfer_rate.kibibits_per_second.to_giga_bits_per_second(1276876.0), places=1)

	def test_convert_known_kibibits_per_second_to_tera_bits_per_second(self):
		self.assertAlmostEqual(0.8192, units.data_transfer_rate.kibibits_per_second.to_tera_bits_per_second(800000000.0), places=1)
		self.assertAlmostEqual(1536.0, units.data_transfer_rate.kibibits_per_second.to_tera_bits_per_second(1.5e12), places=1)
		self.assertAlmostEqual(0.01023999898, units.data_transfer_rate.kibibits_per_second.to_tera_bits_per_second(9999999.0), places=1)

	def test_convert_known_kibibits_per_second_to_kilo_bytes_per_second(self):
		self.assertAlmostEqual(117.632, units.data_transfer_rate.kibibits_per_second.to_kilo_bytes_per_second(919.0), places=1)
		self.assertAlmostEqual(9.9072, units.data_transfer_rate.kibibits_per_second.to_kilo_bytes_per_second(77.4), places=1)
		self.assertAlmostEqual(13.965952, units.data_transfer_rate.kibibits_per_second.to_kilo_bytes_per_second(109.109), places=1)

	def test_convert_known_kibibits_per_second_to_mega_bytes_per_second(self):
		self.assertAlmostEqual(0.128, units.data_transfer_rate.kibibits_per_second.to_mega_bytes_per_second(1000.0), places=1)
		self.assertAlmostEqual(0.102415744, units.data_transfer_rate.kibibits_per_second.to_mega_bytes_per_second(800.123), places=1)
		self.assertAlmostEqual(15.802368, units.data_transfer_rate.kibibits_per_second.to_mega_bytes_per_second(123456.0), places=1)

	def test_convert_known_kibibits_per_second_to_giga_bytes_per_second(self):
		self.assertAlmostEqual(1.580347926, units.data_transfer_rate.kibibits_per_second.to_giga_bytes_per_second(12345678.0), places=1)
		self.assertAlmostEqual(1024000.00, units.data_transfer_rate.kibibits_per_second.to_giga_bytes_per_second(8e12), places=1)
		self.assertAlmostEqual(0.01536, units.data_transfer_rate.kibibits_per_second.to_giga_bytes_per_second(1.2e5), places=1)

	def test_convert_known_kibibits_per_second_to_tera_bytes_per_second(self):
		self.assertAlmostEqual(0.01536, units.data_transfer_rate.kibibits_per_second.to_tera_bytes_per_second(120000000.0), places=1)
		self.assertAlmostEqual(11264.0, units.data_transfer_rate.kibibits_per_second.to_tera_bytes_per_second(88e12), places=1)
		self.assertAlmostEqual(0.001152, units.data_transfer_rate.kibibits_per_second.to_tera_bytes_per_second(9000000.0), places=1)

	def test_convert_known_kibibits_per_second_to_mebibits_per_second(self):
		self.assertAlmostEqual(0.5859375, units.data_transfer_rate.kibibits_per_second.to_mebibits_per_second(600.0), places=1)
		self.assertAlmostEqual(12.055664, units.data_transfer_rate.kibibits_per_second.to_mebibits_per_second(12345.0), places=1)
		self.assertAlmostEqual(0.0986328, units.data_transfer_rate.kibibits_per_second.to_mebibits_per_second(101.0), places=1)

if __name__ == '__main__':
    unittest.main()
