# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.pressure.torrs

class TestTorrsMethods(unittest.TestCase):

	def test_convert_known_torrs_to_bars(self):
		self.assertAlmostEqual(0.133322, units.pressure.torrs.to_bars(100.0), places=1)
		self.assertAlmostEqual(11.9991465, units.pressure.torrs.to_bars(9000.1), places=1)
		self.assertAlmostEqual(1.645198, units.pressure.torrs.to_bars(1234.0), places=1)

	def test_convert_known_torrs_to_pascals(self):
		self.assertAlmostEqual(25331.2499, units.pressure.torrs.to_pascals(190.0), places=1)
		self.assertAlmostEqual(866.595, units.pressure.torrs.to_pascals(6.5), places=1)
		self.assertAlmostEqual(453.296, units.pressure.torrs.to_pascals(3.4), places=1)

	def test_convert_known_torrs_to_atmospheres(self):
		self.assertAlmostEqual(7.471053, units.pressure.torrs.to_atmospheres(5678.0), places=1)
		self.assertAlmostEqual(0.131579, units.pressure.torrs.to_atmospheres(100.0), places=1)
		self.assertAlmostEqual(5.932895, units.pressure.torrs.to_atmospheres(4509.0), places=1)

	def test_convert_known_torrs_to_psi(self):
		self.assertAlmostEqual(87.01549, units.pressure.torrs.to_psi(4500.0), places=1)
		self.assertAlmostEqual(23.86158, units.pressure.torrs.to_psi(1234.0), places=1)
		self.assertAlmostEqual(17.4031, units.pressure.torrs.to_psi(900.0), places=1)

if __name__ == '__main__':
    unittest.main()
