# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.energy.joules

class TestJoulesMethods(unittest.TestCase):

	def test_convert_known_joules_to_kilojoules(self):
		self.assertAlmostEqual(0.79, units.energy.joules.to_kilojoules(790.0), places=1)
		self.assertAlmostEqual(800.1, units.energy.joules.to_kilojoules(800100.0), places=1)
		self.assertAlmostEqual(0.5092, units.energy.joules.to_kilojoules(509.2), places=1)

	def test_convert_known_joules_to_kilocalories(self):
		self.assertAlmostEqual(0.188815, units.energy.joules.to_kilocalories(790.0), places=1)
		self.assertAlmostEqual(0.030090822, units.energy.joules.to_kilocalories(125.9), places=1)
		self.assertAlmostEqual(1.912046, units.energy.joules.to_kilocalories(8000.0), places=1)

	def test_convert_known_joules_to_btu(self):
		self.assertAlmostEqual(0.473909, units.energy.joules.to_btu(500.0), places=1)
		self.assertAlmostEqual(1.810331, units.energy.joules.to_btu(1910.0), places=1)
		self.assertAlmostEqual(63.50384184, units.energy.joules.to_btu(67000.1), places=1)

	def test_convert_known_joules_to_calories(self):
		self.assertAlmostEqual(16.0134, units.energy.joules.to_calories(67.0), places=1)
		self.assertAlmostEqual(217.256, units.energy.joules.to_calories(909.0), places=1)
		self.assertAlmostEqual(45.4111, units.energy.joules.to_calories(190.0), places=1)

	def test_convert_known_joules_to_u_s_therms(self):
		self.assertAlmostEqual(0.948896667059, units.energy.joules.to_u_s_therms(100090000.0), places=1)
		self.assertAlmostEqual(0.52806018938, units.energy.joules.to_u_s_therms(55.7e6), places=1)
		self.assertAlmostEqual(11.70423974501, units.energy.joules.to_u_s_therms(1234567890.0), places=1)

	def test_convert_known_joules_to_watt_hours(self):
		self.assertAlmostEqual(15.555556, units.energy.joules.to_watt_hours(56000.0), places=1)
		self.assertAlmostEqual(0.247222, units.energy.joules.to_watt_hours(890.0), places=1)
		self.assertAlmostEqual(6.1113889, units.energy.joules.to_watt_hours(22001.0), places=1)

	def test_convert_known_joules_to_kilowatt_hours(self):
		self.assertAlmostEqual(0.1555557, units.energy.joules.to_kilowatt_hours(560000.8), places=1)
		self.assertAlmostEqual(0.3429352778, units.energy.joules.to_kilowatt_hours(1234567.0), places=1)
		self.assertAlmostEqual(0.250027778, units.energy.joules.to_kilowatt_hours(900100.0), places=1)

	def test_convert_known_joules_to_foot_pounds(self):
		self.assertAlmostEqual(663.806, units.energy.joules.to_foot_pounds(900.0), places=1)
		self.assertAlmostEqual(7.523134, units.energy.joules.to_foot_pounds(10.2), places=1)
		self.assertAlmostEqual(4.94167, units.energy.joules.to_foot_pounds(6.7), places=1)

	def test_convert_known_joules_to_electronvolts(self):
		self.assertAlmostEqual(55424602968504.0, units.energy.joules.to_electronvolts(0.00000888), places=1)
		self.assertAlmostEqual(77020225296322.0, units.energy.joules.to_electronvolts(0.00001234), places=1)
		self.assertAlmostEqual(41568452226378.0, units.energy.joules.to_electronvolts(0.00000666), places=1)

if __name__ == '__main__':
    unittest.main()
