# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.length.inches

class TestInchesMethods(unittest.TestCase):

	def test_convert_known_inches_to_millimetres(self):
		self.assertAlmostEqual(25.4, units.length.inches.to_millimetres(1.0), places=1)
		self.assertAlmostEqual(15.24, units.length.inches.to_millimetres(0.6), places=1)
		self.assertAlmostEqual(11582.4, units.length.inches.to_millimetres(456.0), places=1)

	def test_convert_known_inches_to_centimetres(self):
		self.assertAlmostEqual(312.42, units.length.inches.to_centimetres(123.0), places=1)
		self.assertAlmostEqual(2.286, units.length.inches.to_centimetres(0.9), places=1)
		self.assertAlmostEqual(8.636, units.length.inches.to_centimetres(3.4), places=1)

	def test_convert_known_inches_to_metres(self):
		self.assertAlmostEqual(0.08636, units.length.inches.to_metres(3.4), places=1)
		self.assertAlmostEqual(25.4508, units.length.inches.to_metres(1002.0), places=1)
		self.assertAlmostEqual(1.4224, units.length.inches.to_metres(56.0), places=1)

	def test_convert_known_inches_to_kilometres(self):
		self.assertAlmostEqual(0.454406, units.length.inches.to_kilometres(17890.0), places=1)
		self.assertAlmostEqual(25.3746, units.length.inches.to_kilometres(999000.0), places=1)
		self.assertAlmostEqual(2.54508, units.length.inches.to_kilometres(100200.0), places=1)

	def test_convert_known_inches_to_feet(self):
		self.assertAlmostEqual(1.91667, units.length.inches.to_feet(23.0), places=1)
		self.assertAlmostEqual(0.075, units.length.inches.to_feet(0.9), places=1)
		self.assertAlmostEqual(39.9167, units.length.inches.to_feet(479.0), places=1)

	def test_convert_known_inches_to_yards(self):
		self.assertAlmostEqual(3.41667, units.length.inches.to_yards(123.0), places=1)
		self.assertAlmostEqual(0.186111, units.length.inches.to_yards(6.7), places=1)
		self.assertAlmostEqual(0.25, units.length.inches.to_yards(9.0), places=1)

	def test_convert_known_inches_to_miles(self):
		self.assertAlmostEqual(0.1420455, units.length.inches.to_miles(9000.0), places=1)
		self.assertAlmostEqual(1.94848485, units.length.inches.to_miles(123456.0), places=1)
		self.assertAlmostEqual(0.1388889, units.length.inches.to_miles(8800.0), places=1)

	def test_convert_known_inches_to_nautical_miles(self):
		self.assertAlmostEqual(0.1234341, units.length.inches.to_nautical_miles(9000.0), places=1)
		self.assertAlmostEqual(1.69318704, units.length.inches.to_nautical_miles(123456.0), places=1)
		self.assertAlmostEqual(1.37423326, units.length.inches.to_nautical_miles(100200.0), places=1)

if __name__ == '__main__':
    unittest.main()
