# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.volume.cubic_metres

class TestCubicMetresMethods(unittest.TestCase):

	def test_convert_known_cubic_metres_to_millilitres(self):
		self.assertAlmostEqual(10000.0, units.volume.cubic_metres.to_millilitres(0.01), places=1)
		self.assertAlmostEqual(230673.5, units.volume.cubic_metres.to_millilitres(0.2306735), places=1)
		self.assertAlmostEqual(9000.0, units.volume.cubic_metres.to_millilitres(0.009), places=1)

	def test_convert_known_cubic_metres_to_litres(self):
		self.assertAlmostEqual(100.0, units.volume.cubic_metres.to_litres(0.1), places=1)
		self.assertAlmostEqual(9.0, units.volume.cubic_metres.to_litres(0.009), places=1)
		self.assertAlmostEqual(89.89, units.volume.cubic_metres.to_litres(0.08989), places=1)

	def test_convert_known_cubic_metres_to_kilolitres(self):
		self.assertAlmostEqual(0.9, units.volume.cubic_metres.to_kilolitres(0.9), places=1)
		self.assertAlmostEqual(100.9, units.volume.cubic_metres.to_kilolitres(100.9), places=1)
		self.assertAlmostEqual(666.9, units.volume.cubic_metres.to_kilolitres(666.9), places=1)

	def test_convert_known_cubic_metres_to_teaspoons(self):
		self.assertAlmostEqual(16893.6, units.volume.cubic_metres.to_teaspoons(0.1), places=1)
		self.assertAlmostEqual(506808.0, units.volume.cubic_metres.to_teaspoons(3.0), places=1)
		self.assertAlmostEqual(153731.76, units.volume.cubic_metres.to_teaspoons(0.91), places=1)

	def test_convert_known_cubic_metres_to_tablespoons(self):
		self.assertAlmostEqual(50680.8899, units.volume.cubic_metres.to_tablespoons(0.9), places=1)
		self.assertAlmostEqual(5631.21, units.volume.cubic_metres.to_tablespoons(0.1), places=1)
		self.assertAlmostEqual(506808.89, units.volume.cubic_metres.to_tablespoons(9.0), places=1)

	def test_convert_known_cubic_metres_to_quarts(self):
		self.assertAlmostEqual(703.902, units.volume.cubic_metres.to_quarts(0.8), places=1)
		self.assertAlmostEqual(351.951, units.volume.cubic_metres.to_quarts(0.4), places=1)
		self.assertAlmostEqual(5279.26, units.volume.cubic_metres.to_quarts(6.0), places=1)

	def test_convert_known_cubic_metres_to_pints(self):
		self.assertAlmostEqual(1231.83, units.volume.cubic_metres.to_pints(0.7), places=1)
		self.assertAlmostEqual(7918.875, units.volume.cubic_metres.to_pints(4.5), places=1)
		self.assertAlmostEqual(105.5852, units.volume.cubic_metres.to_pints(0.06), places=1)

	def test_convert_known_cubic_metres_to_gallons(self):
		self.assertAlmostEqual(43.9938, units.volume.cubic_metres.to_gallons(0.2), places=1)
		self.assertAlmostEqual(87.9877, units.volume.cubic_metres.to_gallons(0.4), places=1)
		self.assertAlmostEqual(6.0, units.volume.cubic_metres.to_gallons(0.0272765), places=1)

	def test_convert_known_cubic_metres_to_fluid_ounces(self):
		self.assertAlmostEqual(24636.569, units.volume.cubic_metres.to_fluid_ounces(0.7), places=1)
		self.assertAlmostEqual(3167.557, units.volume.cubic_metres.to_fluid_ounces(0.09), places=1)
		self.assertAlmostEqual(140780.399, units.volume.cubic_metres.to_fluid_ounces(4.0), places=1)

	def test_convert_known_cubic_metres_to_u_s_teaspoons(self):
		self.assertAlmostEqual(101442.0, units.volume.cubic_metres.to_u_s_teaspoons(0.5), places=1)
		self.assertAlmostEqual(405768.0, units.volume.cubic_metres.to_u_s_teaspoons(2), places=1)
		self.assertAlmostEqual(60865.199, units.volume.cubic_metres.to_u_s_teaspoons(0.3), places=1)

	def test_convert_known_cubic_metres_to_u_s_tablespoons(self):
		self.assertAlmostEqual(13525.6, units.volume.cubic_metres.to_u_s_tablespoons(0.2), places=1)
		self.assertAlmostEqual(60865.2, units.volume.cubic_metres.to_u_s_tablespoons(0.9), places=1)
		self.assertAlmostEqual(135256.0, units.volume.cubic_metres.to_u_s_tablespoons(2.0), places=1)

	def test_convert_known_cubic_metres_to_u_s_quarts(self):
		self.assertAlmostEqual(211.338, units.volume.cubic_metres.to_u_s_quarts(0.2), places=1)
		self.assertAlmostEqual(4226.76, units.volume.cubic_metres.to_u_s_quarts(4.0), places=1)
		self.assertAlmostEqual(900.0, units.volume.cubic_metres.to_u_s_quarts(0.851718), places=1)

	def test_convert_known_cubic_metres_to_u_s_pints(self):
		self.assertAlmostEqual(845.351, units.volume.cubic_metres.to_u_s_pints(0.4), places=1)
		self.assertAlmostEqual(14793.66, units.volume.cubic_metres.to_u_s_pints(7.0), places=1)
		self.assertAlmostEqual(12680.280, units.volume.cubic_metres.to_u_s_pints(6.0), places=1)

	def test_convert_known_cubic_metres_to_u_s_gallons(self):
		self.assertAlmostEqual(184.92, units.volume.cubic_metres.to_u_s_gallons(0.7), places=1)
		self.assertAlmostEqual(225.0, units.volume.cubic_metres.to_u_s_gallons(0.851718), places=1)
		self.assertAlmostEqual(5.283441, units.volume.cubic_metres.to_u_s_gallons(0.02), places=1)

	def test_convert_known_cubic_metres_to_u_s_fluid_ounces(self):
		self.assertAlmostEqual(30432.6, units.volume.cubic_metres.to_u_s_fluid_ounces(0.9), places=1)
		self.assertAlmostEqual(10144.2, units.volume.cubic_metres.to_u_s_fluid_ounces(0.3), places=1)
		self.assertAlmostEqual(111586.2, units.volume.cubic_metres.to_u_s_fluid_ounces(3.3), places=1)

	def test_convert_known_cubic_metres_to_u_s_cups(self):
		self.assertAlmostEqual(29166.7, units.volume.cubic_metres.to_u_s_cups(7.0), places=1)
		self.assertAlmostEqual(45833.37, units.volume.cubic_metres.to_u_s_cups(11.0), places=1)
		self.assertAlmostEqual(275000.22, units.volume.cubic_metres.to_u_s_cups(66.0), places=1)

	def test_convert_known_cubic_metres_to_cubic_feet(self):
		self.assertAlmostEqual(28.2517, units.volume.cubic_metres.to_cubic_feet(0.8), places=1)
		self.assertAlmostEqual(176.573, units.volume.cubic_metres.to_cubic_feet(5.0), places=1)
		self.assertAlmostEqual(428.014163, units.volume.cubic_metres.to_cubic_feet(12.12), places=1)

	def test_convert_known_cubic_metres_to_cubic_inches(self):
		self.assertAlmostEqual(24409.48, units.volume.cubic_metres.to_cubic_inches(0.4), places=1)
		self.assertAlmostEqual(183071.099, units.volume.cubic_metres.to_cubic_inches(3.0), places=1)
		self.assertAlmostEqual(60413.4629, units.volume.cubic_metres.to_cubic_inches(0.99), places=1)

	def test_convert_known_cubic_metres_to_oil_barrels(self):
		self.assertAlmostEqual(0.566083, units.volume.cubic_metres.to_oil_barrels(0.09), places=1)
		self.assertAlmostEqual(31.4491, units.volume.cubic_metres.to_oil_barrels(5.0), places=1)
		self.assertAlmostEqual(7.547772, units.volume.cubic_metres.to_oil_barrels(1.2), places=1)

if __name__ == '__main__':
    unittest.main()
