# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.data_storage.bits

class TestBitsMethods(unittest.TestCase):

	def test_convert_known_bits_to_kilobits(self):
		self.assertAlmostEqual(0.1, units.data_storage.bits.to_kilobits(100.0), places=1)
		self.assertAlmostEqual(6.021, units.data_storage.bits.to_kilobits(6021.0), places=1)
		self.assertAlmostEqual(9.1, units.data_storage.bits.to_kilobits(9100.0), places=1)

	def test_convert_known_bits_to_megabits(self):
		self.assertAlmostEqual(9.0, units.data_storage.bits.to_megabits(9000000.0), places=1)
		self.assertAlmostEqual(0.123456, units.data_storage.bits.to_megabits(123456.0), places=1)
		self.assertAlmostEqual(1.9, units.data_storage.bits.to_megabits(1900000.0), places=1)

	def test_convert_known_bits_to_gigabits(self):
		self.assertAlmostEqual(0.19, units.data_storage.bits.to_gigabits(190000000.0), places=1)
		self.assertAlmostEqual(8.009e-6, units.data_storage.bits.to_gigabits(8009.0), places=1)
		self.assertAlmostEqual(0.987654321, units.data_storage.bits.to_gigabits(987654321.0), places=1)

	def test_convert_known_bits_to_terabits(self):
		self.assertAlmostEqual(0.987654321234, units.data_storage.bits.to_terabits(987654321234.0), places=1)
		self.assertAlmostEqual(1234.567890123455982, units.data_storage.bits.to_terabits(1234567890123456.0), places=1)
		self.assertAlmostEqual(999.888777666555029, units.data_storage.bits.to_terabits(999888777666555.0), places=1)

	def test_convert_known_bits_to_kilobytes(self):
		self.assertAlmostEqual(0.1125, units.data_storage.bits.to_kilobytes(900.0), places=1)
		self.assertAlmostEqual(1.543125, units.data_storage.bits.to_kilobytes(12345.0), places=1)
		self.assertAlmostEqual(0.7501125, units.data_storage.bits.to_kilobytes(6000.9), places=1)

	def test_convert_known_bits_to_megabytes(self):
		self.assertAlmostEqual(0.015432, units.data_storage.bits.to_megabytes(123456.0), places=1)
		self.assertAlmostEqual(0.1126, units.data_storage.bits.to_megabytes(900800.0), places=1)
		self.assertAlmostEqual(124.986097125, units.data_storage.bits.to_megabytes(999888777.0), places=1)

	def test_convert_known_bits_to_gigabytes(self):
		self.assertAlmostEqual(0.124986097125, units.data_storage.bits.to_gigabytes(999888777.0), places=1)
		self.assertAlmostEqual(0.2375, units.data_storage.bits.to_gigabytes(1.9e+9), places=1)
		self.assertAlmostEqual(0.010011259625, units.data_storage.bits.to_gigabytes(80090077.0), places=1)

	def test_convert_known_bits_to_terabytes(self):
		self.assertAlmostEqual(0.12498609720825, units.data_storage.bits.to_terabytes(999888777666.0), places=1)
		self.assertAlmostEqual(1.5432098640431251, units.data_storage.bits.to_terabytes(12345678912345.0), places=1)
		self.assertAlmostEqual(13.9999028610416243, units.data_storage.bits.to_terabytes(111999222888333.0), places=1)

	def test_convert_known_bits_to_kibibits(self):
		self.assertAlmostEqual(1.757813, units.data_storage.bits.to_kibibits(1800.0), places=1)
		self.assertAlmostEqual(0.867188, units.data_storage.bits.to_kibibits(888.0), places=1)
		self.assertAlmostEqual(7.506836, units.data_storage.bits.to_kibibits(7687.0), places=1)

	def test_convert_known_bits_to_mebibits(self):
		self.assertAlmostEqual(0.953567505, units.data_storage.bits.to_mebibits(999888.0), places=1)
		self.assertAlmostEqual(1.17737484, units.data_storage.bits.to_mebibits(1234567.0), places=1)
		self.assertAlmostEqual(0.859069824, units.data_storage.bits.to_mebibits(900800.0), places=1)

if __name__ == '__main__':
    unittest.main()
