# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.luminous_energy.lumen_hour

class TestLumenHourMethods(unittest.TestCase):

	def test_convert_known_lumen_hour_to_talbot(self):
		self.assertAlmostEqual(32400.0, units.luminous_energy.lumen_hour.to_talbot(9.0), places=1)
		self.assertAlmostEqual(4320.0, units.luminous_energy.lumen_hour.to_talbot(1.2), places=1)
		self.assertAlmostEqual(14400.0, units.luminous_energy.lumen_hour.to_talbot(4.0), places=1)

	def test_convert_known_lumen_hour_to_lumen_minute(self):
		self.assertAlmostEqual(72.0, units.luminous_energy.lumen_hour.to_lumen_minute(1.2), places=1)
		self.assertAlmostEqual(48.0, units.luminous_energy.lumen_hour.to_lumen_minute(0.8), places=1)
		self.assertAlmostEqual(6540.0, units.luminous_energy.lumen_hour.to_lumen_minute(109.00), places=1)

	def test_convert_known_lumen_hour_to_lumen_second(self):
		self.assertAlmostEqual(392400.0, units.luminous_energy.lumen_hour.to_lumen_second(109.0), places=1)
		self.assertAlmostEqual(21960.0, units.luminous_energy.lumen_hour.to_lumen_second(6.1), places=1)
		self.assertAlmostEqual(2520.0, units.luminous_energy.lumen_hour.to_lumen_second(0.7), places=1)

if __name__ == '__main__':
    unittest.main()
