# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.mass.stones

class TestStonesMethods(unittest.TestCase):

	def test_convert_known_stones_to_milligrams(self):
		self.assertAlmostEqual(57152.63861, units.mass.stones.to_milligrams(0.009), places=1)
		self.assertAlmostEqual(12700.586, units.mass.stones.to_milligrams(0.002), places=1)
		self.assertAlmostEqual(3810.17591, units.mass.stones.to_milligrams(0.0006), places=1)

	def test_convert_known_stones_to_grams(self):
		self.assertAlmostEqual(7620.35, units.mass.stones.to_grams(1.2), places=1)
		self.assertAlmostEqual(50802.34543, units.mass.stones.to_grams(8.0), places=1)
		self.assertAlmostEqual(571526.38619, units.mass.stones.to_grams(90.0), places=1)

	def test_convert_known_stones_to_kilograms(self):
		self.assertAlmostEqual(571.526, units.mass.stones.to_kilograms(90.0), places=1)
		self.assertAlmostEqual(21.591, units.mass.stones.to_kilograms(3.4), places=1)
		self.assertAlmostEqual(419.119, units.mass.stones.to_kilograms(66.0), places=1)

	def test_convert_known_stones_to_tonnes(self):
		self.assertAlmostEqual(0.635029, units.mass.stones.to_tonnes(100.0), places=1)
		self.assertAlmostEqual(78.394369, units.mass.stones.to_tonnes(12345.0), places=1)
		self.assertAlmostEqual(64.131611, units.mass.stones.to_tonnes(10099.0), places=1)

	def test_convert_known_stones_to_ounces(self):
		self.assertAlmostEqual(7616.0, units.mass.stones.to_ounces(34.0), places=1)
		self.assertAlmostEqual(268.8, units.mass.stones.to_ounces(1.2), places=1)
		self.assertAlmostEqual(179200.0, units.mass.stones.to_ounces(800.0), places=1)

	def test_convert_known_stones_to_pounds(self):
		self.assertAlmostEqual(11200.0, units.mass.stones.to_pounds(800.0), places=1)
		self.assertAlmostEqual(7.0, units.mass.stones.to_pounds(0.5), places=1)
		self.assertAlmostEqual(729.4, units.mass.stones.to_pounds(52.1), places=1)

	def test_convert_known_stones_to_carats(self):
		self.assertAlmostEqual(317.5147, units.mass.stones.to_carats(0.01), places=1)
		self.assertAlmostEqual(190.5088, units.mass.stones.to_carats(0.006), places=1)
		self.assertAlmostEqual(66677.25, units.mass.stones.to_carats(2.1), places=1)

if __name__ == '__main__':
    unittest.main()
