# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.energy.btu

class TestBtuMethods(unittest.TestCase):

	def test_convert_known_btu_to_kilojoules(self):
		self.assertAlmostEqual(105.506, units.energy.btu.to_kilojoules(100.0), places=1)
		self.assertAlmostEqual(1042.03, units.energy.btu.to_kilojoules(987.65), places=1)
		self.assertAlmostEqual(586258.6917293, units.energy.btu.to_kilojoules(555666.0), places=1)

	def test_convert_known_btu_to_kilocalories(self):
		self.assertAlmostEqual(17.12196, units.energy.btu.to_kilocalories(67.9), places=1)
		self.assertAlmostEqual(27.7009516484, units.energy.btu.to_kilocalories(109.9), places=1)
		self.assertAlmostEqual(1260.279874814, units.energy.btu.to_kilocalories(5000.0), places=1)

	def test_convert_known_btu_to_joules(self):
		self.assertAlmostEqual(5275.3, units.energy.btu.to_joules(5.0), places=1)
		self.assertAlmostEqual(963164.274, units.energy.btu.to_joules(912.9), places=1)
		self.assertAlmostEqual(115001.54, units.energy.btu.to_joules(109.0), places=1)

	def test_convert_known_btu_to_calories(self):
		self.assertAlmostEqual(14121.184, units.energy.btu.to_calories(56.0), places=1)
		self.assertAlmostEqual(31016.172, units.energy.btu.to_calories(123.0), places=1)
		self.assertAlmostEqual(226.9476, units.energy.btu.to_calories(0.9), places=1)

	def test_convert_known_btu_to_u_s_therms(self):
		self.assertAlmostEqual(0.120028657, units.energy.btu.to_u_s_therms(12000.0), places=1)
		self.assertAlmostEqual(0.098788586, units.energy.btu.to_u_s_therms(9876.5), places=1)
		self.assertAlmostEqual(0.006671583, units.energy.btu.to_u_s_therms(666.999), places=1)

	def test_convert_known_btu_to_watt_hours(self):
		self.assertAlmostEqual(263.764, units.energy.btu.to_watt_hours(900.0), places=1)
		self.assertAlmostEqual(36.839034, units.energy.btu.to_watt_hours(125.7), places=1)
		self.assertAlmostEqual(0.2901404, units.energy.btu.to_watt_hours(0.99), places=1)

	def test_convert_known_btu_to_kilowatt_hours(self):
		self.assertAlmostEqual(2.63764, units.energy.btu.to_kilowatt_hours(9000.0), places=1)
		self.assertAlmostEqual(3.6179624, units.energy.btu.to_kilowatt_hours(12345.0), places=1)
		self.assertAlmostEqual(2.37117941, units.energy.btu.to_kilowatt_hours(8090.8), places=1)

	def test_convert_known_btu_to_foot_pounds(self):
		self.assertAlmostEqual(147073.9409, units.energy.btu.to_foot_pounds(189.0), places=1)
		self.assertAlmostEqual(233.451, units.energy.btu.to_foot_pounds(0.3), places=1)
		self.assertAlmostEqual(2023.24, units.energy.btu.to_foot_pounds(2.6), places=1)

	def test_convert_known_btu_to_electronvolts(self):
		self.assertAlmostEqual(519567655294184.88, units.energy.btu.to_electronvolts(0.0000000789), places=1)
		self.assertAlmostEqual(6598311667994592.0, units.energy.btu.to_electronvolts(0.000001002), places=1)
		self.assertAlmostEqual(6585141385224.14, units.energy.btu.to_electronvolts(0.000000001), places=1)

if __name__ == '__main__':
    unittest.main()
