# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.data_transfer_rate.mebibits_per_second

class TestMebibitsPerSecondMethods(unittest.TestCase):

	def test_convert_known_mebibits_per_second_to_bits_per_second(self):
		self.assertAlmostEqual(943718.4, units.data_transfer_rate.mebibits_per_second.to_bits_per_second(0.9), places=1)
		self.assertAlmostEqual(6291.456, units.data_transfer_rate.mebibits_per_second.to_bits_per_second(0.006), places=1)
		self.assertAlmostEqual(2097152.0, units.data_transfer_rate.mebibits_per_second.to_bits_per_second(2.0), places=1)

	def test_convert_known_mebibits_per_second_to_kilo_bits_per_second(self):
		self.assertAlmostEqual(838.861, units.data_transfer_rate.mebibits_per_second.to_kilo_bits_per_second(0.8), places=1)
		self.assertAlmostEqual(2097.15, units.data_transfer_rate.mebibits_per_second.to_kilo_bits_per_second(2.0), places=1)
		self.assertAlmostEqual(241.1725, units.data_transfer_rate.mebibits_per_second.to_kilo_bits_per_second(0.23), places=1)

	def test_convert_known_mebibits_per_second_to_mega_bits_per_second(self):
		self.assertAlmostEqual(0.943718, units.data_transfer_rate.mebibits_per_second.to_mega_bits_per_second(0.9), places=1)
		self.assertAlmostEqual(12.89748, units.data_transfer_rate.mebibits_per_second.to_mega_bits_per_second(12.3), places=1)
		self.assertAlmostEqual(8.49347, units.data_transfer_rate.mebibits_per_second.to_mega_bits_per_second(8.1), places=1)

	def test_convert_known_mebibits_per_second_to_giga_bits_per_second(self):
		self.assertAlmostEqual(12.944671, units.data_transfer_rate.mebibits_per_second.to_giga_bits_per_second(12345.0), places=1)
		self.assertAlmostEqual(0.104858, units.data_transfer_rate.mebibits_per_second.to_giga_bits_per_second(100.0), places=1)
		self.assertAlmostEqual(1.0484711, units.data_transfer_rate.mebibits_per_second.to_giga_bits_per_second(999.9), places=1)

	def test_convert_known_mebibits_per_second_to_tera_bits_per_second(self):
		self.assertAlmostEqual(0.104867037, units.data_transfer_rate.mebibits_per_second.to_tera_bits_per_second(100009.0), places=1)
		self.assertAlmostEqual(10.35630595, units.data_transfer_rate.mebibits_per_second.to_tera_bits_per_second(9876543.0), places=1)
		self.assertAlmostEqual(1.049519718, units.data_transfer_rate.mebibits_per_second.to_tera_bits_per_second(1000900.0), places=1)

	def test_convert_known_mebibits_per_second_to_kilo_bytes_per_second(self):
		self.assertAlmostEqual(524.288, units.data_transfer_rate.mebibits_per_second.to_kilo_bytes_per_second(4.0), places=1)
		self.assertAlmostEqual(190.0544, units.data_transfer_rate.mebibits_per_second.to_kilo_bytes_per_second(1.45), places=1)
		self.assertAlmostEqual(11548.754, units.data_transfer_rate.mebibits_per_second.to_kilo_bytes_per_second(88.11), places=1)

	def test_convert_known_mebibits_per_second_to_mega_bytes_per_second(self):
		self.assertAlmostEqual(14.2868, units.data_transfer_rate.mebibits_per_second.to_mega_bytes_per_second(109.0), places=1)
		self.assertAlmostEqual(7.2967782, units.data_transfer_rate.mebibits_per_second.to_mega_bytes_per_second(55.67), places=1)
		self.assertAlmostEqual(5987.1068, units.data_transfer_rate.mebibits_per_second.to_mega_bytes_per_second(45678.0), places=1)

	def test_convert_known_mebibits_per_second_to_giga_bytes_per_second(self):
		self.assertAlmostEqual(0.524288311, units.data_transfer_rate.mebibits_per_second.to_giga_bytes_per_second(4000.0), places=1)
		self.assertAlmostEqual(11.80959421, units.data_transfer_rate.mebibits_per_second.to_giga_bytes_per_second(90100.0), places=1)
		self.assertAlmostEqual(0.132251727, units.data_transfer_rate.mebibits_per_second.to_giga_bytes_per_second(1009.0), places=1)

	def test_convert_known_mebibits_per_second_to_tera_bytes_per_second(self):
		self.assertAlmostEqual(0.1310731796, units.data_transfer_rate.mebibits_per_second.to_tera_bytes_per_second(1000009.0), places=1)
		self.assertAlmostEqual(11.902396662, units.data_transfer_rate.mebibits_per_second.to_tera_bytes_per_second(90808080.0), places=1)
		self.assertAlmostEqual(681574.4, units.data_transfer_rate.mebibits_per_second.to_tera_bytes_per_second(5.2e12), places=1)

	def test_convert_known_mebibits_per_second_to_kibibits_per_second(self):
		self.assertAlmostEqual(5120.0, units.data_transfer_rate.mebibits_per_second.to_kibibits_per_second(5.0), places=1)
		self.assertAlmostEqual(1264189.44, units.data_transfer_rate.mebibits_per_second.to_kibibits_per_second(1234.56), places=1)
		self.assertAlmostEqual(517120.0, units.data_transfer_rate.mebibits_per_second.to_kibibits_per_second(505.0), places=1)

if __name__ == '__main__':
    unittest.main()
