# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.power.mechanical_horse_power

class TestMechanicalHorsePowerMethods(unittest.TestCase):

	def test_convert_known_mechanical_horse_power_to_metric_horse_power(self):
		self.assertAlmostEqual(65.9999749, units.power.mechanical_horse_power.to_metric_horse_power(65.0971), places=1)
		self.assertAlmostEqual(122.9996, units.power.mechanical_horse_power.to_metric_horse_power(121.317), places=1)
		self.assertAlmostEqual(88.0, units.power.mechanical_horse_power.to_metric_horse_power(86.7962), places=1)

if __name__ == '__main__':
    unittest.main()
