# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.data_transfer_rate.kilo_bits_per_second

class TestKiloBitsPerSecondMethods(unittest.TestCase):

	def test_convert_known_kilo_bits_per_second_to_bits_per_second(self):
		self.assertAlmostEqual(9000.0, units.data_transfer_rate.kilo_bits_per_second.to_bits_per_second(9.0), places=1)
		self.assertAlmostEqual(6700.0, units.data_transfer_rate.kilo_bits_per_second.to_bits_per_second(6.7), places=1)
		self.assertAlmostEqual(1234.5, units.data_transfer_rate.kilo_bits_per_second.to_bits_per_second(1.2345), places=1)

	def test_convert_known_kilo_bits_per_second_to_mega_bits_per_second(self):
		self.assertAlmostEqual(0.9, units.data_transfer_rate.kilo_bits_per_second.to_mega_bits_per_second(900.0), places=1)
		self.assertAlmostEqual(12.345, units.data_transfer_rate.kilo_bits_per_second.to_mega_bits_per_second(12345.0), places=1)
		self.assertAlmostEqual(9.988, units.data_transfer_rate.kilo_bits_per_second.to_mega_bits_per_second(9988.0), places=1)

	def test_convert_known_kilo_bits_per_second_to_giga_bits_per_second(self):
		self.assertAlmostEqual(0.123456, units.data_transfer_rate.kilo_bits_per_second.to_giga_bits_per_second(123456.0), places=1)
		self.assertAlmostEqual(8.0007, units.data_transfer_rate.kilo_bits_per_second.to_giga_bits_per_second(8000700.0), places=1)
		self.assertAlmostEqual(191.987578, units.data_transfer_rate.kilo_bits_per_second.to_giga_bits_per_second(191987578.0), places=1)

	def test_convert_known_kilo_bits_per_second_to_tera_bits_per_second(self):
		self.assertAlmostEqual(0.191987578, units.data_transfer_rate.kilo_bits_per_second.to_tera_bits_per_second(191987578.0), places=1)
		self.assertAlmostEqual(9.010081903, units.data_transfer_rate.kilo_bits_per_second.to_tera_bits_per_second(9010081903.0), places=1)
		self.assertAlmostEqual(0.123456789, units.data_transfer_rate.kilo_bits_per_second.to_tera_bits_per_second(123456789.0), places=1)

	def test_convert_known_kilo_bits_per_second_to_kilo_bytes_per_second(self):
		self.assertAlmostEqual(10.0, units.data_transfer_rate.kilo_bits_per_second.to_kilo_bytes_per_second(80.0), places=1)
		self.assertAlmostEqual(1.95875, units.data_transfer_rate.kilo_bits_per_second.to_kilo_bytes_per_second(15.67), places=1)
		self.assertAlmostEqual(1000.88625, units.data_transfer_rate.kilo_bits_per_second.to_kilo_bytes_per_second(8007.09), places=1)

	def test_convert_known_kilo_bits_per_second_to_mega_bytes_per_second(self):
		self.assertAlmostEqual(15.432, units.data_transfer_rate.kilo_bits_per_second.to_mega_bytes_per_second(123456.0), places=1)
		self.assertAlmostEqual(124.859625, units.data_transfer_rate.kilo_bits_per_second.to_mega_bytes_per_second(998877.0), places=1)
		self.assertAlmostEqual(1.26125, units.data_transfer_rate.kilo_bits_per_second.to_mega_bytes_per_second(10090.0), places=1)

	def test_convert_known_kilo_bits_per_second_to_giga_bytes_per_second(self):
		self.assertAlmostEqual(0.2286215, units.data_transfer_rate.kilo_bits_per_second.to_giga_bytes_per_second(1828972.0), places=1)
		self.assertAlmostEqual(0.1099826, units.data_transfer_rate.kilo_bits_per_second.to_giga_bytes_per_second(879860.8), places=1)
		self.assertAlmostEqual(9.772371375, units.data_transfer_rate.kilo_bits_per_second.to_giga_bytes_per_second(78178971.0), places=1)

	def test_convert_known_kilo_bits_per_second_to_tera_bytes_per_second(self):
		self.assertAlmostEqual(0.154320986375, units.data_transfer_rate.kilo_bits_per_second.to_tera_bytes_per_second(1234567891.0), places=1)
		self.assertAlmostEqual(0.12499988725, units.data_transfer_rate.kilo_bits_per_second.to_tera_bytes_per_second(999999098.0), places=1)
		self.assertAlmostEqual(10.57729551775, units.data_transfer_rate.kilo_bits_per_second.to_tera_bytes_per_second(84618364142.0), places=1)

	def test_convert_known_kilo_bits_per_second_to_kibibits_per_second(self):
		self.assertAlmostEqual(87.01172, units.data_transfer_rate.kilo_bits_per_second.to_kibibits_per_second(89.1), places=1)
		self.assertAlmostEqual(6.93359, units.data_transfer_rate.kilo_bits_per_second.to_kibibits_per_second(7.1), places=1)
		self.assertAlmostEqual(427.734, units.data_transfer_rate.kilo_bits_per_second.to_kibibits_per_second(438.0), places=1)

	def test_convert_known_kilo_bits_per_second_to_mebibits_per_second(self):
		self.assertAlmostEqual(74.186325, units.data_transfer_rate.kilo_bits_per_second.to_mebibits_per_second(77790.0), places=1)
		self.assertAlmostEqual(117.736816, units.data_transfer_rate.kilo_bits_per_second.to_mebibits_per_second(123456.0), places=1)
		self.assertAlmostEqual(22.861481, units.data_transfer_rate.kilo_bits_per_second.to_mebibits_per_second(23972.0), places=1)

if __name__ == '__main__':
    unittest.main()
