# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.volume.kilolitres

class TestKilolitresMethods(unittest.TestCase):

	def test_convert_known_kilolitres_to_millilitres(self):
		self.assertAlmostEqual(90000.0, units.volume.kilolitres.to_millilitres(0.09), places=1)
		self.assertAlmostEqual(1230.0, units.volume.kilolitres.to_millilitres(0.00123), places=1)
		self.assertAlmostEqual(1.2e+6, units.volume.kilolitres.to_millilitres(1.2), places=1)

	def test_convert_known_kilolitres_to_litres(self):
		self.assertAlmostEqual(1200.0, units.volume.kilolitres.to_litres(1.2), places=1)
		self.assertAlmostEqual(800.0, units.volume.kilolitres.to_litres(0.8), places=1)
		self.assertAlmostEqual(456000.0, units.volume.kilolitres.to_litres(456.0), places=1)

	def test_convert_known_kilolitres_to_teaspoons(self):
		self.assertAlmostEqual(118255.41900799, units.volume.kilolitres.to_teaspoons(0.7), places=1)
		self.assertAlmostEqual(1689.363, units.volume.kilolitres.to_teaspoons(0.01), places=1)
		self.assertAlmostEqual(760213.407908, units.volume.kilolitres.to_teaspoons(4.5), places=1)

	def test_convert_known_kilolitres_to_tablespoons(self):
		self.assertAlmostEqual(16893.631286856, units.volume.kilolitres.to_tablespoons(0.3), places=1)
		self.assertAlmostEqual(163305.10243961, units.volume.kilolitres.to_tablespoons(2.9), places=1)
		self.assertAlmostEqual(3772.911, units.volume.kilolitres.to_tablespoons(0.067), places=1)

	def test_convert_known_kilolitres_to_quarts(self):
		self.assertAlmostEqual(79.18893, units.volume.kilolitres.to_quarts(0.09), places=1)
		self.assertAlmostEqual(2023.72, units.volume.kilolitres.to_quarts(2.3), places=1)
		self.assertAlmostEqual(589.5176, units.volume.kilolitres.to_quarts(0.67), places=1)

	def test_convert_known_kilolitres_to_pints(self):
		self.assertAlmostEqual(703.902, units.volume.kilolitres.to_pints(0.4), places=1)
		self.assertAlmostEqual(117903.46835618, units.volume.kilolitres.to_pints(67.0), places=1)
		self.assertAlmostEqual(16365.7, units.volume.kilolitres.to_pints(9.3), places=1)

	def test_convert_known_kilolitres_to_gallons(self):
		self.assertAlmostEqual(23976.638149, units.volume.kilolitres.to_gallons(109.0), places=1)
		self.assertAlmostEqual(1583.78, units.volume.kilolitres.to_gallons(7.2), places=1)
		self.assertAlmostEqual(87.9877, units.volume.kilolitres.to_gallons(0.4), places=1)

	def test_convert_known_kilolitres_to_fluid_ounces(self):
		self.assertAlmostEqual(7039.02, units.volume.kilolitres.to_fluid_ounces(0.2), places=1)
		self.assertAlmostEqual(168936.31286856, units.volume.kilolitres.to_fluid_ounces(4.8), places=1)
		self.assertAlmostEqual(211170.391085, units.volume.kilolitres.to_fluid_ounces(6.0), places=1)

	def test_convert_known_kilolitres_to_u_s_teaspoons(self):
		self.assertAlmostEqual(811536.5448442, units.volume.kilolitres.to_u_s_teaspoons(4.0), places=1)
		self.assertAlmostEqual(40576.82724221160, units.volume.kilolitres.to_u_s_teaspoons(0.2), places=1)
		self.assertAlmostEqual(486921.92690653, units.volume.kilolitres.to_u_s_teaspoons(2.4), places=1)

	def test_convert_known_kilolitres_to_u_s_tablespoons(self):
		self.assertAlmostEqual(87916.45902479, units.volume.kilolitres.to_u_s_tablespoons(1.3), places=1)
		self.assertAlmostEqual(40576.82724221, units.volume.kilolitres.to_u_s_tablespoons(0.6), places=1)
		self.assertAlmostEqual(2028.841, units.volume.kilolitres.to_u_s_tablespoons(0.03), places=1)

	def test_convert_known_kilolitres_to_u_s_quarts(self):
		self.assertAlmostEqual(95.10194, units.volume.kilolitres.to_u_s_quarts(0.09), places=1)
		self.assertAlmostEqual(2641.72, units.volume.kilolitres.to_u_s_quarts(2.5), places=1)
		self.assertAlmostEqual(189041.52, units.volume.kilolitres.to_u_s_quarts(178.9), places=1)

	def test_convert_known_kilolitres_to_u_s_pints(self):
		self.assertAlmostEqual(141596.2200639, units.volume.kilolitres.to_u_s_pints(67.0), places=1)
		self.assertAlmostEqual(9932.87, units.volume.kilolitres.to_u_s_pints(4.7), places=1)
		self.assertAlmostEqual(230146.69, units.volume.kilolitres.to_u_s_pints(108.9), places=1)

	def test_convert_known_kilolitres_to_u_s_gallons(self):
		self.assertAlmostEqual(422.675, units.volume.kilolitres.to_u_s_gallons(1.6), places=1)
		self.assertAlmostEqual(15057.8, units.volume.kilolitres.to_u_s_gallons(57.0), places=1)
		self.assertAlmostEqual(232.4714, units.volume.kilolitres.to_u_s_gallons(0.88), places=1)

	def test_convert_known_kilolitres_to_u_s_fluid_ounces(self):
		self.assertAlmostEqual(2366.982, units.volume.kilolitres.to_u_s_fluid_ounces(0.07), places=1)
		self.assertAlmostEqual(142018.89516765, units.volume.kilolitres.to_u_s_fluid_ounces(4.2), places=1)
		self.assertAlmostEqual(405768.27190759, units.volume.kilolitres.to_u_s_fluid_ounces(12.0), places=1)

	def test_convert_known_kilolitres_to_u_s_cups(self):
		self.assertAlmostEqual(50721.03405276, units.volume.kilolitres.to_u_s_cups(12.0), places=1)
		self.assertAlmostEqual(3381.4, units.volume.kilolitres.to_u_s_cups(0.8), places=1)
		self.assertAlmostEqual(26205.86759392, units.volume.kilolitres.to_u_s_cups(6.2), places=1)

	def test_convert_known_kilolitres_to_cubic_metres(self):
		self.assertAlmostEqual(1000.0, units.volume.kilolitres.to_cubic_metres(1000.0), places=1)
		self.assertAlmostEqual(0.9, units.volume.kilolitres.to_cubic_metres(0.9), places=1)
		self.assertAlmostEqual(6.09, units.volume.kilolitres.to_cubic_metres(6.09), places=1)

	def test_convert_known_kilolitres_to_cubic_feet(self):
		self.assertAlmostEqual(2.0, units.volume.kilolitres.to_cubic_feet(0.0566337), places=1)
		self.assertAlmostEqual(278.986, units.volume.kilolitres.to_cubic_feet(7.9), places=1)
		self.assertAlmostEqual(3107.69, units.volume.kilolitres.to_cubic_feet(88.0), places=1)

	def test_convert_known_kilolitres_to_cubic_inches(self):
		self.assertAlmostEqual(366142.19999, units.volume.kilolitres.to_cubic_inches(6.0), places=1)
		self.assertAlmostEqual(6102.37, units.volume.kilolitres.to_cubic_inches(0.1), places=1)
		self.assertAlmostEqual(48818.959, units.volume.kilolitres.to_cubic_inches(0.8), places=1)

	def test_convert_known_kilolitres_to_oil_barrels(self):
		self.assertAlmostEqual(3.0, units.volume.kilolitres.to_oil_barrels(0.476962), places=1)
		self.assertAlmostEqual(25.1592, units.volume.kilolitres.to_oil_barrels(4.0), places=1)
		self.assertAlmostEqual(37.7389, units.volume.kilolitres.to_oil_barrels(6.0), places=1)

if __name__ == '__main__':
    unittest.main()
