# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.frequency.megahertz

class TestMegahertzMethods(unittest.TestCase):

	def test_convert_known_megahertz_to_hertz(self):
		self.assertAlmostEqual(900000.0, units.frequency.megahertz.to_hertz(0.9), places=1)
		self.assertAlmostEqual(1000.0, units.frequency.megahertz.to_hertz(0.001), places=1)
		self.assertAlmostEqual(91000.0, units.frequency.megahertz.to_hertz(0.091), places=1)

	def test_convert_known_megahertz_to_kilohertz(self):
		self.assertAlmostEqual(870.0, units.frequency.megahertz.to_kilohertz(0.87), places=1)
		self.assertAlmostEqual(12000.0, units.frequency.megahertz.to_kilohertz(12.0), places=1)
		self.assertAlmostEqual(88100.0, units.frequency.megahertz.to_kilohertz(88.1), places=1)

	def test_convert_known_megahertz_to_gigahertz(self):
		self.assertAlmostEqual(0.798, units.frequency.megahertz.to_gigahertz(798.0), places=1)
		self.assertAlmostEqual(0.9, units.frequency.megahertz.to_gigahertz(900.0), places=1)
		self.assertAlmostEqual(0.5791, units.frequency.megahertz.to_gigahertz(579.1), places=1)

if __name__ == '__main__':
    unittest.main()
