# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.energy.foot_pounds

class TestFootPoundsMethods(unittest.TestCase):

	def test_convert_known_foot_pounds_to_kilojoules(self):
		self.assertAlmostEqual(0.257605, units.energy.foot_pounds.to_kilojoules(190.0), places=1)
		self.assertAlmostEqual(0.00623676, units.energy.foot_pounds.to_kilojoules(4.6), places=1)
		self.assertAlmostEqual(0.16785026, units.energy.foot_pounds.to_kilojoules(123.8), places=1)

	def test_convert_known_foot_pounds_to_kilocalories(self):
		self.assertAlmostEqual(0.6477725, units.energy.foot_pounds.to_kilocalories(1999.0), places=1)
		self.assertAlmostEqual(0.2886622, units.energy.foot_pounds.to_kilocalories(890.8), places=1)
		self.assertAlmostEqual(3.8885792, units.energy.foot_pounds.to_kilocalories(12000.0), places=1)

	def test_convert_known_foot_pounds_to_joules(self):
		self.assertAlmostEqual(257.605, units.energy.foot_pounds.to_joules(190.0), places=1)
		self.assertAlmostEqual(31.72614, units.energy.foot_pounds.to_joules(23.4), places=1)
		self.assertAlmostEqual(12.4735, units.energy.foot_pounds.to_joules(9.2), places=1)

	def test_convert_known_foot_pounds_to_btu(self):
		self.assertAlmostEqual(11.56561, units.energy.foot_pounds.to_btu(9000.0), places=1)
		self.assertAlmostEqual(0.05859908, units.energy.foot_pounds.to_btu(45.6), places=1)
		self.assertAlmostEqual(2.564995, units.energy.foot_pounds.to_btu(1996.0), places=1)

	def test_convert_known_foot_pounds_to_calories(self):
		self.assertAlmostEqual(39.8579, units.energy.foot_pounds.to_calories(123.0), places=1)
		self.assertAlmostEqual(17.72544, units.energy.foot_pounds.to_calories(54.7), places=1)
		self.assertAlmostEqual(35.386071, units.energy.foot_pounds.to_calories(109.2), places=1)

	def test_convert_known_foot_pounds_to_u_s_therms(self):
		self.assertAlmostEqual(0.24422111613, units.energy.foot_pounds.to_u_s_therms(19000000.0), places=1)
		self.assertAlmostEqual(0.01586880688, units.energy.foot_pounds.to_u_s_therms(1234567.0), places=1)
		self.assertAlmostEqual(1.28794890016, units.energy.foot_pounds.to_u_s_therms(100200300.0), places=1)

	def test_convert_known_foot_pounds_to_watt_hours(self):
		self.assertAlmostEqual(0.0165711, units.energy.foot_pounds.to_watt_hours(44.0), places=1)
		self.assertAlmostEqual(3.419674, units.energy.foot_pounds.to_watt_hours(9080.0), places=1)
		self.assertAlmostEqual(0.4519393, units.energy.foot_pounds.to_watt_hours(1200.0), places=1)

	def test_convert_known_foot_pounds_to_kilowatt_hours(self):
		self.assertAlmostEqual(0.338954487, units.energy.foot_pounds.to_kilowatt_hours(900000.0), places=1)
		self.assertAlmostEqual(0.0377369329, units.energy.foot_pounds.to_kilowatt_hours(100200.0), places=1)
		self.assertAlmostEqual(3.719665074, units.energy.foot_pounds.to_kilowatt_hours(9876543.0), places=1)

	def test_convert_known_foot_pounds_to_electronvolts(self):
		self.assertAlmostEqual(10408691651641586.0, units.energy.foot_pounds.to_electronvolts(0.00123), places=1)
		self.assertAlmostEqual(7616115842664575.0, units.energy.foot_pounds.to_electronvolts(0.0009), places=1)
		self.assertAlmostEqual(75145676314290.469, units.energy.foot_pounds.to_electronvolts(0.00000888), places=1)

if __name__ == '__main__':
    unittest.main()
