# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.angle.gradians

class TestGradiansMethods(unittest.TestCase):

	def test_convert_known_gradians_to_degrees(self):
		self.assertAlmostEqual(5.04, units.angle.gradians.to_degrees(5.6), places=1)
		self.assertAlmostEqual(150.3, units.angle.gradians.to_degrees(167.0), places=1)
		self.assertAlmostEqual(0.09, units.angle.gradians.to_degrees(0.1), places=1)

	def test_convert_known_gradians_to_radians(self):
		self.assertAlmostEqual(1.066571, units.angle.gradians.to_radians(67.9), places=1)
		self.assertAlmostEqual(125.6637, units.angle.gradians.to_radians(8000.0), places=1)
		self.assertAlmostEqual(0.102102, units.angle.gradians.to_radians(6.5), places=1)

	def test_convert_known_gradians_to_milliradians(self):
		self.assertAlmostEqual(127.2348, units.angle.gradians.to_milliradians(8.1), places=1)
		self.assertAlmostEqual(14137.167, units.angle.gradians.to_milliradians(900.0), places=1)
		self.assertAlmostEqual(29884.4, units.angle.gradians.to_milliradians(1902.5), places=1)

	def test_convert_known_gradians_to_minute_of_arc(self):
		self.assertAlmostEqual(4368.6, units.angle.gradians.to_minute_of_arc(80.9), places=1)
		self.assertAlmostEqual(90612.0, units.angle.gradians.to_minute_of_arc(1678.0), places=1)
		self.assertAlmostEqual(48600.0, units.angle.gradians.to_minute_of_arc(900.0), places=1)

	def test_convert_known_gradians_to_seconds_of_arc(self):
		self.assertAlmostEqual(2916.0, units.angle.gradians.to_seconds_of_arc(0.9), places=1)
		self.assertAlmostEqual(39852.0, units.angle.gradians.to_seconds_of_arc(12.3), places=1)
		self.assertAlmostEqual(16524.0, units.angle.gradians.to_seconds_of_arc(5.1), places=1)

if __name__ == '__main__':
    unittest.main()
