# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.mass.ounces

class TestOuncesMethods(unittest.TestCase):

	def test_convert_known_ounces_to_milligrams(self):
		self.assertAlmostEqual(5669.9, units.mass.ounces.to_milligrams(0.2), places=1)
		self.assertAlmostEqual(340194.2772, units.mass.ounces.to_milligrams(12.0), places=1)
		self.assertAlmostEqual(51029.141579, units.mass.ounces.to_milligrams(1.8), places=1)

	def test_convert_known_ounces_to_grams(self):
		self.assertAlmostEqual(56.699, units.mass.ounces.to_grams(2.0), places=1)
		self.assertAlmostEqual(8.50486, units.mass.ounces.to_grams(0.3), places=1)
		self.assertAlmostEqual(198.447, units.mass.ounces.to_grams(7.0), places=1)

	def test_convert_known_ounces_to_kilograms(self):
		self.assertAlmostEqual(1.58757, units.mass.ounces.to_kilograms(56.0), places=1)
		self.assertAlmostEqual(3.48699, units.mass.ounces.to_kilograms(123.0), places=1)
		self.assertAlmostEqual(2.8604669, units.mass.ounces.to_kilograms(100.9), places=1)

	def test_convert_known_ounces_to_tonnes(self):
		self.assertAlmostEqual(0.2267962, units.mass.ounces.to_tonnes(8000.0), places=1)
		self.assertAlmostEqual(34.99938572, units.mass.ounces.to_tonnes(1234567.0), places=1)
		self.assertAlmostEqual(25.5372504, units.mass.ounces.to_tonnes(900800.0), places=1)

	def test_convert_known_ounces_to_pounds(self):
		self.assertAlmostEqual(5.625, units.mass.ounces.to_pounds(90.0), places=1)
		self.assertAlmostEqual(0.325, units.mass.ounces.to_pounds(5.2), places=1)
		self.assertAlmostEqual(0.75, units.mass.ounces.to_pounds(12.0), places=1)

	def test_convert_known_ounces_to_stones(self):
		self.assertAlmostEqual(0.745536, units.mass.ounces.to_stones(167.0), places=1)
		self.assertAlmostEqual(3.5745536, units.mass.ounces.to_stones(800.7), places=1)
		self.assertAlmostEqual(5.51116071, units.mass.ounces.to_stones(1234.5), places=1)

	def test_convert_known_ounces_to_carats(self):
		self.assertAlmostEqual(0.170097139, units.mass.ounces.to_carats(0.0012), places=1)
		self.assertAlmostEqual(566.99, units.mass.ounces.to_carats(4.0), places=1)
		self.assertAlmostEqual(198.447, units.mass.ounces.to_carats(1.4), places=1)

if __name__ == '__main__':
    unittest.main()
