# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.volume.u_s_quarts

class TestUSQuartsMethods(unittest.TestCase):

	def test_convert_known_u_s_quarts_to_millilitres(self):
		self.assertAlmostEqual(8517176.51400, units.volume.u_s_quarts.to_millilitres(9000.0), places=1)
		self.assertAlmostEqual(4731.76, units.volume.u_s_quarts.to_millilitres(5.0), places=1)
		self.assertAlmostEqual(662.447, units.volume.u_s_quarts.to_millilitres(0.7), places=1)

	def test_convert_known_u_s_quarts_to_litres(self):
		self.assertAlmostEqual(8.51718, units.volume.u_s_quarts.to_litres(9.0), places=1)
		self.assertAlmostEqual(969.0654, units.volume.u_s_quarts.to_litres(1024.0), places=1)
		self.assertAlmostEqual(0.757082, units.volume.u_s_quarts.to_litres(0.8), places=1)

	def test_convert_known_u_s_quarts_to_kilolitres(self):
		self.assertAlmostEqual(0.946353, units.volume.u_s_quarts.to_kilolitres(1000.0), places=1)
		self.assertAlmostEqual(6.42479, units.volume.u_s_quarts.to_kilolitres(6789.0), places=1)
		self.assertAlmostEqual(0.0425859, units.volume.u_s_quarts.to_kilolitres(45.0), places=1)

	def test_convert_known_u_s_quarts_to_teaspoons(self):
		self.assertAlmostEqual(7194.3, units.volume.u_s_quarts.to_teaspoons(45.0), places=1)
		self.assertAlmostEqual(1039.18, units.volume.u_s_quarts.to_teaspoons(6.5), places=1)
		self.assertAlmostEqual(143.886, units.volume.u_s_quarts.to_teaspoons(0.9), places=1)

	def test_convert_known_u_s_quarts_to_tablespoons(self):
		self.assertAlmostEqual(319.747, units.volume.u_s_quarts.to_tablespoons(6.0), places=1)
		self.assertAlmostEqual(4764.227, units.volume.u_s_quarts.to_tablespoons(89.4), places=1)
		self.assertAlmostEqual(248.8696, units.volume.u_s_quarts.to_tablespoons(4.67), places=1)

	def test_convert_known_u_s_quarts_to_quarts(self):
		self.assertAlmostEqual(3.8303, units.volume.u_s_quarts.to_quarts(4.6), places=1)
		self.assertAlmostEqual(0.749407, units.volume.u_s_quarts.to_quarts(0.9), places=1)
		self.assertAlmostEqual(111.578, units.volume.u_s_quarts.to_quarts(134.0), places=1)

	def test_convert_known_u_s_quarts_to_pints(self):
		self.assertAlmostEqual(204.838, units.volume.u_s_quarts.to_pints(123.0), places=1)
		self.assertAlmostEqual(1816.72854, units.volume.u_s_quarts.to_pints(1090.9), places=1)
		self.assertAlmostEqual(93.2595, units.volume.u_s_quarts.to_pints(56.0), places=1)

	def test_convert_known_u_s_quarts_to_gallons(self):
		self.assertAlmostEqual(11.6574, units.volume.u_s_quarts.to_gallons(56.0), places=1)
		self.assertAlmostEqual(1.48216, units.volume.u_s_quarts.to_gallons(7.12), places=1)
		self.assertAlmostEqual(166.535, units.volume.u_s_quarts.to_gallons(800.0), places=1)

	def test_convert_known_u_s_quarts_to_fluid_ounces(self):
		self.assertAlmostEqual(26645.56289492, units.volume.u_s_quarts.to_fluid_ounces(800.0), places=1)
		self.assertAlmostEqual(226.487, units.volume.u_s_quarts.to_fluid_ounces(6.8), places=1)
		self.assertAlmostEqual(29.9763, units.volume.u_s_quarts.to_fluid_ounces(0.9), places=1)

	def test_convert_known_u_s_quarts_to_u_s_teaspoons(self):
		self.assertAlmostEqual(576.0, units.volume.u_s_quarts.to_u_s_teaspoons(3.0), places=1)
		self.assertAlmostEqual(23.04001, units.volume.u_s_quarts.to_u_s_teaspoons(0.12), places=1)
		self.assertAlmostEqual(864.0, units.volume.u_s_quarts.to_u_s_teaspoons(4.5), places=1)

	def test_convert_known_u_s_quarts_to_u_s_tablespoons(self):
		self.assertAlmostEqual(288.0, units.volume.u_s_quarts.to_u_s_tablespoons(4.5), places=1)
		self.assertAlmostEqual(49.728, units.volume.u_s_quarts.to_u_s_tablespoons(0.777), places=1)
		self.assertAlmostEqual(115.2, units.volume.u_s_quarts.to_u_s_tablespoons(1.8), places=1)

	def test_convert_known_u_s_quarts_to_u_s_pints(self):
		self.assertAlmostEqual(3.6, units.volume.u_s_quarts.to_u_s_pints(1.8), places=1)
		self.assertAlmostEqual(1800.0, units.volume.u_s_quarts.to_u_s_pints(900.0), places=1)
		self.assertAlmostEqual(24.9, units.volume.u_s_quarts.to_u_s_pints(12.45), places=1)

	def test_convert_known_u_s_quarts_to_u_s_gallons(self):
		self.assertAlmostEqual(3.1125, units.volume.u_s_quarts.to_u_s_gallons(12.45), places=1)
		self.assertAlmostEqual(0.2, units.volume.u_s_quarts.to_u_s_gallons(0.8), places=1)
		self.assertAlmostEqual(25.225, units.volume.u_s_quarts.to_u_s_gallons(100.9), places=1)

	def test_convert_known_u_s_quarts_to_u_s_fluid_ounces(self):
		self.assertAlmostEqual(3228.8, units.volume.u_s_quarts.to_u_s_fluid_ounces(100.9), places=1)
		self.assertAlmostEqual(395040.0, units.volume.u_s_quarts.to_u_s_fluid_ounces(12345.0), places=1)
		self.assertAlmostEqual(278.4, units.volume.u_s_quarts.to_u_s_fluid_ounces(8.7), places=1)

	def test_convert_known_u_s_quarts_to_u_s_cups(self):
		self.assertAlmostEqual(34.8, units.volume.u_s_quarts.to_u_s_cups(8.7), places=1)
		self.assertAlmostEqual(495.6, units.volume.u_s_quarts.to_u_s_cups(123.9), places=1)
		self.assertAlmostEqual(2.64, units.volume.u_s_quarts.to_u_s_cups(0.66), places=1)

	def test_convert_known_u_s_quarts_to_cubic_metres(self):
		self.assertAlmostEqual(8.0, units.volume.u_s_quarts.to_cubic_metres(8453.51), places=1)
		self.assertAlmostEqual(4.731765, units.volume.u_s_quarts.to_cubic_metres(5000.0), places=1)
		self.assertAlmostEqual(116.832949, units.volume.u_s_quarts.to_cubic_metres(123456.0), places=1)

	def test_convert_known_u_s_quarts_to_cubic_feet(self):
		self.assertAlmostEqual(1.47049, units.volume.u_s_quarts.to_cubic_feet(44.0), places=1)
		self.assertAlmostEqual(89.0, units.volume.u_s_quarts.to_cubic_feet(2663.06), places=1)
		self.assertAlmostEqual(14.8385, units.volume.u_s_quarts.to_cubic_feet(444.0), places=1)

	def test_convert_known_u_s_quarts_to_cubic_inches(self):
		self.assertAlmostEqual(2541.0, units.volume.u_s_quarts.to_cubic_inches(44.0), places=1)
		self.assertAlmostEqual(46200.0, units.volume.u_s_quarts.to_cubic_inches(800.0), places=1)
		self.assertAlmostEqual(346.5, units.volume.u_s_quarts.to_cubic_inches(6.0), places=1)

	def test_convert_known_u_s_quarts_to_oil_barrels(self):
		self.assertAlmostEqual(55.0, units.volume.u_s_quarts.to_oil_barrels(9240.0), places=1)
		self.assertAlmostEqual(8.0, units.volume.u_s_quarts.to_oil_barrels(1344.0), places=1)
		self.assertAlmostEqual(1234.0, units.volume.u_s_quarts.to_oil_barrels(207312.0), places=1)

if __name__ == '__main__':
    unittest.main()
