# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.speed.knots

class TestKnotsMethods(unittest.TestCase):

	def test_convert_known_knots_to_miles_per_hour(self):
		self.assertAlmostEqual(9.20624, units.speed.knots.to_miles_per_hour(8.0), places=1)
		self.assertAlmostEqual(1.38094, units.speed.knots.to_miles_per_hour(1.2), places=1)
		self.assertAlmostEqual(771.022, units.speed.knots.to_miles_per_hour(670.0), places=1)

	def test_convert_known_knots_to_kilometres_per_hour(self):
		self.assertAlmostEqual(1255.66, units.speed.knots.to_kilometres_per_hour(678.0), places=1)
		self.assertAlmostEqual(3.3336, units.speed.knots.to_kilometres_per_hour(1.8), places=1)
		self.assertAlmostEqual(103.712, units.speed.knots.to_kilometres_per_hour(56.0), places=1)

	def test_convert_known_knots_to_feet_per_second(self):
		self.assertAlmostEqual(94.5174, units.speed.knots.to_feet_per_second(56.0), places=1)
		self.assertAlmostEqual(7.93271, units.speed.knots.to_feet_per_second(4.7), places=1)
		self.assertAlmostEqual(5.06343, units.speed.knots.to_feet_per_second(3.0), places=1)

	def test_convert_known_knots_to_metres_per_second(self):
		self.assertAlmostEqual(2.57222, units.speed.knots.to_metres_per_second(5.0), places=1)
		self.assertAlmostEqual(4.68144, units.speed.knots.to_metres_per_second(9.1), places=1)
		self.assertAlmostEqual(97.7444, units.speed.knots.to_metres_per_second(190.0), places=1)

if __name__ == '__main__':
    unittest.main()
