# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.data_transfer_rate.giga_bytes_per_second

class TestGigaBytesPerSecondMethods(unittest.TestCase):

	def test_convert_known_giga_bytes_per_second_to_bits_per_second(self):
		self.assertAlmostEqual(32000000.0, units.data_transfer_rate.giga_bytes_per_second.to_bits_per_second(0.004), places=1)
		self.assertAlmostEqual(96000000.0, units.data_transfer_rate.giga_bytes_per_second.to_bits_per_second(0.012), places=1)
		self.assertAlmostEqual(24.0, units.data_transfer_rate.giga_bytes_per_second.to_bits_per_second(3e-9), places=1)

	def test_convert_known_giga_bytes_per_second_to_kilo_bits_per_second(self):
		self.assertAlmostEqual(72000.0, units.data_transfer_rate.giga_bytes_per_second.to_kilo_bits_per_second(0.009), places=1)
		self.assertAlmostEqual(960.0, units.data_transfer_rate.giga_bytes_per_second.to_kilo_bits_per_second(1.2e-4), places=1)
		self.assertAlmostEqual(62400.0, units.data_transfer_rate.giga_bytes_per_second.to_kilo_bits_per_second(0.0078), places=1)

	def test_convert_known_giga_bytes_per_second_to_mega_bits_per_second(self):
		self.assertAlmostEqual(62.4, units.data_transfer_rate.giga_bytes_per_second.to_mega_bits_per_second(0.0078), places=1)
		self.assertAlmostEqual(80.0, units.data_transfer_rate.giga_bytes_per_second.to_mega_bits_per_second(0.01), places=1)
		self.assertAlmostEqual(9.872, units.data_transfer_rate.giga_bytes_per_second.to_mega_bits_per_second(0.001234), places=1)

	def test_convert_known_giga_bytes_per_second_to_giga_bits_per_second(self):
		self.assertAlmostEqual(40.0, units.data_transfer_rate.giga_bytes_per_second.to_giga_bits_per_second(5.0), places=1)
		self.assertAlmostEqual(9.6, units.data_transfer_rate.giga_bytes_per_second.to_giga_bits_per_second(1.2), places=1)
		self.assertAlmostEqual(0.08, units.data_transfer_rate.giga_bytes_per_second.to_giga_bits_per_second(0.01), places=1)

	def test_convert_known_giga_bytes_per_second_to_tera_bits_per_second(self):
		self.assertAlmostEqual(0.56, units.data_transfer_rate.giga_bytes_per_second.to_tera_bits_per_second(70.0), places=1)
		self.assertAlmostEqual(72.008, units.data_transfer_rate.giga_bytes_per_second.to_tera_bits_per_second(9001.0), places=1)
		self.assertAlmostEqual(6144.9912, units.data_transfer_rate.giga_bytes_per_second.to_tera_bits_per_second(768123.9), places=1)

	def test_convert_known_giga_bytes_per_second_to_kilo_bytes_per_second(self):
		self.assertAlmostEqual(200000.0, units.data_transfer_rate.giga_bytes_per_second.to_kilo_bytes_per_second(0.2), places=1)
		self.assertAlmostEqual(9000.0, units.data_transfer_rate.giga_bytes_per_second.to_kilo_bytes_per_second(0.009), places=1)
		self.assertAlmostEqual(1230.0, units.data_transfer_rate.giga_bytes_per_second.to_kilo_bytes_per_second(0.00123), places=1)

	def test_convert_known_giga_bytes_per_second_to_mega_bytes_per_second(self):
		self.assertAlmostEqual(900.0, units.data_transfer_rate.giga_bytes_per_second.to_mega_bytes_per_second(0.9), places=1)
		self.assertAlmostEqual(12000.0, units.data_transfer_rate.giga_bytes_per_second.to_mega_bytes_per_second(12.0), places=1)
		self.assertAlmostEqual(35600.0, units.data_transfer_rate.giga_bytes_per_second.to_mega_bytes_per_second(35.6), places=1)

	def test_convert_known_giga_bytes_per_second_to_tera_bytes_per_second(self):
		self.assertAlmostEqual(0.0356, units.data_transfer_rate.giga_bytes_per_second.to_tera_bytes_per_second(35.6), places=1)
		self.assertAlmostEqual(0.10023, units.data_transfer_rate.giga_bytes_per_second.to_tera_bytes_per_second(100.23), places=1)
		self.assertAlmostEqual(900.1, units.data_transfer_rate.giga_bytes_per_second.to_tera_bytes_per_second(900100.0), places=1)

	def test_convert_known_giga_bytes_per_second_to_kibibits_per_second(self):
		self.assertAlmostEqual(390625.0, units.data_transfer_rate.giga_bytes_per_second.to_kibibits_per_second(0.05), places=1)
		self.assertAlmostEqual(62500.0, units.data_transfer_rate.giga_bytes_per_second.to_kibibits_per_second(0.008), places=1)
		self.assertAlmostEqual(9609.375, units.data_transfer_rate.giga_bytes_per_second.to_kibibits_per_second(0.00123), places=1)

	def test_convert_known_giga_bytes_per_second_to_mebibits_per_second(self):
		self.assertAlmostEqual(68.66451, units.data_transfer_rate.giga_bytes_per_second.to_mebibits_per_second(0.009), places=1)
		self.assertAlmostEqual(9155.268, units.data_transfer_rate.giga_bytes_per_second.to_mebibits_per_second(1.2), places=1)
		self.assertAlmostEqual(146484.288, units.data_transfer_rate.giga_bytes_per_second.to_mebibits_per_second(19.2), places=1)

if __name__ == '__main__':
    unittest.main()
