# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.area.hectares

class TestHectaresMethods(unittest.TestCase):

	def test_convert_known_hectares_to_square_kilometres(self):
		self.assertAlmostEqual(150.0, units.area.hectares.to_square_kilometres(15000.0), places=1)
		self.assertAlmostEqual(3.0, units.area.hectares.to_square_kilometres(300.0), places=1)
		self.assertAlmostEqual(0.456, units.area.hectares.to_square_kilometres(45.6), places=1)

	def test_convert_known_hectares_to_square_metres(self):
		self.assertAlmostEqual(14000.0, units.area.hectares.to_square_metres(1.4), places=1)
		self.assertAlmostEqual(9000.0, units.area.hectares.to_square_metres(0.9), places=1)
		self.assertAlmostEqual(120.0, units.area.hectares.to_square_metres(0.012), places=1)

	def test_convert_known_hectares_to_square_miles(self):
		self.assertAlmostEqual(4.254846, units.area.hectares.to_square_miles(1102.0), places=1)
		self.assertAlmostEqual(17.3746, units.area.hectares.to_square_miles(4500.0), places=1)
		self.assertAlmostEqual(0.347492, units.area.hectares.to_square_miles(90.0), places=1)

	def test_convert_known_hectares_to_square_yards(self):
		self.assertAlmostEqual(14351.8805556, units.area.hectares.to_square_yards(1.2), places=1)
		self.assertAlmostEqual(9567.92, units.area.hectares.to_square_yards(0.8), places=1)
		self.assertAlmostEqual(406636.615, units.area.hectares.to_square_yards(34.0), places=1)

	def test_convert_known_hectares_to_square_feet(self):
		self.assertAlmostEqual(365972.599, units.area.hectares.to_square_feet(3.4), places=1)
		self.assertAlmostEqual(9687.519, units.area.hectares.to_square_feet(0.09), places=1)
		self.assertAlmostEqual(129166.7999, units.area.hectares.to_square_feet(1.2), places=1)

	def test_convert_known_hectares_to_square_inches(self):
		self.assertAlmostEqual(139500.28, units.area.hectares.to_square_inches(0.009), places=1)
		self.assertAlmostEqual(155000.31, units.area.hectares.to_square_inches(0.01), places=1)
		self.assertAlmostEqual(94550.1891, units.area.hectares.to_square_inches(0.0061), places=1)

	def test_convert_known_hectares_to_acres(self):
		self.assertAlmostEqual(2.96526, units.area.hectares.to_acres(1.2), places=1)
		self.assertAlmostEqual(1.97684, units.area.hectares.to_acres(0.8), places=1)
		self.assertAlmostEqual(10.3784, units.area.hectares.to_acres(4.2), places=1)

if __name__ == '__main__':
    unittest.main()
