# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.energy.watt_hours

class TestWattHoursMethods(unittest.TestCase):

	def test_convert_known_watt_hours_to_kilojoules(self):
		self.assertAlmostEqual(5.76, units.energy.watt_hours.to_kilojoules(1.6), places=1)
		self.assertAlmostEqual(241.2, units.energy.watt_hours.to_kilojoules(67.0), places=1)
		self.assertAlmostEqual(29.232, units.energy.watt_hours.to_kilojoules(8.12), places=1)

	def test_convert_known_watt_hours_to_kilocalories(self):
		self.assertAlmostEqual(6.986616, units.energy.watt_hours.to_kilocalories(8.12), places=1)
		self.assertAlmostEqual(146.272, units.energy.watt_hours.to_kilocalories(170.0), places=1)
		self.assertAlmostEqual(16.52008, units.energy.watt_hours.to_kilocalories(19.2), places=1)

	def test_convert_known_watt_hours_to_joules(self):
		self.assertAlmostEqual(24120.0, units.energy.watt_hours.to_joules(6.7), places=1)
		self.assertAlmostEqual(44424.0, units.energy.watt_hours.to_joules(12.34), places=1)
		self.assertAlmostEqual(324.0, units.energy.watt_hours.to_joules(0.09), places=1)

	def test_convert_known_watt_hours_to_btu(self):
		self.assertAlmostEqual(116.013, units.energy.watt_hours.to_btu(34.0), places=1)
		self.assertAlmostEqual(611.45578, units.energy.watt_hours.to_btu(179.2), places=1)
		self.assertAlmostEqual(3.07093, units.energy.watt_hours.to_btu(0.9), places=1)

	def test_convert_known_watt_hours_to_calories(self):
		self.assertAlmostEqual(172.084, units.energy.watt_hours.to_calories(0.2), places=1)
		self.assertAlmostEqual(77.43786, units.energy.watt_hours.to_calories(0.09), places=1)
		self.assertAlmostEqual(10325.06754, units.energy.watt_hours.to_calories(12.0), places=1)

	def test_convert_known_watt_hours_to_u_s_therms(self):
		self.assertAlmostEqual(0.03720122, units.energy.watt_hours.to_u_s_therms(1090.0), places=1)
		self.assertAlmostEqual(1.7061369, units.energy.watt_hours.to_u_s_therms(49990.0), places=1)
		self.assertAlmostEqual(30.7439107, units.energy.watt_hours.to_u_s_therms(900800.0), places=1)

	def test_convert_known_watt_hours_to_kilowatt_hours(self):
		self.assertAlmostEqual(0.098, units.energy.watt_hours.to_kilowatt_hours(98.0), places=1)
		self.assertAlmostEqual(0.0125, units.energy.watt_hours.to_kilowatt_hours(12.5), places=1)
		self.assertAlmostEqual(0.0006, units.energy.watt_hours.to_kilowatt_hours(0.6), places=1)

	def test_convert_known_watt_hours_to_foot_pounds(self):
		self.assertAlmostEqual(3982.829, units.energy.watt_hours.to_foot_pounds(1.5), places=1)
		self.assertAlmostEqual(796.567, units.energy.watt_hours.to_foot_pounds(0.3), places=1)
		self.assertAlmostEqual(239235.3219, units.energy.watt_hours.to_foot_pounds(90.1), places=1)

	def test_convert_known_watt_hours_to_electronvolts(self):
		self.assertAlmostEqual(1496463565615.39, units.energy.watt_hours.to_electronvolts(0.0000000000666), places=1)
		self.assertAlmostEqual(179755383257104.03, units.energy.watt_hours.to_electronvolts(0.000000008), places=1)
		self.assertAlmostEqual(2.7637390175779744E+17, units.energy.watt_hours.to_electronvolts(0.0000123), places=1)

if __name__ == '__main__':
    unittest.main()
