# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.frequency.hertz

class TestHertzMethods(unittest.TestCase):

	def test_convert_known_hertz_to_kilohertz(self):
		self.assertAlmostEqual(0.8, units.frequency.hertz.to_kilohertz(800.0), places=1)
		self.assertAlmostEqual(1.5069, units.frequency.hertz.to_kilohertz(1506.9), places=1)
		self.assertAlmostEqual(5.0, units.frequency.hertz.to_kilohertz(5000.0), places=1)

	def test_convert_known_hertz_to_megahertz(self):
		self.assertAlmostEqual(0.900009, units.frequency.hertz.to_megahertz(900009.0), places=1)
		self.assertAlmostEqual(0.16, units.frequency.hertz.to_megahertz(160000.0), places=1)
		self.assertAlmostEqual(0.888888, units.frequency.hertz.to_megahertz(888888.0), places=1)

	def test_convert_known_hertz_to_gigahertz(self):
		self.assertAlmostEqual(0.1009009, units.frequency.hertz.to_gigahertz(100900900.0), places=1)
		self.assertAlmostEqual(9e-9, units.frequency.hertz.to_gigahertz(9.0), places=1)
		self.assertAlmostEqual(0.09090909, units.frequency.hertz.to_gigahertz(90909090.0), places=1)

if __name__ == '__main__':
    unittest.main()
