# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.length.millimetres

class TestMillimetresMethods(unittest.TestCase):

	def test_convert_known_millimetres_to_centimetres(self):
		self.assertAlmostEqual(90.0, units.length.millimetres.to_centimetres(900.0), places=1)
		self.assertAlmostEqual(19.0, units.length.millimetres.to_centimetres(190.0), places=1)
		self.assertAlmostEqual(500.0, units.length.millimetres.to_centimetres(5000.0), places=1)

	def test_convert_known_millimetres_to_metres(self):
		self.assertAlmostEqual(1.09, units.length.millimetres.to_metres(1090.0), places=1)
		self.assertAlmostEqual(9.0, units.length.millimetres.to_metres(9000.0), places=1)
		self.assertAlmostEqual(12.345, units.length.millimetres.to_metres(12345.0), places=1)

	def test_convert_known_millimetres_to_kilometres(self):
		self.assertAlmostEqual(0.109, units.length.millimetres.to_kilometres(109000.0), places=1)
		self.assertAlmostEqual(9.876543, units.length.millimetres.to_kilometres(9876543.0), places=1)
		self.assertAlmostEqual(0.9008, units.length.millimetres.to_kilometres(900800.0), places=1)

	def test_convert_known_millimetres_to_inches(self):
		self.assertAlmostEqual(35.4331, units.length.millimetres.to_inches(900.0), places=1)
		self.assertAlmostEqual(4.84252, units.length.millimetres.to_inches(123.0), places=1)
		self.assertAlmostEqual(3.14961, units.length.millimetres.to_inches(80.0), places=1)

	def test_convert_known_millimetres_to_feet(self):
		self.assertAlmostEqual(2.62467, units.length.millimetres.to_feet(800.0), places=1)
		self.assertAlmostEqual(4.048556, units.length.millimetres.to_feet(1234.0), places=1)
		self.assertAlmostEqual(1.9711286, units.length.millimetres.to_feet(600.8), places=1)

	def test_convert_known_millimetres_to_yards(self):
		self.assertAlmostEqual(0.874891, units.length.millimetres.to_yards(800.0), places=1)
		self.assertAlmostEqual(1.312336, units.length.millimetres.to_yards(1200.0), places=1)
		self.assertAlmostEqual(0.994094, units.length.millimetres.to_yards(909.0), places=1)

	def test_convert_known_millimetres_to_miles(self):
		self.assertAlmostEqual(0.559234073, units.length.millimetres.to_miles(900000.0), places=1)
		self.assertAlmostEqual(7.671249217072, units.length.millimetres.to_miles(12345678.9), places=1)
		self.assertAlmostEqual(62.2615798735, units.length.millimetres.to_miles(100200300.0), places=1)

	def test_convert_known_millimetres_to_nautical_miles(self):
		self.assertAlmostEqual(4.859611231, units.length.millimetres.to_nautical_miles(9000000.0), places=1)
		self.assertAlmostEqual(6.6661328294, units.length.millimetres.to_nautical_miles(12345678.0), places=1)
		self.assertAlmostEqual(0.5, units.length.millimetres.to_nautical_miles(926000.0), places=1)

if __name__ == '__main__':
    unittest.main()
