# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.angle.radians

class TestRadiansMethods(unittest.TestCase):

	def test_convert_known_radians_to_degrees(self):
		self.assertAlmostEqual(257.831, units.angle.radians.to_degrees(4.5), places=1)
		self.assertAlmostEqual(51.5662, units.angle.radians.to_degrees(0.9), places=1)
		self.assertAlmostEqual(4520.637, units.angle.radians.to_degrees(78.9), places=1)

	def test_convert_known_radians_to_gradians(self):
		self.assertAlmostEqual(318.31, units.angle.radians.to_gradians(5.0), places=1)
		self.assertAlmostEqual(57.2958, units.angle.radians.to_gradians(0.9), places=1)
		self.assertAlmostEqual(5665.92, units.angle.radians.to_gradians(89.0), places=1)

	def test_convert_known_radians_to_milliradians(self):
		self.assertAlmostEqual(5000.0, units.angle.radians.to_milliradians(5.0), places=1)
		self.assertAlmostEqual(130.0, units.angle.radians.to_milliradians(0.13), places=1)
		self.assertAlmostEqual(130.0, units.angle.radians.to_milliradians(0.13), places=1)
		self.assertAlmostEqual(89100.0, units.angle.radians.to_milliradians(89.1), places=1)

	def test_convert_known_radians_to_minute_of_arc(self):
		self.assertAlmostEqual(20626.480624709635, units.angle.radians.to_minute_of_arc(6.0), places=1)
		self.assertAlmostEqual(2750.2, units.angle.radians.to_minute_of_arc(0.8), places=1)
		self.assertAlmostEqual(7906.82, units.angle.radians.to_minute_of_arc(2.3), places=1)

	def test_convert_known_radians_to_seconds_of_arc(self):
		self.assertAlmostEqual(165011.84499767708, units.angle.radians.to_seconds_of_arc(0.8), places=1)
		self.assertAlmostEqual(206.26481, units.angle.radians.to_seconds_of_arc(0.001), places=1)
		self.assertAlmostEqual(185638.32562238674, units.angle.radians.to_seconds_of_arc(0.9), places=1)

if __name__ == '__main__':
    unittest.main()
