# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.volume.u_s_teaspoons

class TestUSTeaspoonsMethods(unittest.TestCase):

	def test_convert_known_u_s_teaspoons_to_millilitres(self):
		self.assertAlmostEqual(34.0095, units.volume.u_s_teaspoons.to_millilitres(6.9), places=1)
		self.assertAlmostEqual(7.88627, units.volume.u_s_teaspoons.to_millilitres(1.6), places=1)
		self.assertAlmostEqual(3943.14, units.volume.u_s_teaspoons.to_millilitres(800.0), places=1)

	def test_convert_known_u_s_teaspoons_to_litres(self):
		self.assertAlmostEqual(0.0345024, units.volume.u_s_teaspoons.to_litres(7.0), places=1)
		self.assertAlmostEqual(0.443603, units.volume.u_s_teaspoons.to_litres(90.0), places=1)
		self.assertAlmostEqual(0.2794698, units.volume.u_s_teaspoons.to_litres(56.7), places=1)

	def test_convert_known_u_s_teaspoons_to_kilolitres(self):
		self.assertAlmostEqual(49.33356028, units.volume.u_s_teaspoons.to_kilolitres(10009000.0), places=1)
		self.assertAlmostEqual(6.08508592078, units.volume.u_s_teaspoons.to_kilolitres(1234567.8), places=1)
		self.assertAlmostEqual(0.04830342, units.volume.u_s_teaspoons.to_kilolitres(9800.0), places=1)

	def test_convert_known_u_s_teaspoons_to_teaspoons(self):
		self.assertAlmostEqual(101.586, units.volume.u_s_teaspoons.to_teaspoons(122.0), places=1)
		self.assertAlmostEqual(74.27448, units.volume.u_s_teaspoons.to_teaspoons(89.2), places=1)
		self.assertAlmostEqual(749.406, units.volume.u_s_teaspoons.to_teaspoons(900.0), places=1)

	def test_convert_known_u_s_teaspoons_to_tablespoons(self):
		self.assertAlmostEqual(138.779, units.volume.u_s_teaspoons.to_tablespoons(500.0), places=1)
		self.assertAlmostEqual(3.425064, units.volume.u_s_teaspoons.to_tablespoons(12.34), places=1)
		self.assertAlmostEqual(185.131, units.volume.u_s_teaspoons.to_tablespoons(667.0), places=1)

	def test_convert_known_u_s_teaspoons_to_quarts(self):
		self.assertAlmostEqual(0.338274, units.volume.u_s_teaspoons.to_quarts(78.0), places=1)
		self.assertAlmostEqual(3.9035927, units.volume.u_s_teaspoons.to_quarts(900.1), places=1)
		self.assertAlmostEqual(0.50697698, units.volume.u_s_teaspoons.to_quarts(116.9), places=1)

	def test_convert_known_u_s_teaspoons_to_pints(self):
		self.assertAlmostEqual(1.00615, units.volume.u_s_teaspoons.to_pints(116.0), places=1)
		self.assertAlmostEqual(0.5160844, units.volume.u_s_teaspoons.to_pints(59.5), places=1)
		self.assertAlmostEqual(16.48, units.volume.u_s_teaspoons.to_pints(1900.0), places=1)

	def test_convert_known_u_s_teaspoons_to_gallons(self):
		self.assertAlmostEqual(0.215758, units.volume.u_s_teaspoons.to_gallons(199.0), places=1)
		self.assertAlmostEqual(13.384583, units.volume.u_s_teaspoons.to_gallons(12345.0), places=1)
		self.assertAlmostEqual(97.580059, units.volume.u_s_teaspoons.to_gallons(90001.0), places=1)

	def test_convert_known_u_s_teaspoons_to_fluid_ounces(self):
		self.assertAlmostEqual(21.3373, units.volume.u_s_teaspoons.to_fluid_ounces(123.0), places=1)
		self.assertAlmostEqual(15.4392, units.volume.u_s_teaspoons.to_fluid_ounces(89.0), places=1)
		self.assertAlmostEqual(175.035, units.volume.u_s_teaspoons.to_fluid_ounces(1009.0), places=1)

	def test_convert_known_u_s_teaspoons_to_u_s_tablespoons(self):
		self.assertAlmostEqual(63.3333, units.volume.u_s_teaspoons.to_u_s_tablespoons(190.0), places=1)
		self.assertAlmostEqual(1.86667, units.volume.u_s_teaspoons.to_u_s_tablespoons(5.6), places=1)
		self.assertAlmostEqual(0.233333, units.volume.u_s_teaspoons.to_u_s_tablespoons(0.7), places=1)

	def test_convert_known_u_s_teaspoons_to_u_s_quarts(self):
		self.assertAlmostEqual(0.5229165, units.volume.u_s_teaspoons.to_u_s_quarts(100.4), places=1)
		self.assertAlmostEqual(46.87498, units.volume.u_s_teaspoons.to_u_s_quarts(9000.0), places=1)
		self.assertAlmostEqual(6.427081, units.volume.u_s_teaspoons.to_u_s_quarts(1234.0), places=1)

	def test_convert_known_u_s_teaspoons_to_u_s_pints(self):
		self.assertAlmostEqual(1.13542, units.volume.u_s_teaspoons.to_u_s_pints(109.0), places=1)
		self.assertAlmostEqual(35.41666, units.volume.u_s_teaspoons.to_u_s_pints(3400.0), places=1)
		self.assertAlmostEqual(0.1114583, units.volume.u_s_teaspoons.to_u_s_pints(10.7), places=1)

	def test_convert_known_u_s_teaspoons_to_u_s_gallons(self):
		self.assertAlmostEqual(0.141927, units.volume.u_s_teaspoons.to_u_s_gallons(109.0), places=1)
		self.assertAlmostEqual(12.85937, units.volume.u_s_teaspoons.to_u_s_gallons(9876.0), places=1)
		self.assertAlmostEqual(14.192704, units.volume.u_s_teaspoons.to_u_s_gallons(10900.0), places=1)

	def test_convert_known_u_s_teaspoons_to_u_s_fluid_ounces(self):
		self.assertAlmostEqual(30.0, units.volume.u_s_teaspoons.to_u_s_fluid_ounces(180.0), places=1)
		self.assertAlmostEqual(0.933333, units.volume.u_s_teaspoons.to_u_s_fluid_ounces(5.6), places=1)
		self.assertAlmostEqual(150.08328, units.volume.u_s_teaspoons.to_u_s_fluid_ounces(900.5), places=1)

	def test_convert_known_u_s_teaspoons_to_u_s_cups(self):
		self.assertAlmostEqual(1.875, units.volume.u_s_teaspoons.to_u_s_cups(90.0), places=1)
		self.assertAlmostEqual(93.7666363, units.volume.u_s_teaspoons.to_u_s_cups(4500.8), places=1)
		self.assertAlmostEqual(0.01875, units.volume.u_s_teaspoons.to_u_s_cups(0.9), places=1)

if __name__ == '__main__':
    unittest.main()
