# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.luminous_energy.lumen_second

class TestLumenSecondMethods(unittest.TestCase):

	def test_convert_known_lumen_second_to_talbot(self):
		self.assertAlmostEqual(190.0, units.luminous_energy.lumen_second.to_talbot(190.0), places=1)
		self.assertAlmostEqual(0.6, units.luminous_energy.lumen_second.to_talbot(0.6), places=1)
		self.assertAlmostEqual(5000.0, units.luminous_energy.lumen_second.to_talbot(5000.0), places=1)

	def test_convert_known_lumen_second_to_lumen_hour(self):
		self.assertAlmostEqual(0.052778, units.luminous_energy.lumen_second.to_lumen_hour(190.0), places=1)
		self.assertAlmostEqual(55.7222, units.luminous_energy.lumen_second.to_lumen_hour(200600.0), places=1)
		self.assertAlmostEqual(0.342778, units.luminous_energy.lumen_second.to_lumen_hour(1234.0), places=1)

	def test_convert_known_lumen_second_to_lumen_minute(self):
		self.assertAlmostEqual(181.6667, units.luminous_energy.lumen_second.to_lumen_minute(10900.0), places=1)
		self.assertAlmostEqual(0.83833, units.luminous_energy.lumen_second.to_lumen_minute(50.3), places=1)
		self.assertAlmostEqual(4.6, units.luminous_energy.lumen_second.to_lumen_minute(276.0), places=1)

if __name__ == '__main__':
    unittest.main()
