# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.force.dynes

class TestDynesMethods(unittest.TestCase):

	def test_convert_known_dynes_to_newtons(self):
		self.assertAlmostEqual(0.009, units.force.dynes.to_newtons(900.0), places=1)
		self.assertAlmostEqual(0.01234, units.force.dynes.to_newtons(1234.0), places=1)
		self.assertAlmostEqual(0.00046, units.force.dynes.to_newtons(46.0), places=1)

	def test_convert_known_dynes_to_poundals(self):
		self.assertAlmostEqual(0.73046207, units.force.dynes.to_poundals(10099.0), places=1)
		self.assertAlmostEqual(5.7864111, units.force.dynes.to_poundals(80000.0), places=1)
		self.assertAlmostEqual(0.89291556, units.force.dynes.to_poundals(12345.0), places=1)

	def test_convert_known_dynes_to_kilogramforce(self):
		self.assertAlmostEqual(0.125890085, units.force.dynes.to_kilogramforce(123456.0), places=1)
		self.assertAlmostEqual(0.081577297, units.force.dynes.to_kilogramforce(80000.0), places=1)
		self.assertAlmostEqual(1007.12712394, units.force.dynes.to_kilogramforce(987654321.0), places=1)

if __name__ == '__main__':
    unittest.main()
