# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.volume.u_s_fluid_ounces

class TestUSFluidOuncesMethods(unittest.TestCase):

	def test_convert_known_u_s_fluid_ounces_to_millilitres(self):
		self.assertAlmostEqual(28.98206, units.volume.u_s_fluid_ounces.to_millilitres(0.98), places=1)
		self.assertAlmostEqual(242.503, units.volume.u_s_fluid_ounces.to_millilitres(8.2), places=1)
		self.assertAlmostEqual(2966.225, units.volume.u_s_fluid_ounces.to_millilitres(100.3), places=1)

	def test_convert_known_u_s_fluid_ounces_to_litres(self):
		self.assertAlmostEqual(0.354882, units.volume.u_s_fluid_ounces.to_litres(12.0), places=1)
		self.assertAlmostEqual(4.4537736, units.volume.u_s_fluid_ounces.to_litres(150.6), places=1)
		self.assertAlmostEqual(0.174484, units.volume.u_s_fluid_ounces.to_litres(5.9), places=1)

	def test_convert_known_u_s_fluid_ounces_to_kilolitres(self):
		self.assertAlmostEqual(0.0010055, units.volume.u_s_fluid_ounces.to_kilolitres(34.0), places=1)
		self.assertAlmostEqual(0.0032264721, units.volume.u_s_fluid_ounces.to_kilolitres(109.1), places=1)
		self.assertAlmostEqual(1.3508597, units.volume.u_s_fluid_ounces.to_kilolitres(45678.0), places=1)

	def test_convert_known_u_s_fluid_ounces_to_teaspoons(self):
		self.assertAlmostEqual(19.9842, units.volume.u_s_fluid_ounces.to_teaspoons(4.0), places=1)
		self.assertAlmostEqual(0.5995252, units.volume.u_s_fluid_ounces.to_teaspoons(0.12), places=1)
		self.assertAlmostEqual(14.93817, units.volume.u_s_fluid_ounces.to_teaspoons(2.99), places=1)

	def test_convert_known_u_s_fluid_ounces_to_tablespoons(self):
		self.assertAlmostEqual(1332.28, units.volume.u_s_fluid_ounces.to_tablespoons(800.0), places=1)
		self.assertAlmostEqual(0.03330695, units.volume.u_s_fluid_ounces.to_tablespoons(0.02), places=1)
		self.assertAlmostEqual(4.49644, units.volume.u_s_fluid_ounces.to_tablespoons(2.7), places=1)

	def test_convert_known_u_s_fluid_ounces_to_quarts(self):
		self.assertAlmostEqual(0.0910737, units.volume.u_s_fluid_ounces.to_quarts(3.5), places=1)
		self.assertAlmostEqual(0.01977601, units.volume.u_s_fluid_ounces.to_quarts(0.76), places=1)
		self.assertAlmostEqual(0.0520421, units.volume.u_s_fluid_ounces.to_quarts(2.0), places=1)

	def test_convert_known_u_s_fluid_ounces_to_pints(self):
		self.assertAlmostEqual(0.624506, units.volume.u_s_fluid_ounces.to_pints(12.0), places=1)
		self.assertAlmostEqual(0.0208169, units.volume.u_s_fluid_ounces.to_pints(0.4), places=1)
		self.assertAlmostEqual(0.1035639, units.volume.u_s_fluid_ounces.to_pints(1.99), places=1)

	def test_convert_known_u_s_fluid_ounces_to_gallons(self):
		self.assertAlmostEqual(0.0195158, units.volume.u_s_fluid_ounces.to_gallons(3.0), places=1)
		self.assertAlmostEqual(0.65377934, units.volume.u_s_fluid_ounces.to_gallons(100.5), places=1)
		self.assertAlmostEqual(0.00585474, units.volume.u_s_fluid_ounces.to_gallons(0.9), places=1)

	def test_convert_known_u_s_fluid_ounces_to_fluid_ounces(self):
		self.assertAlmostEqual(0.624506, units.volume.u_s_fluid_ounces.to_fluid_ounces(0.6), places=1)
		self.assertAlmostEqual(128.024, units.volume.u_s_fluid_ounces.to_fluid_ounces(123.0), places=1)
		self.assertAlmostEqual(8336.109, units.volume.u_s_fluid_ounces.to_fluid_ounces(8009.0), places=1)

	def test_convert_known_u_s_fluid_ounces_to_u_s_teaspoons(self):
		self.assertAlmostEqual(270.0, units.volume.u_s_fluid_ounces.to_u_s_teaspoons(45.0), places=1)
		self.assertAlmostEqual(9.0, units.volume.u_s_fluid_ounces.to_u_s_teaspoons(1.5), places=1)
		self.assertAlmostEqual(2404.8008, units.volume.u_s_fluid_ounces.to_u_s_teaspoons(400.8), places=1)

	def test_convert_known_u_s_fluid_ounces_to_u_s_tablespoons(self):
		self.assertAlmostEqual(8.0, units.volume.u_s_fluid_ounces.to_u_s_tablespoons(4.0), places=1)
		self.assertAlmostEqual(340.4, units.volume.u_s_fluid_ounces.to_u_s_tablespoons(170.2), places=1)
		self.assertAlmostEqual(17622.0, units.volume.u_s_fluid_ounces.to_u_s_tablespoons(8811.0), places=1)

	def test_convert_known_u_s_fluid_ounces_to_u_s_quarts(self):
		self.assertAlmostEqual(275.3438, units.volume.u_s_fluid_ounces.to_u_s_quarts(8811.0), places=1)
		self.assertAlmostEqual(0.13125, units.volume.u_s_fluid_ounces.to_u_s_quarts(4.2), places=1)
		self.assertAlmostEqual(3.40625, units.volume.u_s_fluid_ounces.to_u_s_quarts(109.0), places=1)

	def test_convert_known_u_s_fluid_ounces_to_u_s_pints(self):
		self.assertAlmostEqual(6.8125, units.volume.u_s_fluid_ounces.to_u_s_pints(109.0), places=1)
		self.assertAlmostEqual(4.818125, units.volume.u_s_fluid_ounces.to_u_s_pints(77.09), places=1)
		self.assertAlmostEqual(11.275, units.volume.u_s_fluid_ounces.to_u_s_pints(180.4), places=1)

	def test_convert_known_u_s_fluid_ounces_to_u_s_gallons(self):
		self.assertAlmostEqual(0.351563, units.volume.u_s_fluid_ounces.to_u_s_gallons(45.0), places=1)
		self.assertAlmostEqual(0.0140625, units.volume.u_s_fluid_ounces.to_u_s_gallons(1.8), places=1)
		self.assertAlmostEqual(6.0851562, units.volume.u_s_fluid_ounces.to_u_s_gallons(778.9), places=1)

	def test_convert_known_u_s_fluid_ounces_to_u_s_cups(self):
		self.assertAlmostEqual(5.625, units.volume.u_s_fluid_ounces.to_u_s_cups(45.0), places=1)
		self.assertAlmostEqual(8.3625, units.volume.u_s_fluid_ounces.to_u_s_cups(66.9), places=1)
		self.assertAlmostEqual(0.03625, units.volume.u_s_fluid_ounces.to_u_s_cups(0.29), places=1)

	def test_convert_known_u_s_fluid_ounces_to_cubic_metres(self):
		self.assertAlmostEqual(23.6854398, units.volume.u_s_fluid_ounces.to_cubic_metres(800900.0), places=1)
		self.assertAlmostEqual(0.0233335, units.volume.u_s_fluid_ounces.to_cubic_metres(789.0), places=1)
		self.assertAlmostEqual(2.96031031, units.volume.u_s_fluid_ounces.to_cubic_metres(100100.0), places=1)

	def test_convert_known_u_s_fluid_ounces_to_cubic_feet(self):
		self.assertAlmostEqual(0.359266, units.volume.u_s_fluid_ounces.to_cubic_feet(344.0), places=1)
		self.assertAlmostEqual(8.364434, units.volume.u_s_fluid_ounces.to_cubic_feet(8009.0), places=1)
		self.assertAlmostEqual(4.0, units.volume.u_s_fluid_ounces.to_cubic_feet(3830.03), places=1)

	def test_convert_known_u_s_fluid_ounces_to_cubic_inches(self):
		self.assertAlmostEqual(119.109, units.volume.u_s_fluid_ounces.to_cubic_inches(66.0), places=1)
		self.assertAlmostEqual(1624.22, units.volume.u_s_fluid_ounces.to_cubic_inches(900.0), places=1)
		self.assertAlmostEqual(14.4375, units.volume.u_s_fluid_ounces.to_cubic_inches(8.0), places=1)

	def test_convert_known_u_s_fluid_ounces_to_oil_barrels(self):
		self.assertAlmostEqual(6.0, units.volume.u_s_fluid_ounces.to_oil_barrels(32256.0), places=1)
		self.assertAlmostEqual(0.3532366, units.volume.u_s_fluid_ounces.to_oil_barrels(1899.0), places=1)
		self.assertAlmostEqual(1.3, units.volume.u_s_fluid_ounces.to_oil_barrels(6988.8), places=1)

if __name__ == '__main__':
    unittest.main()
