# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.temperature.reaumur

class TestReaumurMethods(unittest.TestCase):

	def test_convert_known_reaumur_to_kelvin(self):
		self.assertAlmostEqual(433.15, units.temperature.reaumur.to_kelvin(128.0), places=1)
		self.assertAlmostEqual(282.4, units.temperature.reaumur.to_kelvin(7.4), places=1)
		self.assertAlmostEqual(275.025, units.temperature.reaumur.to_kelvin(1.5), places=1)

	def test_convert_known_reaumur_to_celsius(self):
		self.assertAlmostEqual(1.875, units.temperature.reaumur.to_celsius(1.5), places=1)
		self.assertAlmostEqual(29.875, units.temperature.reaumur.to_celsius(23.9), places=1)
		self.assertAlmostEqual(0.375, units.temperature.reaumur.to_celsius(0.3), places=1)

	def test_convert_known_reaumur_to_fahrenheit(self):
		self.assertAlmostEqual(32.675, units.temperature.reaumur.to_fahrenheit(0.3), places=1)
		self.assertAlmostEqual(227.75, units.temperature.reaumur.to_fahrenheit(87.0), places=1)
		self.assertAlmostEqual(108.725, units.temperature.reaumur.to_fahrenheit(34.1), places=1)

	def test_convert_known_reaumur_to_rankine(self):
		self.assertAlmostEqual(568.395, units.temperature.reaumur.to_rankine(34.1), places=1)
		self.assertAlmostEqual(515.52, units.temperature.reaumur.to_rankine(10.6), places=1)
		self.assertAlmostEqual(495.945, units.temperature.reaumur.to_rankine(1.9), places=1)

if __name__ == '__main__':
    unittest.main()
