# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.length.kilometres

class TestKilometresMethods(unittest.TestCase):

	def test_convert_known_kilometres_to_millimetres(self):
		self.assertAlmostEqual(90000.0, units.length.kilometres.to_millimetres(0.09), places=1)
		self.assertAlmostEqual(120000.0, units.length.kilometres.to_millimetres(0.12), places=1)
		self.assertAlmostEqual(2.3e+6, units.length.kilometres.to_millimetres(2.3), places=1)

	def test_convert_known_kilometres_to_centimetres(self):
		self.assertAlmostEqual(790000.0, units.length.kilometres.to_centimetres(7.9), places=1)
		self.assertAlmostEqual(20000.0, units.length.kilometres.to_centimetres(0.2), places=1)
		self.assertAlmostEqual(9000.0, units.length.kilometres.to_centimetres(0.09), places=1)

	def test_convert_known_kilometres_to_metres(self):
		self.assertAlmostEqual(800.0, units.length.kilometres.to_metres(0.8), places=1)
		self.assertAlmostEqual(45000.0, units.length.kilometres.to_metres(45.0), places=1)
		self.assertAlmostEqual(1200.0, units.length.kilometres.to_metres(1.2), places=1)

	def test_convert_known_kilometres_to_inches(self):
		self.assertAlmostEqual(47244.094488, units.length.kilometres.to_inches(1.2), places=1)
		self.assertAlmostEqual(25590.551181, units.length.kilometres.to_inches(0.65), places=1)
		self.assertAlmostEqual(196850.3937, units.length.kilometres.to_inches(5.0), places=1)

	def test_convert_known_kilometres_to_feet(self):
		self.assertAlmostEqual(12467.2, units.length.kilometres.to_feet(3.8), places=1)
		self.assertAlmostEqual(3937.01, units.length.kilometres.to_feet(1.2), places=1)
		self.assertAlmostEqual(2132.546, units.length.kilometres.to_feet(0.65), places=1)

	def test_convert_known_kilometres_to_yards(self):
		self.assertAlmostEqual(87.48906, units.length.kilometres.to_yards(0.08), places=1)
		self.assertAlmostEqual(1312.34, units.length.kilometres.to_yards(1.2), places=1)
		self.assertAlmostEqual(37182.852143, units.length.kilometres.to_yards(34.0), places=1)

	def test_convert_known_kilometres_to_miles(self):
		self.assertAlmostEqual(7.45645, units.length.kilometres.to_miles(12.0), places=1)
		self.assertAlmostEqual(0.559234, units.length.kilometres.to_miles(0.9), places=1)
		self.assertAlmostEqual(2.42335, units.length.kilometres.to_miles(3.9), places=1)

	def test_convert_known_kilometres_to_nautical_miles(self):
		self.assertAlmostEqual(0.647948, units.length.kilometres.to_nautical_miles(1.2), places=1)
		self.assertAlmostEqual(0.107991, units.length.kilometres.to_nautical_miles(0.2), places=1)
		self.assertAlmostEqual(53.94168, units.length.kilometres.to_nautical_miles(99.9), places=1)

if __name__ == '__main__':
    unittest.main()
