# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.speed.metres_per_second

class TestMetresPerSecondMethods(unittest.TestCase):

	def test_convert_known_metres_per_second_to_miles_per_hour(self):
		self.assertAlmostEqual(29.0802, units.speed.metres_per_second.to_miles_per_hour(13.0), places=1)
		self.assertAlmostEqual(14.9875, units.speed.metres_per_second.to_miles_per_hour(6.7), places=1)
		self.assertAlmostEqual(313.171, units.speed.metres_per_second.to_miles_per_hour(140.0), places=1)

	def test_convert_known_metres_per_second_to_kilometres_per_hour(self):
		self.assertAlmostEqual(2880.0, units.speed.metres_per_second.to_kilometres_per_hour(800.0), places=1)
		self.assertAlmostEqual(28.08, units.speed.metres_per_second.to_kilometres_per_hour(7.8), places=1)
		self.assertAlmostEqual(32400.0, units.speed.metres_per_second.to_kilometres_per_hour(9000.0), places=1)

	def test_convert_known_metres_per_second_to_feet_per_second(self):
		self.assertAlmostEqual(29527.56, units.speed.metres_per_second.to_feet_per_second(9000.0), places=1)
		self.assertAlmostEqual(11.1549, units.speed.metres_per_second.to_feet_per_second(3.4), places=1)
		self.assertAlmostEqual(39.3701, units.speed.metres_per_second.to_feet_per_second(12.0), places=1)

	def test_convert_known_metres_per_second_to_knots(self):
		self.assertAlmostEqual(23.3261, units.speed.metres_per_second.to_knots(12.0), places=1)
		self.assertAlmostEqual(12.2462, units.speed.metres_per_second.to_knots(6.3), places=1)
		self.assertAlmostEqual(17.4946, units.speed.metres_per_second.to_knots(9.0), places=1)

if __name__ == '__main__':
    unittest.main()
