# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.area.square_inches

class TestSquareInchesMethods(unittest.TestCase):

	def test_convert_known_square_inches_to_square_kilometres(self):
		self.assertAlmostEqual(0.437999124, units.area.square_inches.to_square_kilometres(678900000.0), places=1)
		self.assertAlmostEqual(6.4516, units.area.square_inches.to_square_kilometres(10000000000.0), places=1)
		self.assertAlmostEqual(5806.44, units.area.square_inches.to_square_kilometres(9e12), places=1)

	def test_convert_known_square_inches_to_square_metres(self):
		self.assertAlmostEqual(0.7032244, units.area.square_inches.to_square_metres(1090.0), places=1)
		self.assertAlmostEqual(838.708, units.area.square_inches.to_square_metres(1.3e6), places=1)
		self.assertAlmostEqual(6.443858, units.area.square_inches.to_square_metres(9988.0), places=1)

	def test_convert_known_square_inches_to_square_miles(self):
		self.assertAlmostEqual(0.2508433450668, units.area.square_inches.to_square_miles(1007008000.0), places=1)
		self.assertAlmostEqual(298.9172023262932, units.area.square_inches.to_square_miles(1.2e12), places=1)
		self.assertAlmostEqual(0.6227441715131, units.area.square_inches.to_square_miles(250e7), places=1)

	def test_convert_known_square_inches_to_square_yards(self):
		self.assertAlmostEqual(0.694444, units.area.square_inches.to_square_yards(900.0), places=1)
		self.assertAlmostEqual(11.574074, units.area.square_inches.to_square_yards(15000.0), places=1)
		self.assertAlmostEqual(2314.814815, units.area.square_inches.to_square_yards(3e6), places=1)

	def test_convert_known_square_inches_to_square_feet(self):
		self.assertAlmostEqual(0.236111, units.area.square_inches.to_square_feet(34.0), places=1)
		self.assertAlmostEqual(6.958333, units.area.square_inches.to_square_feet(1002.0), places=1)
		self.assertAlmostEqual(6.18056, units.area.square_inches.to_square_feet(890.0), places=1)

	def test_convert_known_square_inches_to_hectares(self):
		self.assertAlmostEqual(0.580644, units.area.square_inches.to_hectares(9000000.0), places=1)
		self.assertAlmostEqual(0.79649376185, units.area.square_inches.to_hectares(12345678.0), places=1)
		self.assertAlmostEqual(6.4443591113, units.area.square_inches.to_hectares(99887766.0), places=1)

	def test_convert_known_square_inches_to_acres(self):
		self.assertAlmostEqual(0.143496199, units.area.square_inches.to_acres(900100.0), places=1)
		self.assertAlmostEqual(0.7971125395, units.area.square_inches.to_acres(5e6), places=1)
		self.assertAlmostEqual(1.9681789486, units.area.square_inches.to_acres(12345678.0), places=1)

if __name__ == '__main__':
    unittest.main()
