# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.power.metric_horse_power

class TestMetricHorsePowerMethods(unittest.TestCase):

	def test_convert_known_metric_horse_power_to_mechanical_horse_power(self):
		self.assertAlmostEqual(125.0, units.power.metric_horse_power.to_mechanical_horse_power(126.734), places=1)
		self.assertAlmostEqual(90.0, units.power.metric_horse_power.to_mechanical_horse_power(91.2483), places=1)
		self.assertAlmostEqual(419.9997, units.power.metric_horse_power.to_mechanical_horse_power(425.825), places=1)

if __name__ == '__main__':
    unittest.main()
