# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.length.centimetres

class TestCentimetresMethods(unittest.TestCase):

	def test_convert_known_centimetres_to_millimetres(self):
		self.assertAlmostEqual(9000.0, units.length.centimetres.to_millimetres(900.0), places=1)
		self.assertAlmostEqual(349.0, units.length.centimetres.to_millimetres(34.9), places=1)
		self.assertAlmostEqual(20.0, units.length.centimetres.to_millimetres(2.0), places=1)

	def test_convert_known_centimetres_to_metres(self):
		self.assertAlmostEqual(0.13, units.length.centimetres.to_metres(13.0), places=1)
		self.assertAlmostEqual(39.0, units.length.centimetres.to_metres(3900.0), places=1)
		self.assertAlmostEqual(0.01, units.length.centimetres.to_metres(1.0), places=1)

	def test_convert_known_centimetres_to_kilometres(self):
		self.assertAlmostEqual(1.23456, units.length.centimetres.to_kilometres(123456.0), places=1)
		self.assertAlmostEqual(0.089, units.length.centimetres.to_kilometres(8900.0), places=1)
		self.assertAlmostEqual(60.09, units.length.centimetres.to_kilometres(6009000.0), places=1)

	def test_convert_known_centimetres_to_inches(self):
		self.assertAlmostEqual(236.22, units.length.centimetres.to_inches(600.0), places=1)
		self.assertAlmostEqual(4.72441, units.length.centimetres.to_inches(12.0), places=1)
		self.assertAlmostEqual(3.07087, units.length.centimetres.to_inches(7.8), places=1)

	def test_convert_known_centimetres_to_feet(self):
		self.assertAlmostEqual(0.4035433, units.length.centimetres.to_feet(12.3), places=1)
		self.assertAlmostEqual(2.91995, units.length.centimetres.to_feet(89.0), places=1)
		self.assertAlmostEqual(0.0229659, units.length.centimetres.to_feet(0.7), places=1)

	def test_convert_known_centimetres_to_yards(self):
		self.assertAlmostEqual(7.65529, units.length.centimetres.to_yards(700.0), places=1)
		self.assertAlmostEqual(0.6157043, units.length.centimetres.to_yards(56.3), places=1)
		self.assertAlmostEqual(0.0874891, units.length.centimetres.to_yards(8.0), places=1)

	def test_convert_known_centimetres_to_miles(self):
		self.assertAlmostEqual(0.49709695, units.length.centimetres.to_miles(80000.0), places=1)
		self.assertAlmostEqual(0.767120019, units.length.centimetres.to_miles(123456.0), places=1)
		self.assertAlmostEqual(564.88289639, units.length.centimetres.to_miles(90909090.0), places=1)

	def test_convert_known_centimetres_to_nautical_miles(self):
		self.assertAlmostEqual(0.16198704, units.length.centimetres.to_nautical_miles(30000.0), places=1)
		self.assertAlmostEqual(5.33290497, units.length.centimetres.to_nautical_miles(987654.0), places=1)
		self.assertAlmostEqual(0.541036717, units.length.centimetres.to_nautical_miles(100200.0), places=1)

if __name__ == '__main__':
    unittest.main()
