# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.data_storage.kilobytes

class TestKilobytesMethods(unittest.TestCase):

	def test_convert_known_kilobytes_to_bits(self):
		self.assertAlmostEqual(987648.0, units.data_storage.kilobytes.to_bits(123.456), places=1)
		self.assertAlmostEqual(7.2e+6, units.data_storage.kilobytes.to_bits(900.0), places=1)
		self.assertAlmostEqual(801600000.0, units.data_storage.kilobytes.to_bits(100200.0), places=1)

	def test_convert_known_kilobytes_to_kilobits(self):
		self.assertAlmostEqual(32.0, units.data_storage.kilobytes.to_kilobits(4.0), places=1)
		self.assertAlmostEqual(9.6, units.data_storage.kilobytes.to_kilobits(1.2), places=1)
		self.assertAlmostEqual(704.8, units.data_storage.kilobytes.to_kilobits(88.1), places=1)

	def test_convert_known_kilobytes_to_megabits(self):
		self.assertAlmostEqual(0.7048, units.data_storage.kilobytes.to_megabits(88.1), places=1)
		self.assertAlmostEqual(0.0568, units.data_storage.kilobytes.to_megabits(7.1), places=1)
		self.assertAlmostEqual(0.1024, units.data_storage.kilobytes.to_megabits(12.8), places=1)

	def test_convert_known_kilobytes_to_gigabits(self):
		self.assertAlmostEqual(0.08064, units.data_storage.kilobytes.to_gigabits(10080.0), places=1)
		self.assertAlmostEqual(36000.0, units.data_storage.kilobytes.to_gigabits(4.5e+9), places=1)
		self.assertAlmostEqual(2.170232, units.data_storage.kilobytes.to_gigabits(271279.0), places=1)

	def test_convert_known_kilobytes_to_terabits(self):
		self.assertAlmostEqual(0.072072, units.data_storage.kilobytes.to_terabits(9009000.0), places=1)
		self.assertAlmostEqual(57.6, units.data_storage.kilobytes.to_terabits(7.2e9), places=1)
		self.assertAlmostEqual(800.8008072, units.data_storage.kilobytes.to_terabits(100100100900.0), places=1)

	def test_convert_known_kilobytes_to_megabytes(self):
		self.assertAlmostEqual(1.009, units.data_storage.kilobytes.to_megabytes(1009.0), places=1)
		self.assertAlmostEqual(8.899, units.data_storage.kilobytes.to_megabytes(8899.0), places=1)
		self.assertAlmostEqual(0.619, units.data_storage.kilobytes.to_megabytes(619.0), places=1)

	def test_convert_known_kilobytes_to_gigabytes(self):
		self.assertAlmostEqual(0.9008, units.data_storage.kilobytes.to_gigabytes(900800.0), places=1)
		self.assertAlmostEqual(1.234567, units.data_storage.kilobytes.to_gigabytes(1234567.0), places=1)
		self.assertAlmostEqual(7900.0, units.data_storage.kilobytes.to_gigabytes(7.9e9), places=1)

	def test_convert_known_kilobytes_to_terabytes(self):
		self.assertAlmostEqual(9e-10, units.data_storage.kilobytes.to_terabytes(0.9), places=1)
		self.assertAlmostEqual(0.14, units.data_storage.kilobytes.to_terabytes(140000000.0), places=1)
		self.assertAlmostEqual(7e-9, units.data_storage.kilobytes.to_terabytes(7.0), places=1)

	def test_convert_known_kilobytes_to_kibibits(self):
		self.assertAlmostEqual(0.0703125, units.data_storage.kilobytes.to_kibibits(0.009), places=1)
		self.assertAlmostEqual(46875.0, units.data_storage.kilobytes.to_kibibits(6e+3), places=1)
		self.assertAlmostEqual(9.609375, units.data_storage.kilobytes.to_kibibits(1.23), places=1)

	def test_convert_known_kilobytes_to_mebibits(self):
		self.assertAlmostEqual(0.534058, units.data_storage.kilobytes.to_mebibits(70.0), places=1)
		self.assertAlmostEqual(0.0686646, units.data_storage.kilobytes.to_mebibits(9.0), places=1)
		self.assertAlmostEqual(76.461792, units.data_storage.kilobytes.to_mebibits(10022.0), places=1)

if __name__ == '__main__':
    unittest.main()
