# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.energy.kilojoules

class TestKilojoulesMethods(unittest.TestCase):

	def test_convert_known_kilojoules_to_kilocalories(self):
		self.assertAlmostEqual(47.5621, units.energy.kilojoules.to_kilocalories(199.0), places=1)
		self.assertAlmostEqual(0.1601338, units.energy.kilojoules.to_kilocalories(0.67), places=1)
		self.assertAlmostEqual(1.12333, units.energy.kilojoules.to_kilocalories(4.7), places=1)

	def test_convert_known_kilojoules_to_joules(self):
		self.assertAlmostEqual(4700.0, units.energy.kilojoules.to_joules(4.7), places=1)
		self.assertAlmostEqual(7800.0, units.energy.kilojoules.to_joules(7.8), places=1)
		self.assertAlmostEqual(1800000.0, units.energy.kilojoules.to_joules(1800.0), places=1)

	def test_convert_known_kilojoules_to_btu(self):
		self.assertAlmostEqual(1706.070, units.energy.kilojoules.to_btu(1800.0), places=1)
		self.assertAlmostEqual(1.32694, units.energy.kilojoules.to_btu(1.4), places=1)
		self.assertAlmostEqual(84.54529, units.energy.kilojoules.to_btu(89.2), places=1)

	def test_convert_known_kilojoules_to_calories(self):
		self.assertAlmostEqual(16013.381899, units.energy.kilojoules.to_calories(67.0), places=1)
		self.assertAlmostEqual(334.608, units.energy.kilojoules.to_calories(1.4), places=1)
		self.assertAlmostEqual(20793.5, units.energy.kilojoules.to_calories(87.0), places=1)

	def test_convert_known_kilojoules_to_u_s_therms(self):
		self.assertAlmostEqual(1.17041649, units.energy.kilojoules.to_u_s_therms(123456.0), places=1)
		self.assertAlmostEqual(0.83427822, units.energy.kilojoules.to_u_s_therms(88000.0), places=1)
		self.assertAlmostEqual(0.08532391, units.energy.kilojoules.to_u_s_therms(9000.0), places=1)

	def test_convert_known_kilojoules_to_watt_hours(self):
		self.assertAlmostEqual(27222.222, units.energy.kilojoules.to_watt_hours(98000.0), places=1)
		self.assertAlmostEqual(0.416667, units.energy.kilojoules.to_watt_hours(1.5), places=1)
		self.assertAlmostEqual(18.86111, units.energy.kilojoules.to_watt_hours(67.9), places=1)

	def test_convert_known_kilojoules_to_kilowatt_hours(self):
		self.assertAlmostEqual(2.222222, units.energy.kilojoules.to_kilowatt_hours(8000.0), places=1)
		self.assertAlmostEqual(0.018886111, units.energy.kilojoules.to_kilowatt_hours(67.99), places=1)
		self.assertAlmostEqual(0.113, units.energy.kilojoules.to_kilowatt_hours(406.8), places=1)

	def test_convert_known_kilojoules_to_foot_pounds(self):
		self.assertAlmostEqual(74420.00579, units.energy.kilojoules.to_foot_pounds(100.9), places=1)
		self.assertAlmostEqual(1770.15, units.energy.kilojoules.to_foot_pounds(2.4), places=1)
		self.assertAlmostEqual(663.806, units.energy.kilojoules.to_foot_pounds(0.9), places=1)

	def test_convert_known_kilojoules_to_electronvolts(self):
		self.assertAlmostEqual(6235268234766989.0, units.energy.kilojoules.to_electronvolts(0.000000999), places=1)
		self.assertAlmostEqual(1248301948902300.0, units.energy.kilojoules.to_electronvolts(0.0000002), places=1)
		self.assertAlmostEqual(3.5389360251380204E+19, units.energy.kilojoules.to_electronvolts(0.00567), places=1)

if __name__ == '__main__':
    unittest.main()
