# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.length.metres

class TestMetresMethods(unittest.TestCase):

	def test_convert_known_metres_to_millimetres(self):
		self.assertAlmostEqual(123000.0, units.length.metres.to_millimetres(123.0), places=1)
		self.assertAlmostEqual(900.0, units.length.metres.to_millimetres(0.9), places=1)
		self.assertAlmostEqual(2.3, units.length.metres.to_millimetres(0.0023), places=1)

	def test_convert_known_metres_to_centimetres(self):
		self.assertAlmostEqual(230.0, units.length.metres.to_centimetres(2.3), places=1)
		self.assertAlmostEqual(3400.0, units.length.metres.to_centimetres(34.0), places=1)
		self.assertAlmostEqual(90.0, units.length.metres.to_centimetres(0.9), places=1)

	def test_convert_known_metres_to_kilometres(self):
		self.assertAlmostEqual(0.1, units.length.metres.to_kilometres(100.0), places=1)
		self.assertAlmostEqual(123.456, units.length.metres.to_kilometres(123456.0), places=1)
		self.assertAlmostEqual(0.0911, units.length.metres.to_kilometres(91.1), places=1)

	def test_convert_known_metres_to_inches(self):
		self.assertAlmostEqual(472.441, units.length.metres.to_inches(12.0), places=1)
		self.assertAlmostEqual(366.142, units.length.metres.to_inches(9.3), places=1)
		self.assertAlmostEqual(3.93701, units.length.metres.to_inches(0.1), places=1)

	def test_convert_known_metres_to_feet(self):
		self.assertAlmostEqual(219.816, units.length.metres.to_feet(67.0), places=1)
		self.assertAlmostEqual(3.93701, units.length.metres.to_feet(1.2), places=1)
		self.assertAlmostEqual(2.29659, units.length.metres.to_feet(0.7), places=1)

	def test_convert_known_metres_to_yards(self):
		self.assertAlmostEqual(0.874891, units.length.metres.to_yards(0.8), places=1)
		self.assertAlmostEqual(37.72966, units.length.metres.to_yards(34.5), places=1)
		self.assertAlmostEqual(1.345144, units.length.metres.to_yards(1.23), places=1)

	def test_convert_known_metres_to_miles(self):
		self.assertAlmostEqual(4.908832, units.length.metres.to_miles(7900.0), places=1)
		self.assertAlmostEqual(76.7120019, units.length.metres.to_miles(123456.0), places=1)
		self.assertAlmostEqual(0.621371, units.length.metres.to_miles(1000.0), places=1)

	def test_convert_known_metres_to_nautical_miles(self):
		self.assertAlmostEqual(0.485961, units.length.metres.to_nautical_miles(900.0), places=1)
		self.assertAlmostEqual(38.779158, units.length.metres.to_nautical_miles(71819.0), places=1)
		self.assertAlmostEqual(66.6609071, units.length.metres.to_nautical_miles(123456.0), places=1)

if __name__ == '__main__':
    unittest.main()
