# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.data_storage.kilobits

class TestKilobitsMethods(unittest.TestCase):

	def test_convert_known_kilobits_to_bits(self):
		self.assertAlmostEqual(9000.0, units.data_storage.kilobits.to_bits(9.0), places=1)
		self.assertAlmostEqual(6700.0, units.data_storage.kilobits.to_bits(6.7), places=1)
		self.assertAlmostEqual(1234.5, units.data_storage.kilobits.to_bits(1.2345), places=1)

	def test_convert_known_kilobits_to_megabits(self):
		self.assertAlmostEqual(0.9, units.data_storage.kilobits.to_megabits(900.0), places=1)
		self.assertAlmostEqual(12.345, units.data_storage.kilobits.to_megabits(12345.0), places=1)
		self.assertAlmostEqual(9.988, units.data_storage.kilobits.to_megabits(9988.0), places=1)

	def test_convert_known_kilobits_to_gigabits(self):
		self.assertAlmostEqual(0.123456, units.data_storage.kilobits.to_gigabits(123456.0), places=1)
		self.assertAlmostEqual(8.0007, units.data_storage.kilobits.to_gigabits(8000700.0), places=1)
		self.assertAlmostEqual(191.987578, units.data_storage.kilobits.to_gigabits(191987578.0), places=1)

	def test_convert_known_kilobits_to_terabits(self):
		self.assertAlmostEqual(0.191987578, units.data_storage.kilobits.to_terabits(191987578.0), places=1)
		self.assertAlmostEqual(9.010081903, units.data_storage.kilobits.to_terabits(9010081903.0), places=1)
		self.assertAlmostEqual(0.123456789, units.data_storage.kilobits.to_terabits(123456789.0), places=1)

	def test_convert_known_kilobits_to_kilobytes(self):
		self.assertAlmostEqual(10.0, units.data_storage.kilobits.to_kilobytes(80.0), places=1)
		self.assertAlmostEqual(1.95875, units.data_storage.kilobits.to_kilobytes(15.67), places=1)
		self.assertAlmostEqual(1000.88625, units.data_storage.kilobits.to_kilobytes(8007.09), places=1)

	def test_convert_known_kilobits_to_megabytes(self):
		self.assertAlmostEqual(15.432, units.data_storage.kilobits.to_megabytes(123456.0), places=1)
		self.assertAlmostEqual(124.859625, units.data_storage.kilobits.to_megabytes(998877.0), places=1)
		self.assertAlmostEqual(1.26125, units.data_storage.kilobits.to_megabytes(10090.0), places=1)

	def test_convert_known_kilobits_to_gigabytes(self):
		self.assertAlmostEqual(0.2286215, units.data_storage.kilobits.to_gigabytes(1828972.0), places=1)
		self.assertAlmostEqual(0.1099826, units.data_storage.kilobits.to_gigabytes(879860.8), places=1)
		self.assertAlmostEqual(9.772371375, units.data_storage.kilobits.to_gigabytes(78178971.0), places=1)

	def test_convert_known_kilobits_to_terabytes(self):
		self.assertAlmostEqual(0.154320986375, units.data_storage.kilobits.to_terabytes(1234567891.0), places=1)
		self.assertAlmostEqual(0.12499988725, units.data_storage.kilobits.to_terabytes(999999098.0), places=1)
		self.assertAlmostEqual(10.57729551775, units.data_storage.kilobits.to_terabytes(84618364142.0), places=1)

	def test_convert_known_kilobits_to_kibibits(self):
		self.assertAlmostEqual(87.01172, units.data_storage.kilobits.to_kibibits(89.1), places=1)
		self.assertAlmostEqual(6.93359, units.data_storage.kilobits.to_kibibits(7.1), places=1)
		self.assertAlmostEqual(427.734, units.data_storage.kilobits.to_kibibits(438.0), places=1)

	def test_convert_known_kilobits_to_mebibits(self):
		self.assertAlmostEqual(74.186325, units.data_storage.kilobits.to_mebibits(77790.0), places=1)
		self.assertAlmostEqual(117.736816, units.data_storage.kilobits.to_mebibits(123456.0), places=1)
		self.assertAlmostEqual(22.861481, units.data_storage.kilobits.to_mebibits(23972.0), places=1)

if __name__ == '__main__':
    unittest.main()
