# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.mass.kilograms

class TestKilogramsMethods(unittest.TestCase):

	def test_convert_known_kilograms_to_milligrams(self):
		self.assertAlmostEqual(900000.0, units.mass.kilograms.to_milligrams(0.9), places=1)
		self.assertAlmostEqual(560000.0, units.mass.kilograms.to_milligrams(0.56), places=1)
		self.assertAlmostEqual(7000.0, units.mass.kilograms.to_milligrams(0.007), places=1)

	def test_convert_known_kilograms_to_grams(self):
		self.assertAlmostEqual(800.0, units.mass.kilograms.to_grams(0.8), places=1)
		self.assertAlmostEqual(12000.0, units.mass.kilograms.to_grams(12.0), places=1)
		self.assertAlmostEqual(200.0, units.mass.kilograms.to_grams(0.2), places=1)

	def test_convert_known_kilograms_to_tonnes(self):
		self.assertAlmostEqual(0.123, units.mass.kilograms.to_tonnes(123.0), places=1)
		self.assertAlmostEqual(9.0, units.mass.kilograms.to_tonnes(9000.0), places=1)
		self.assertAlmostEqual(2.3, units.mass.kilograms.to_tonnes(2300.0), places=1)

	def test_convert_known_kilograms_to_ounces(self):
		self.assertAlmostEqual(81130.19, units.mass.kilograms.to_ounces(2300.0), places=1)
		self.assertAlmostEqual(423.288, units.mass.kilograms.to_ounces(12.0), places=1)
		self.assertAlmostEqual(119.931, units.mass.kilograms.to_ounces(3.4), places=1)

	def test_convert_known_kilograms_to_pounds(self):
		self.assertAlmostEqual(7.49572, units.mass.kilograms.to_pounds(3.4), places=1)
		self.assertAlmostEqual(1.98416, units.mass.kilograms.to_pounds(0.9), places=1)
		self.assertAlmostEqual(6.61387, units.mass.kilograms.to_pounds(3.0), places=1)

	def test_convert_known_kilograms_to_stones(self):
		self.assertAlmostEqual(0.472419, units.mass.kilograms.to_stones(3.0), places=1)
		self.assertAlmostEqual(15.4324, units.mass.kilograms.to_stones(98.0), places=1)
		self.assertAlmostEqual(0.188968, units.mass.kilograms.to_stones(1.2), places=1)

	def test_convert_known_kilograms_to_carats(self):
		self.assertAlmostEqual(500.0, units.mass.kilograms.to_carats(0.1), places=1)
		self.assertAlmostEqual(400.0, units.mass.kilograms.to_carats(0.08), places=1)
		self.assertAlmostEqual(10000.0, units.mass.kilograms.to_carats(2.0), places=1)

if __name__ == '__main__':
    unittest.main()
