# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.volume.oil_barrels

class TestOilBarrelsMethods(unittest.TestCase):

	def test_convert_known_oil_barrels_to_millilitres(self):
		self.assertAlmostEqual(127189.6, units.volume.oil_barrels.to_millilitres(0.8), places=1)
		self.assertAlmostEqual(953922.0, units.volume.oil_barrels.to_millilitres(6.0), places=1)
		self.assertAlmostEqual(9998.981786, units.volume.oil_barrels.to_millilitres(0.06289182), places=1)

	def test_convert_known_oil_barrels_to_litres(self):
		self.assertAlmostEqual(1907.85, units.volume.oil_barrels.to_litres(12.0), places=1)
		self.assertAlmostEqual(953.924, units.volume.oil_barrels.to_litres(6.0), places=1)
		self.assertAlmostEqual(12242.0, units.volume.oil_barrels.to_litres(77.0), places=1)

	def test_convert_known_oil_barrels_to_kilolitres(self):
		self.assertAlmostEqual(1.90785, units.volume.oil_barrels.to_kilolitres(12.0), places=1)
		self.assertAlmostEqual(1.2719, units.volume.oil_barrels.to_kilolitres(8.0), places=1)
		self.assertAlmostEqual(12.242, units.volume.oil_barrels.to_kilolitres(77.0), places=1)

	def test_convert_known_oil_barrels_to_teaspoons(self):
		self.assertAlmostEqual(16115.219, units.volume.oil_barrels.to_teaspoons(0.6), places=1)
		self.assertAlmostEqual(107434.8, units.volume.oil_barrels.to_teaspoons(4.0), places=1)
		self.assertAlmostEqual(179953.29, units.volume.oil_barrels.to_teaspoons(6.7), places=1)

	def test_convert_known_oil_barrels_to_tablespoons(self):
		self.assertAlmostEqual(6267.04, units.volume.oil_barrels.to_tablespoons(0.7), places=1)
		self.assertAlmostEqual(71623.279, units.volume.oil_barrels.to_tablespoons(8.0), places=1)
		self.assertAlmostEqual(89999.011387, units.volume.oil_barrels.to_tablespoons(10.052487), places=1)

	def test_convert_known_oil_barrels_to_quarts(self):
		self.assertAlmostEqual(12310.232, units.volume.oil_barrels.to_quarts(88.0), places=1)
		self.assertAlmostEqual(1678.67, units.volume.oil_barrels.to_quarts(12.0), places=1)
		self.assertAlmostEqual(839.336, units.volume.oil_barrels.to_quarts(6.0), places=1)

	def test_convert_known_oil_barrels_to_pints(self):
		self.assertAlmostEqual(2238.23, units.volume.oil_barrels.to_pints(8.0), places=1)
		self.assertAlmostEqual(1678.67, units.volume.oil_barrels.to_pints(6.0), places=1)
		self.assertAlmostEqual(77.0, units.volume.oil_barrels.to_pints(0.275218), places=1)

	def test_convert_known_oil_barrels_to_gallons(self):
		self.assertAlmostEqual(139.889, units.volume.oil_barrels.to_gallons(4.0), places=1)
		self.assertAlmostEqual(209.834, units.volume.oil_barrels.to_gallons(6.0), places=1)
		self.assertAlmostEqual(629.502, units.volume.oil_barrels.to_gallons(18.0), places=1)

	def test_convert_known_oil_barrels_to_fluid_ounces(self):
		self.assertAlmostEqual(2797.79, units.volume.oil_barrels.to_fluid_ounces(0.5), places=1)
		self.assertAlmostEqual(33573.4199, units.volume.oil_barrels.to_fluid_ounces(6.0), places=1)
		self.assertAlmostEqual(430858.889, units.volume.oil_barrels.to_fluid_ounces(77.0), places=1)

	def test_convert_known_oil_barrels_to_u_s_teaspoons(self):
		self.assertAlmostEqual(9676.8, units.volume.oil_barrels.to_u_s_teaspoons(0.3), places=1)
		self.assertAlmostEqual(225792.0, units.volume.oil_barrels.to_u_s_teaspoons(7.0), places=1)
		self.assertAlmostEqual(48384.0, units.volume.oil_barrels.to_u_s_teaspoons(1.5), places=1)

	def test_convert_known_oil_barrels_to_u_s_tablespoons(self):
		self.assertAlmostEqual(2150.4, units.volume.oil_barrels.to_u_s_tablespoons(0.2), places=1)
		self.assertAlmostEqual(64512.0, units.volume.oil_barrels.to_u_s_tablespoons(6.0), places=1)
		self.assertAlmostEqual(827904.0, units.volume.oil_barrels.to_u_s_tablespoons(77.0), places=1)

	def test_convert_known_oil_barrels_to_u_s_quarts(self):
		self.assertAlmostEqual(756.0, units.volume.oil_barrels.to_u_s_quarts(4.5), places=1)
		self.assertAlmostEqual(12936.0, units.volume.oil_barrels.to_u_s_quarts(77.0), places=1)
		self.assertAlmostEqual(117.6, units.volume.oil_barrels.to_u_s_quarts(0.7), places=1)

	def test_convert_known_oil_barrels_to_u_s_pints(self):
		self.assertAlmostEqual(2620.8, units.volume.oil_barrels.to_u_s_pints(7.8), places=1)
		self.assertAlmostEqual(235.2, units.volume.oil_barrels.to_u_s_pints(0.7), places=1)
		self.assertAlmostEqual(1008.0, units.volume.oil_barrels.to_u_s_pints(3.0), places=1)

	def test_convert_known_oil_barrels_to_u_s_gallons(self):
		self.assertAlmostEqual(3276.0, units.volume.oil_barrels.to_u_s_gallons(78.0), places=1)
		self.assertAlmostEqual(126.0, units.volume.oil_barrels.to_u_s_gallons(3.0), places=1)
		self.assertAlmostEqual(32634.0, units.volume.oil_barrels.to_u_s_gallons(777.0), places=1)

	def test_convert_known_oil_barrels_to_u_s_fluid_ounces(self):
		self.assertAlmostEqual(26342.4, units.volume.oil_barrels.to_u_s_fluid_ounces(4.9), places=1)
		self.assertAlmostEqual(2150.4, units.volume.oil_barrels.to_u_s_fluid_ounces(0.4), places=1)
		self.assertAlmostEqual(16128.0, units.volume.oil_barrels.to_u_s_fluid_ounces(3.0), places=1)

	def test_convert_known_oil_barrels_to_u_s_cups(self):
		self.assertAlmostEqual(36434.5849, units.volume.oil_barrels.to_u_s_cups(55.0), places=1)
		self.assertAlmostEqual(455.0, units.volume.oil_barrels.to_u_s_cups(0.686847), places=1)
		self.assertAlmostEqual(6094.51, units.volume.oil_barrels.to_u_s_cups(9.2), places=1)

	def test_convert_known_oil_barrels_to_cubic_metres(self):
		self.assertAlmostEqual(1.1129112, units.volume.oil_barrels.to_cubic_metres(7.0), places=1)
		self.assertAlmostEqual(0.476962, units.volume.oil_barrels.to_cubic_metres(3.0), places=1)
		self.assertAlmostEqual(12.401, units.volume.oil_barrels.to_cubic_metres(78.0), places=1)

	def test_convert_known_oil_barrels_to_cubic_feet(self):
		self.assertAlmostEqual(494.083, units.volume.oil_barrels.to_cubic_feet(88.0), places=1)
		self.assertAlmostEqual(16.8438, units.volume.oil_barrels.to_cubic_feet(3.0), places=1)
		self.assertAlmostEqual(61.7604, units.volume.oil_barrels.to_cubic_feet(11.0), places=1)

	def test_convert_known_oil_barrels_to_cubic_inches(self):
		self.assertAlmostEqual(974080.8, units.volume.oil_barrels.to_cubic_inches(100.4), places=1)
		self.assertAlmostEqual(48510.0, units.volume.oil_barrels.to_cubic_inches(5.0), places=1)
		self.assertAlmostEqual(640332.0, units.volume.oil_barrels.to_cubic_inches(66.0), places=1)

if __name__ == '__main__':
    unittest.main()
