# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.volume.teaspoons

class TestTeaspoonsMethods(unittest.TestCase):

	def test_convert_known_teaspoons_to_millilitres(self):
		self.assertAlmostEqual(3.55163, units.volume.teaspoons.to_millilitres(0.6), places=1)
		self.assertAlmostEqual(7.69521, units.volume.teaspoons.to_millilitres(1.3), places=1)
		self.assertAlmostEqual(0.4143573, units.volume.teaspoons.to_millilitres(0.07), places=1)

	def test_convert_known_teaspoons_to_litres(self):
		self.assertAlmostEqual(0.18942, units.volume.teaspoons.to_litres(32.0), places=1)
		self.assertAlmostEqual(1.06549, units.volume.teaspoons.to_litres(180.0), places=1)
		self.assertAlmostEqual(27.03386, units.volume.teaspoons.to_litres(4567.0), places=1)

	def test_convert_known_teaspoons_to_kilolitres(self):
		self.assertAlmostEqual(1.4, units.volume.teaspoons.to_kilolitres(236511.0), places=1)
		self.assertAlmostEqual(0.2, units.volume.teaspoons.to_kilolitres(33787.3), places=1)
		self.assertAlmostEqual(0.01, units.volume.teaspoons.to_kilolitres(1689.363), places=1)

	def test_convert_known_teaspoons_to_tablespoons(self):
		self.assertAlmostEqual(4.0, units.volume.teaspoons.to_tablespoons(12.0), places=1)
		self.assertAlmostEqual(300.26667, units.volume.teaspoons.to_tablespoons(900.8), places=1)
		self.assertAlmostEqual(0.41, units.volume.teaspoons.to_tablespoons(1.23), places=1)

	def test_convert_known_teaspoons_to_quarts(self):
		self.assertAlmostEqual(0.567709, units.volume.teaspoons.to_quarts(109.0), places=1)
		self.assertAlmostEqual(23.43751, units.volume.teaspoons.to_quarts(4500.0), places=1)
		self.assertAlmostEqual(0.463542, units.volume.teaspoons.to_quarts(89.0), places=1)

	def test_convert_known_teaspoons_to_pints(self):
		self.assertAlmostEqual(7.0625, units.volume.teaspoons.to_pints(678.0), places=1)
		self.assertAlmostEqual(1.13542, units.volume.teaspoons.to_pints(109.0), places=1)
		self.assertAlmostEqual(0.1302084, units.volume.teaspoons.to_pints(12.5), places=1)

	def test_convert_known_teaspoons_to_gallons(self):
		self.assertAlmostEqual(0.247396, units.volume.teaspoons.to_gallons(190.0), places=1)
		self.assertAlmostEqual(10.53386, units.volume.teaspoons.to_gallons(8090.0), places=1)
		self.assertAlmostEqual(0.31106784, units.volume.teaspoons.to_gallons(238.9), places=1)

	def test_convert_known_teaspoons_to_fluid_ounces(self):
		self.assertAlmostEqual(22.7083, units.volume.teaspoons.to_fluid_ounces(109.0), places=1)
		self.assertAlmostEqual(11.60417, units.volume.teaspoons.to_fluid_ounces(55.7), places=1)
		self.assertAlmostEqual(126.875, units.volume.teaspoons.to_fluid_ounces(609.0), places=1)

	def test_convert_known_teaspoons_to_u_s_teaspoons(self):
		self.assertAlmostEqual(108.086, units.volume.teaspoons.to_u_s_teaspoons(90.0), places=1)
		self.assertAlmostEqual(1.741379, units.volume.teaspoons.to_u_s_teaspoons(1.45), places=1)
		self.assertAlmostEqual(96.19616, units.volume.teaspoons.to_u_s_teaspoons(80.1), places=1)

	def test_convert_known_teaspoons_to_u_s_tablespoons(self):
		self.assertAlmostEqual(22.4177, units.volume.teaspoons.to_u_s_tablespoons(56.0), places=1)
		self.assertAlmostEqual(2.80222, units.volume.teaspoons.to_u_s_tablespoons(7.0), places=1)
		self.assertAlmostEqual(43.6345, units.volume.teaspoons.to_u_s_tablespoons(109.0), places=1)

	def test_convert_known_teaspoons_to_u_s_quarts(self):
		self.assertAlmostEqual(1.24474, units.volume.teaspoons.to_u_s_quarts(199.0), places=1)
		self.assertAlmostEqual(0.0369042, units.volume.teaspoons.to_u_s_quarts(5.9), places=1)
		self.assertAlmostEqual(0.143864, units.volume.teaspoons.to_u_s_quarts(23.0), places=1)

	def test_convert_known_teaspoons_to_u_s_pints(self):
		self.assertAlmostEqual(1.32605, units.volume.teaspoons.to_u_s_pints(106.0), places=1)
		self.assertAlmostEqual(0.425337, units.volume.teaspoons.to_u_s_pints(34.0), places=1)
		self.assertAlmostEqual(0.07656059, units.volume.teaspoons.to_u_s_pints(6.21), places=1)

	def test_convert_known_teaspoons_to_u_s_gallons(self):
		self.assertAlmostEqual(1.40736, units.volume.teaspoons.to_u_s_gallons(900.0), places=1)
		self.assertAlmostEqual(1.93059035, units.volume.teaspoons.to_u_s_gallons(1234.6), places=1)
		self.assertAlmostEqual(0.137609, units.volume.teaspoons.to_u_s_gallons(88.0), places=1)

	def test_convert_known_teaspoons_to_u_s_fluid_ounces(self):
		self.assertAlmostEqual(11.2089, units.volume.teaspoons.to_u_s_fluid_ounces(56.0), places=1)
		self.assertAlmostEqual(0.580459, units.volume.teaspoons.to_u_s_fluid_ounces(2.9), places=1)
		self.assertAlmostEqual(204.1616, units.volume.teaspoons.to_u_s_fluid_ounces(1020.0), places=1)

	def test_convert_known_teaspoons_to_u_s_cups(self):
		self.assertAlmostEqual(200.1584, units.volume.teaspoons.to_u_s_cups(8000.0), places=1)
		self.assertAlmostEqual(0.850673, units.volume.teaspoons.to_u_s_cups(34.0), places=1)
		self.assertAlmostEqual(2.7496761, units.volume.teaspoons.to_u_s_cups(109.9), places=1)

if __name__ == '__main__':
    unittest.main()
