# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.volume.u_s_tablespoons

class TestUSTablespoonsMethods(unittest.TestCase):

	def test_convert_known_u_s_tablespoons_to_millilitres(self):
		self.assertAlmostEqual(177.441, units.volume.u_s_tablespoons.to_millilitres(12.0), places=1)
		self.assertAlmostEqual(11.8294, units.volume.u_s_tablespoons.to_millilitres(0.8), places=1)
		self.assertAlmostEqual(66540.44, units.volume.u_s_tablespoons.to_millilitres(4500.0), places=1)

	def test_convert_known_u_s_tablespoons_to_litres(self):
		self.assertAlmostEqual(8.3841, units.volume.u_s_tablespoons.to_litres(567.0), places=1)
		self.assertAlmostEqual(1.196249, units.volume.u_s_tablespoons.to_litres(80.9), places=1)
		self.assertAlmostEqual(147.8676, units.volume.u_s_tablespoons.to_litres(10000.0), places=1)

	def test_convert_known_u_s_tablespoons_to_kilolitres(self):
		self.assertAlmostEqual(0.146389, units.volume.u_s_tablespoons.to_kilolitres(9900.0), places=1)
		self.assertAlmostEqual(1.82551483, units.volume.u_s_tablespoons.to_kilolitres(123456.0), places=1)
		self.assertAlmostEqual(0.26629485, units.volume.u_s_tablespoons.to_kilolitres(18009.0), places=1)

	def test_convert_known_u_s_tablespoons_to_teaspoons(self):
		self.assertAlmostEqual(34.9723, units.volume.u_s_tablespoons.to_teaspoons(14.0), places=1)
		self.assertAlmostEqual(2.24822, units.volume.u_s_tablespoons.to_teaspoons(0.9), places=1)
		self.assertAlmostEqual(449.644, units.volume.u_s_tablespoons.to_teaspoons(180.0), places=1)

	def test_convert_known_u_s_tablespoons_to_tablespoons(self):
		self.assertAlmostEqual(90.7614, units.volume.u_s_tablespoons.to_tablespoons(109.0), places=1)
		self.assertAlmostEqual(74.108, units.volume.u_s_tablespoons.to_tablespoons(89.0), places=1)
		self.assertAlmostEqual(4.3299, units.volume.u_s_tablespoons.to_tablespoons(5.2), places=1)

	def test_convert_known_u_s_tablespoons_to_quarts(self):
		self.assertAlmostEqual(4.48863, units.volume.u_s_tablespoons.to_quarts(345.0), places=1)
		self.assertAlmostEqual(1.169647, units.volume.u_s_tablespoons.to_quarts(89.9), places=1)
		self.assertAlmostEqual(0.16757568, units.volume.u_s_tablespoons.to_quarts(12.88), places=1)

	def test_convert_known_u_s_tablespoons_to_pints(self):
		self.assertAlmostEqual(0.312253, units.volume.u_s_tablespoons.to_pints(12.0), places=1)
		self.assertAlmostEqual(21.069259, units.volume.u_s_tablespoons.to_pints(809.7), places=1)
		self.assertAlmostEqual(0.0104084, units.volume.u_s_tablespoons.to_pints(0.4), places=1)

	def test_convert_known_u_s_tablespoons_to_gallons(self):
		self.assertAlmostEqual(1.30105, units.volume.u_s_tablespoons.to_gallons(400.0), places=1)
		self.assertAlmostEqual(3.90608761, units.volume.u_s_tablespoons.to_gallons(1200.9), places=1)
		self.assertAlmostEqual(0.0260211, units.volume.u_s_tablespoons.to_gallons(8.0), places=1)

	def test_convert_known_u_s_tablespoons_to_fluid_ounces(self):
		self.assertAlmostEqual(2.08169, units.volume.u_s_tablespoons.to_fluid_ounces(4.0), places=1)
		self.assertAlmostEqual(26.48945, units.volume.u_s_tablespoons.to_fluid_ounces(50.9), places=1)
		self.assertAlmostEqual(64.0118, units.volume.u_s_tablespoons.to_fluid_ounces(123.0), places=1)

	def test_convert_known_u_s_tablespoons_to_u_s_teaspoons(self):
		self.assertAlmostEqual(270.0, units.volume.u_s_tablespoons.to_u_s_teaspoons(90.0), places=1)
		self.assertAlmostEqual(13.5, units.volume.u_s_tablespoons.to_u_s_teaspoons(4.5), places=1)
		self.assertAlmostEqual(13824.0, units.volume.u_s_tablespoons.to_u_s_teaspoons(4608.0), places=1)

	def test_convert_known_u_s_tablespoons_to_u_s_quarts(self):
		self.assertAlmostEqual(7.125, units.volume.u_s_tablespoons.to_u_s_quarts(456.0), places=1)
		self.assertAlmostEqual(0.11125, units.volume.u_s_tablespoons.to_u_s_quarts(7.12), places=1)
		self.assertAlmostEqual(3.0453125, units.volume.u_s_tablespoons.to_u_s_quarts(194.9), places=1)

	def test_convert_known_u_s_tablespoons_to_u_s_pints(self):
		self.assertAlmostEqual(6.090625, units.volume.u_s_tablespoons.to_u_s_pints(194.9), places=1)
		self.assertAlmostEqual(62.5, units.volume.u_s_tablespoons.to_u_s_pints(2000.0), places=1)
		self.assertAlmostEqual(0.584375, units.volume.u_s_tablespoons.to_u_s_pints(18.7), places=1)

	def test_convert_known_u_s_tablespoons_to_u_s_gallons(self):
		self.assertAlmostEqual(0.07304687, units.volume.u_s_tablespoons.to_u_s_gallons(18.7), places=1)
		self.assertAlmostEqual(7.421875, units.volume.u_s_tablespoons.to_u_s_gallons(1900.0), places=1)
		self.assertAlmostEqual(48.222656, units.volume.u_s_tablespoons.to_u_s_gallons(12345.0), places=1)

	def test_convert_known_u_s_tablespoons_to_u_s_fluid_ounces(self):
		self.assertAlmostEqual(617.0, units.volume.u_s_tablespoons.to_u_s_fluid_ounces(1234.0), places=1)
		self.assertAlmostEqual(44.65, units.volume.u_s_tablespoons.to_u_s_fluid_ounces(89.3), places=1)
		self.assertAlmostEqual(45.495, units.volume.u_s_tablespoons.to_u_s_fluid_ounces(90.99), places=1)

	def test_convert_known_u_s_tablespoons_to_u_s_cups(self):
		self.assertAlmostEqual(5.686875, units.volume.u_s_tablespoons.to_u_s_cups(90.99), places=1)
		self.assertAlmostEqual(76.875, units.volume.u_s_tablespoons.to_u_s_cups(1230.0), places=1)
		self.assertAlmostEqual(562.55625, units.volume.u_s_tablespoons.to_u_s_cups(9000.9), places=1)

	def test_convert_known_u_s_tablespoons_to_cubic_metres(self):
		self.assertAlmostEqual(8.0, units.volume.u_s_tablespoons.to_cubic_metres(541024.0), places=1)
		self.assertAlmostEqual(0.150825, units.volume.u_s_tablespoons.to_cubic_metres(10200.0), places=1)
		self.assertAlmostEqual(1.82551483, units.volume.u_s_tablespoons.to_cubic_metres(123456.0), places=1)

	def test_convert_known_u_s_tablespoons_to_cubic_feet(self):
		self.assertAlmostEqual(0.0344645, units.volume.u_s_tablespoons.to_cubic_feet(66.0), places=1)
		self.assertAlmostEqual(4.0, units.volume.u_s_tablespoons.to_cubic_feet(7660.05), places=1)
		self.assertAlmostEqual(0.6443821, units.volume.u_s_tablespoons.to_cubic_feet(1234.0), places=1)

	def test_convert_known_u_s_tablespoons_to_cubic_inches(self):
		self.assertAlmostEqual(812.109, units.volume.u_s_tablespoons.to_cubic_inches(900.0), places=1)
		self.assertAlmostEqual(9.02344, units.volume.u_s_tablespoons.to_cubic_inches(10.0), places=1)
		self.assertAlmostEqual(3.60938, units.volume.u_s_tablespoons.to_cubic_inches(4.0), places=1)

	def test_convert_known_u_s_tablespoons_to_oil_barrels(self):
		self.assertAlmostEqual(55.0, units.volume.u_s_tablespoons.to_oil_barrels(591360), places=1)
		self.assertAlmostEqual(0.4, units.volume.u_s_tablespoons.to_oil_barrels(4300.8), places=1)
		self.assertAlmostEqual(3.2, units.volume.u_s_tablespoons.to_oil_barrels(34406.4), places=1)

if __name__ == '__main__':
    unittest.main()
