# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.volume.u_s_gallons

class TestUSGallonsMethods(unittest.TestCase):

	def test_convert_known_u_s_gallons_to_millilitres(self):
		self.assertAlmostEqual(7570.82, units.volume.u_s_gallons.to_millilitres(2.0), places=1)
		self.assertAlmostEqual(378.541, units.volume.u_s_gallons.to_millilitres(0.1), places=1)
		self.assertAlmostEqual(211983.0599039, units.volume.u_s_gallons.to_millilitres(56.0), places=1)

	def test_convert_known_u_s_gallons_to_litres(self):
		self.assertAlmostEqual(211.983, units.volume.u_s_gallons.to_litres(56.0), places=1)
		self.assertAlmostEqual(19.3056, units.volume.u_s_gallons.to_litres(5.1), places=1)
		self.assertAlmostEqual(9.46353, units.volume.u_s_gallons.to_litres(2.5), places=1)

	def test_convert_known_u_s_gallons_to_kilolitres(self):
		self.assertAlmostEqual(0.420181, units.volume.u_s_gallons.to_kilolitres(111.0), places=1)
		self.assertAlmostEqual(34.40939, units.volume.u_s_gallons.to_kilolitres(9090.0), places=1)
		self.assertAlmostEqual(46.730908, units.volume.u_s_gallons.to_kilolitres(12345.0), places=1)

	def test_convert_known_u_s_gallons_to_teaspoons(self):
		self.assertAlmostEqual(3197.47, units.volume.u_s_gallons.to_teaspoons(5.0), places=1)
		self.assertAlmostEqual(255.797, units.volume.u_s_gallons.to_teaspoons(0.4), places=1)
		self.assertAlmostEqual(5115948.07582550, units.volume.u_s_gallons.to_teaspoons(8000.0), places=1)

	def test_convert_known_u_s_gallons_to_tablespoons(self):
		self.assertAlmostEqual(16840.0, units.volume.u_s_gallons.to_tablespoons(79.0), places=1)
		self.assertAlmostEqual(2700.7943, units.volume.u_s_gallons.to_tablespoons(12.67), places=1)
		self.assertAlmostEqual(11745.36, units.volume.u_s_gallons.to_tablespoons(55.1), places=1)

	def test_convert_known_u_s_gallons_to_quarts(self):
		self.assertAlmostEqual(179.858, units.volume.u_s_gallons.to_quarts(54.0), places=1)
		self.assertAlmostEqual(9.65902, units.volume.u_s_gallons.to_quarts(2.9), places=1)
		self.assertAlmostEqual(0.666139, units.volume.u_s_gallons.to_quarts(0.2), places=1)

	def test_convert_known_u_s_gallons_to_pints(self):
		self.assertAlmostEqual(13.3228, units.volume.u_s_gallons.to_pints(2.0), places=1)
		self.assertAlmostEqual(0.7993672, units.volume.u_s_gallons.to_pints(0.12), places=1)
		self.assertAlmostEqual(3330.7, units.volume.u_s_gallons.to_pints(500.0), places=1)

	def test_convert_known_u_s_gallons_to_gallons(self):
		self.assertAlmostEqual(19.1515, units.volume.u_s_gallons.to_gallons(23.0), places=1)
		self.assertAlmostEqual(6.82793, units.volume.u_s_gallons.to_gallons(8.2), places=1)
		self.assertAlmostEqual(0.9076149, units.volume.u_s_gallons.to_gallons(1.09), places=1)

	def test_convert_known_u_s_gallons_to_fluid_ounces(self):
		self.assertAlmostEqual(145.2184, units.volume.u_s_gallons.to_fluid_ounces(1.09), places=1)
		self.assertAlmostEqual(4529.75, units.volume.u_s_gallons.to_fluid_ounces(34.0), places=1)
		self.assertAlmostEqual(88729.724440098, units.volume.u_s_gallons.to_fluid_ounces(666.0), places=1)

	def test_convert_known_u_s_gallons_to_u_s_teaspoons(self):
		self.assertAlmostEqual(3072.0, units.volume.u_s_gallons.to_u_s_teaspoons(4.0), places=1)
		self.assertAlmostEqual(983.0403, units.volume.u_s_gallons.to_u_s_teaspoons(1.28), places=1)
		self.assertAlmostEqual(5368.322, units.volume.u_s_gallons.to_u_s_teaspoons(6.99), places=1)

	def test_convert_known_u_s_gallons_to_u_s_tablespoons(self):
		self.assertAlmostEqual(8704.0, units.volume.u_s_gallons.to_u_s_tablespoons(34.0), places=1)
		self.assertAlmostEqual(2150.4, units.volume.u_s_gallons.to_u_s_tablespoons(8.4), places=1)
		self.assertAlmostEqual(23.296, units.volume.u_s_gallons.to_u_s_tablespoons(0.091), places=1)

	def test_convert_known_u_s_gallons_to_u_s_quarts(self):
		self.assertAlmostEqual(0.364, units.volume.u_s_gallons.to_u_s_quarts(0.091), places=1)
		self.assertAlmostEqual(92.0, units.volume.u_s_gallons.to_u_s_quarts(23.0), places=1)
		self.assertAlmostEqual(4003.2, units.volume.u_s_gallons.to_u_s_quarts(1000.8), places=1)

	def test_convert_known_u_s_gallons_to_u_s_pints(self):
		self.assertAlmostEqual(8006.4, units.volume.u_s_gallons.to_u_s_pints(1000.8), places=1)
		self.assertAlmostEqual(188.8, units.volume.u_s_gallons.to_u_s_pints(23.6), places=1)
		self.assertAlmostEqual(5.68, units.volume.u_s_gallons.to_u_s_pints(0.71), places=1)

	def test_convert_known_u_s_gallons_to_u_s_fluid_ounces(self):
		self.assertAlmostEqual(90.88, units.volume.u_s_gallons.to_u_s_fluid_ounces(0.71), places=1)
		self.assertAlmostEqual(10649.6, units.volume.u_s_gallons.to_u_s_fluid_ounces(83.2), places=1)
		self.assertAlmostEqual(99456.0, units.volume.u_s_gallons.to_u_s_fluid_ounces(777.0), places=1)

	def test_convert_known_u_s_gallons_to_u_s_cups(self):
		self.assertAlmostEqual(12432.0, units.volume.u_s_gallons.to_u_s_cups(777.0), places=1)
		self.assertAlmostEqual(91.36, units.volume.u_s_gallons.to_u_s_cups(5.71), places=1)
		self.assertAlmostEqual(15.68, units.volume.u_s_gallons.to_u_s_cups(0.98), places=1)

	def test_convert_known_u_s_gallons_to_cubic_metres(self):
		self.assertAlmostEqual(7.0, units.volume.u_s_gallons.to_cubic_metres(1849.2), places=1)
		self.assertAlmostEqual(0.329331, units.volume.u_s_gallons.to_cubic_metres(87.0), places=1)
		self.assertAlmostEqual(467.331797, units.volume.u_s_gallons.to_cubic_metres(123456.0), places=1)

	def test_convert_known_u_s_gallons_to_cubic_feet(self):
		self.assertAlmostEqual(0.802083, units.volume.u_s_gallons.to_cubic_feet(6.0), places=1)
		self.assertAlmostEqual(3.20833, units.volume.u_s_gallons.to_cubic_feet(24.0), places=1)
		self.assertAlmostEqual(0.668403, units.volume.u_s_gallons.to_cubic_feet(5.0), places=1)

	def test_convert_known_u_s_gallons_to_cubic_inches(self):
		self.assertAlmostEqual(1386.0, units.volume.u_s_gallons.to_cubic_inches(6.0), places=1)
		self.assertAlmostEqual(43890.0, units.volume.u_s_gallons.to_cubic_inches(190.0), places=1)
		self.assertAlmostEqual(12705.0, units.volume.u_s_gallons.to_cubic_inches(55.0), places=1)

	def test_convert_known_u_s_gallons_to_oil_barrels(self):
		self.assertAlmostEqual(23.0, units.volume.u_s_gallons.to_oil_barrels(966.0), places=1)
		self.assertAlmostEqual(29.38095, units.volume.u_s_gallons.to_oil_barrels(1234.0), places=1)
		self.assertAlmostEqual(0.4, units.volume.u_s_gallons.to_oil_barrels(16.8), places=1)

if __name__ == '__main__':
    unittest.main()
