# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.speed.miles_per_hour

class TestMilesPerHourMethods(unittest.TestCase):

	def test_convert_known_miles_per_hour_to_kilometres_per_hour(self):
		self.assertAlmostEqual(555.224, units.speed.miles_per_hour.to_kilometres_per_hour(345.0), places=1)
		self.assertAlmostEqual(2.57495, units.speed.miles_per_hour.to_kilometres_per_hour(1.6), places=1)
		self.assertAlmostEqual(0.804672, units.speed.miles_per_hour.to_kilometres_per_hour(0.5), places=1)

	def test_convert_known_miles_per_hour_to_feet_per_second(self):
		self.assertAlmostEqual(0.733333, units.speed.miles_per_hour.to_feet_per_second(0.5), places=1)
		self.assertAlmostEqual(180.4, units.speed.miles_per_hour.to_feet_per_second(123.0), places=1)
		self.assertAlmostEqual(6.6, units.speed.miles_per_hour.to_feet_per_second(4.5), places=1)

	def test_convert_known_miles_per_hour_to_metres_per_second(self):
		self.assertAlmostEqual(2.01168, units.speed.miles_per_hour.to_metres_per_second(4.5), places=1)
		self.assertAlmostEqual(44.704, units.speed.miles_per_hour.to_metres_per_second(100.0), places=1)
		self.assertAlmostEqual(17.8816, units.speed.miles_per_hour.to_metres_per_second(40.0), places=1)

	def test_convert_known_miles_per_hour_to_knots(self):
		self.assertAlmostEqual(26.0693, units.speed.miles_per_hour.to_knots(30.0), places=1)
		self.assertAlmostEqual(3.91039, units.speed.miles_per_hour.to_knots(4.5), places=1)
		self.assertAlmostEqual(47.7937, units.speed.miles_per_hour.to_knots(55.0), places=1)

if __name__ == '__main__':
    unittest.main()
