# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.time.weeks

class TestWeeksMethods(unittest.TestCase):

	def test_convert_known_weeks_to_seconds(self):
		self.assertAlmostEqual(60480.0, units.time.weeks.to_seconds(0.1), places=1)
		self.assertAlmostEqual(48384.0, units.time.weeks.to_seconds(0.08), places=1)
		self.assertAlmostEqual(1814400.0, units.time.weeks.to_seconds(3.0), places=1)

	def test_convert_known_weeks_to_minutes(self):
		self.assertAlmostEqual(20160.0, units.time.weeks.to_minutes(2.0), places=1)
		self.assertAlmostEqual(4032.0, units.time.weeks.to_minutes(0.4), places=1)
		self.assertAlmostEqual(201.6, units.time.weeks.to_minutes(0.02), places=1)

	def test_convert_known_weeks_to_hours(self):
		self.assertAlmostEqual(3.36, units.time.weeks.to_hours(0.02), places=1)
		self.assertAlmostEqual(12936.0, units.time.weeks.to_hours(77.0), places=1)
		self.assertAlmostEqual(1545.6, units.time.weeks.to_hours(9.2), places=1)

	def test_convert_known_weeks_to_days(self):
		self.assertAlmostEqual(64.4, units.time.weeks.to_days(9.2), places=1)
		self.assertAlmostEqual(1183.0, units.time.weeks.to_days(169.0), places=1)
		self.assertAlmostEqual(28.0, units.time.weeks.to_days(4.0), places=1)

	def test_convert_known_weeks_to_months(self):
		self.assertAlmostEqual(0.920547, units.time.weeks.to_months(4.0), places=1)
		self.assertAlmostEqual(207.12319687, units.time.weeks.to_months(900.0), places=1)
		self.assertAlmostEqual(0.87452, units.time.weeks.to_months(3.8), places=1)

	def test_convert_known_weeks_to_years(self):
		self.assertAlmostEqual(0.0575342, units.time.weeks.to_years(3.0), places=1)
		self.assertAlmostEqual(4.50685, units.time.weeks.to_years(235.0), places=1)
		self.assertAlmostEqual(20.90411, units.time.weeks.to_years(1090.0), places=1)

if __name__ == '__main__':
    unittest.main()
