# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.volume.u_s_cups

class TestUSCupsMethods(unittest.TestCase):

	def test_convert_known_u_s_cups_to_millilitres(self):
		self.assertAlmostEqual(2602.47, units.volume.u_s_cups.to_millilitres(11.0), places=1)
		self.assertAlmostEqual(25788.1177, units.volume.u_s_cups.to_millilitres(109.0), places=1)
		self.assertAlmostEqual(1064.65, units.volume.u_s_cups.to_millilitres(4.5), places=1)

	def test_convert_known_u_s_cups_to_litres(self):
		self.assertAlmostEqual(13.2489, units.volume.u_s_cups.to_litres(56.0), places=1)
		self.assertAlmostEqual(0.970012, units.volume.u_s_cups.to_litres(4.1), places=1)
		self.assertAlmostEqual(94.3987, units.volume.u_s_cups.to_litres(399.0), places=1)

	def test_convert_known_u_s_cups_to_kilolitres(self):
		self.assertAlmostEqual(0.0158514, units.volume.u_s_cups.to_kilolitres(67.0), places=1)
		self.assertAlmostEqual(0.238883142, units.volume.u_s_cups.to_kilolitres(1009.7), places=1)
		self.assertAlmostEqual(217.25259, units.volume.u_s_cups.to_kilolitres(918273.0), places=1)

	def test_convert_known_u_s_cups_to_teaspoons(self):
		self.assertAlmostEqual(159.873, units.volume.u_s_cups.to_teaspoons(4.0), places=1)
		self.assertAlmostEqual(7.99367, units.volume.u_s_cups.to_teaspoons(0.2), places=1)
		self.assertAlmostEqual(244.6063, units.volume.u_s_cups.to_teaspoons(6.12), places=1)

	def test_convert_known_u_s_cups_to_tablespoons(self):
		self.assertAlmostEqual(57.288, units.volume.u_s_cups.to_tablespoons(4.3), places=1)
		self.assertAlmostEqual(1606.7274, units.volume.u_s_cups.to_tablespoons(120.6), places=1)
		self.assertAlmostEqual(8.793036, units.volume.u_s_cups.to_tablespoons(0.66), places=1)

	def test_convert_known_u_s_cups_to_quarts(self):
		self.assertAlmostEqual(210.0421, units.volume.u_s_cups.to_quarts(1009.0), places=1)
		self.assertAlmostEqual(13.943129, units.volume.u_s_cups.to_quarts(66.98), places=1)
		self.assertAlmostEqual(0.025604731, units.volume.u_s_cups.to_quarts(0.123), places=1)

	def test_convert_known_u_s_cups_to_pints(self):
		self.assertAlmostEqual(2.08169, units.volume.u_s_cups.to_pints(5.0), places=1)
		self.assertAlmostEqual(0.1790249, units.volume.u_s_cups.to_pints(0.43), places=1)
		self.assertAlmostEqual(333.23621, units.volume.u_s_cups.to_pints(800.4), places=1)

	def test_convert_known_u_s_cups_to_gallons(self):
		self.assertAlmostEqual(2.91436, units.volume.u_s_cups.to_gallons(56.0), places=1)
		self.assertAlmostEqual(5.41862726, units.volume.u_s_cups.to_gallons(104.12), places=1)
		self.assertAlmostEqual(0.317457, units.volume.u_s_cups.to_gallons(6.1), places=1)

	def test_convert_known_u_s_cups_to_fluid_ounces(self):
		self.assertAlmostEqual(457.971, units.volume.u_s_cups.to_fluid_ounces(55.0), places=1)
		self.assertAlmostEqual(3.3307, units.volume.u_s_cups.to_fluid_ounces(0.4), places=1)
		self.assertAlmostEqual(736.084, units.volume.u_s_cups.to_fluid_ounces(88.4), places=1)

	def test_convert_known_u_s_cups_to_u_s_teaspoons(self):
		self.assertAlmostEqual(576.0, units.volume.u_s_cups.to_u_s_teaspoons(12.0), places=1)
		self.assertAlmostEqual(245.7601, units.volume.u_s_cups.to_u_s_teaspoons(5.12), places=1)
		self.assertAlmostEqual(321648.0, units.volume.u_s_cups.to_u_s_teaspoons(6701.0), places=1)

	def test_convert_known_u_s_cups_to_u_s_tablespoons(self):
		self.assertAlmostEqual(10832.0, units.volume.u_s_cups.to_u_s_tablespoons(677.0), places=1)
		self.assertAlmostEqual(30.4, units.volume.u_s_cups.to_u_s_tablespoons(1.9), places=1)
		self.assertAlmostEqual(12812.8, units.volume.u_s_cups.to_u_s_tablespoons(800.8), places=1)

	def test_convert_known_u_s_cups_to_u_s_quarts(self):
		self.assertAlmostEqual(200.2, units.volume.u_s_cups.to_u_s_quarts(800.8), places=1)
		self.assertAlmostEqual(1.21, units.volume.u_s_cups.to_u_s_quarts(4.84), places=1)
		self.assertAlmostEqual(0.2475, units.volume.u_s_cups.to_u_s_quarts(0.99), places=1)

	def test_convert_known_u_s_cups_to_u_s_pints(self):
		self.assertAlmostEqual(0.495, units.volume.u_s_cups.to_u_s_pints(0.99), places=1)
		self.assertAlmostEqual(179.45, units.volume.u_s_cups.to_u_s_pints(358.9), places=1)
		self.assertAlmostEqual(500.0, units.volume.u_s_cups.to_u_s_pints(1000.0), places=1)

	def test_convert_known_u_s_cups_to_u_s_gallons(self):
		self.assertAlmostEqual(62.5, units.volume.u_s_cups.to_u_s_gallons(1000.0), places=1)
		self.assertAlmostEqual(0.04875, units.volume.u_s_cups.to_u_s_gallons(0.78), places=1)
		self.assertAlmostEqual(7.6951875, units.volume.u_s_cups.to_u_s_gallons(123.123), places=1)

	def test_convert_known_u_s_cups_to_u_s_fluid_ounces(self):
		self.assertAlmostEqual(984.984, units.volume.u_s_cups.to_u_s_fluid_ounces(123.123), places=1)
		self.assertAlmostEqual(32.0, units.volume.u_s_cups.to_u_s_fluid_ounces(4.0), places=1)
		self.assertAlmostEqual(7.2, units.volume.u_s_cups.to_u_s_fluid_ounces(0.9), places=1)

	def test_convert_known_u_s_cups_to_cubic_metres(self):
		self.assertAlmostEqual(1.0932, units.volume.u_s_cups.to_cubic_metres(4555.0), places=1)
		self.assertAlmostEqual(24.216, units.volume.u_s_cups.to_cubic_metres(100900.0), places=1)
		self.assertAlmostEqual(1.872, units.volume.u_s_cups.to_cubic_metres(7800.0), places=1)

	def test_convert_known_u_s_cups_to_cubic_feet(self):
		self.assertAlmostEqual(0.745846, units.volume.u_s_cups.to_cubic_feet(88.0), places=1)
		self.assertAlmostEqual(4.0, units.volume.u_s_cups.to_cubic_feet(471.947), places=1)
		self.assertAlmostEqual(1.04249, units.volume.u_s_cups.to_cubic_feet(123.0), places=1)

	def test_convert_known_u_s_cups_to_cubic_inches(self):
		self.assertAlmostEqual(87.8742, units.volume.u_s_cups.to_cubic_inches(6.0), places=1)
		self.assertAlmostEqual(33.6851, units.volume.u_s_cups.to_cubic_inches(2.3), places=1)
		self.assertAlmostEqual(13.1811, units.volume.u_s_cups.to_cubic_inches(0.9), places=1)

	def test_convert_known_u_s_cups_to_oil_barrels(self):
		self.assertAlmostEqual(66.0, units.volume.u_s_cups.to_oil_barrels(43721.5), places=1)
		self.assertAlmostEqual(1.677115, units.volume.u_s_cups.to_oil_barrels(1111.0), places=1)
		self.assertAlmostEqual(5.0, units.volume.u_s_cups.to_oil_barrels(3312.24), places=1)

if __name__ == '__main__':
    unittest.main()
