# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.length.miles

class TestMilesMethods(unittest.TestCase):

	def test_convert_known_miles_to_millimetres(self):
		self.assertAlmostEqual(144840.95999, units.length.miles.to_millimetres(0.09), places=1)
		self.assertAlmostEqual(1609.344, units.length.miles.to_millimetres(0.001), places=1)
		self.assertAlmostEqual(804672.0, units.length.miles.to_millimetres(0.5), places=1)

	def test_convert_known_miles_to_centimetres(self):
		self.assertAlmostEqual(37014.91, units.length.miles.to_centimetres(0.23), places=1)
		self.assertAlmostEqual(1609.344, units.length.miles.to_centimetres(0.01), places=1)
		self.assertAlmostEqual(128747.52, units.length.miles.to_centimetres(0.8), places=1)

	def test_convert_known_miles_to_metres(self):
		self.assertAlmostEqual(160.934, units.length.miles.to_metres(0.1), places=1)
		self.assertAlmostEqual(128.7475, units.length.miles.to_metres(0.08), places=1)
		self.assertAlmostEqual(3.218688, units.length.miles.to_metres(0.002), places=1)

	def test_convert_known_miles_to_kilometres(self):
		self.assertAlmostEqual(3.21869, units.length.miles.to_kilometres(2.0), places=1)
		self.assertAlmostEqual(1.28748, units.length.miles.to_kilometres(0.8), places=1)
		self.assertAlmostEqual(37.0149, units.length.miles.to_kilometres(23.0), places=1)

	def test_convert_known_miles_to_inches(self):
		self.assertAlmostEqual(44352.0, units.length.miles.to_inches(0.7), places=1)
		self.assertAlmostEqual(5702.4, units.length.miles.to_inches(0.09), places=1)
		self.assertAlmostEqual(126720.0, units.length.miles.to_inches(2.0), places=1)

	def test_convert_known_miles_to_feet(self):
		self.assertAlmostEqual(10560.0, units.length.miles.to_feet(2.0), places=1)
		self.assertAlmostEqual(3168.0, units.length.miles.to_feet(0.6), places=1)
		self.assertAlmostEqual(369.6, units.length.miles.to_feet(0.07), places=1)

	def test_convert_known_miles_to_yards(self):
		self.assertAlmostEqual(123.2, units.length.miles.to_yards(0.07), places=1)
		self.assertAlmostEqual(3520.0, units.length.miles.to_yards(2.0), places=1)
		self.assertAlmostEqual(14256.0, units.length.miles.to_yards(8.1), places=1)

	def test_convert_known_miles_to_nautical_miles(self):
		self.assertAlmostEqual(7.03871, units.length.miles.to_nautical_miles(8.1), places=1)
		self.assertAlmostEqual(0.695181, units.length.miles.to_nautical_miles(0.8), places=1)
		self.assertAlmostEqual(1.04277, units.length.miles.to_nautical_miles(1.2), places=1)

if __name__ == '__main__':
    unittest.main()
