# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.time.milliseconds

class TestMillisecondsMethods(unittest.TestCase):

	def test_convert_known_milliseconds_to_seconds(self):
		self.assertAlmostEqual(0.008, units.time.milliseconds.to_seconds(8.0), places=1)
		self.assertAlmostEqual(0.78, units.time.milliseconds.to_seconds(780.0), places=1)
		self.assertAlmostEqual(0.9, units.time.milliseconds.to_seconds(900.0), places=1)

	def test_convert_known_milliseconds_to_minutes(self):
		self.assertAlmostEqual(0.015, units.time.milliseconds.to_minutes(900.0), places=1)
		self.assertAlmostEqual(1.1166667, units.time.milliseconds.to_minutes(67000.0), places=1)
		self.assertAlmostEqual(20.57611667, units.time.milliseconds.to_minutes(1234567.0), places=1)

	def test_convert_known_milliseconds_to_hours(self):
		self.assertAlmostEqual(0.3429352778, units.time.milliseconds.to_hours(1234567.0), places=1)
		self.assertAlmostEqual(0.0280277778, units.time.milliseconds.to_hours(100900.0), places=1)
		self.assertAlmostEqual(0.012777778, units.time.milliseconds.to_hours(46000.0), places=1)

	def test_convert_known_milliseconds_to_days(self):
		self.assertAlmostEqual(0.1041666667, units.time.milliseconds.to_days(9000000.0), places=1)
		self.assertAlmostEqual(1.42889802083, units.time.milliseconds.to_days(123456789.0), places=1)
		self.assertAlmostEqual(1.0301956019, units.time.milliseconds.to_days(89008900.0), places=1)

	def test_convert_known_milliseconds_to_weeks(self):
		self.assertAlmostEqual(0.14717080026, units.time.milliseconds.to_weeks(89008900.0), places=1)
		self.assertAlmostEqual(2.041282886905, units.time.milliseconds.to_weeks(1234567890.0), places=1)
		self.assertAlmostEqual(0.165675099206, units.time.milliseconds.to_weeks(100200300.0), places=1)

	def test_convert_known_milliseconds_to_months(self):
		self.assertAlmostEqual(38.102653412154631, units.time.milliseconds.to_months(100200300400.0), places=1)
		self.assertAlmostEqual(0.034246918329, units.time.milliseconds.to_months(90001000.0), places=1)
		self.assertAlmostEqual(3.382374104552, units.time.milliseconds.to_months(8888888888.0), places=1)

	def test_convert_known_milliseconds_to_years(self):
		self.assertAlmostEqual(0.28167767558793383, units.time.milliseconds.to_years(8888888888.0), places=1)
		self.assertAlmostEqual(3.9121899074093087, units.time.milliseconds.to_years(123456789123.0), places=1)
		self.assertAlmostEqual(28.522399977032002, units.time.milliseconds.to_years(900080007000.0), places=1)

if __name__ == '__main__':
    unittest.main()
