# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.time.hours

class TestHoursMethods(unittest.TestCase):

	def test_convert_known_hours_to_milliseconds(self):
		self.assertAlmostEqual(21600.0, units.time.hours.to_milliseconds(0.006), places=1)
		self.assertAlmostEqual(324000.0, units.time.hours.to_milliseconds(0.09), places=1)
		self.assertAlmostEqual(25200.0, units.time.hours.to_milliseconds(0.007), places=1)

	def test_convert_known_hours_to_seconds(self):
		self.assertAlmostEqual(43200.0, units.time.hours.to_seconds(12.0), places=1)
		self.assertAlmostEqual(11520.0, units.time.hours.to_seconds(3.2), places=1)
		self.assertAlmostEqual(1080.0, units.time.hours.to_seconds(0.3), places=1)

	def test_convert_known_hours_to_minutes(self):
		self.assertAlmostEqual(18.0, units.time.hours.to_minutes(0.3), places=1)
		self.assertAlmostEqual(42000.0, units.time.hours.to_minutes(700.0), places=1)
		self.assertAlmostEqual(288.0, units.time.hours.to_minutes(4.8), places=1)

	def test_convert_known_hours_to_days(self):
		self.assertAlmostEqual(0.2, units.time.hours.to_days(4.8), places=1)
		self.assertAlmostEqual(7.91667, units.time.hours.to_days(190.0), places=1)
		self.assertAlmostEqual(0.354167, units.time.hours.to_days(8.5), places=1)

	def test_convert_known_hours_to_weeks(self):
		self.assertAlmostEqual(4.7619, units.time.hours.to_weeks(800.0), places=1)
		self.assertAlmostEqual(0.535714, units.time.hours.to_weeks(90.0), places=1)
		self.assertAlmostEqual(0.607143, units.time.hours.to_weeks(102.0), places=1)

	def test_convert_known_hours_to_months(self):
		self.assertAlmostEqual(0.139726, units.time.hours.to_months(102.0), places=1)
		self.assertAlmostEqual(13.52875, units.time.hours.to_months(9876.0), places=1)
		self.assertAlmostEqual(0.13808204, units.time.hours.to_months(100.8), places=1)

	def test_convert_known_hours_to_years(self):
		self.assertAlmostEqual(1.027397, units.time.hours.to_years(9000.0), places=1)
		self.assertAlmostEqual(0.1144977, units.time.hours.to_years(1003.0), places=1)
		self.assertAlmostEqual(0.0923516, units.time.hours.to_years(809.0), places=1)

if __name__ == '__main__':
    unittest.main()
