# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.data_transfer_rate.bits_per_second

class TestBitsPerSecondMethods(unittest.TestCase):

	def test_convert_known_bits_per_second_to_kilo_bits_per_second(self):
		self.assertAlmostEqual(0.1, units.data_transfer_rate.bits_per_second.to_kilo_bits_per_second(100.0), places=1)
		self.assertAlmostEqual(6.021, units.data_transfer_rate.bits_per_second.to_kilo_bits_per_second(6021.0), places=1)
		self.assertAlmostEqual(9.1, units.data_transfer_rate.bits_per_second.to_kilo_bits_per_second(9100.0), places=1)

	def test_convert_known_bits_per_second_to_mega_bits_per_second(self):
		self.assertAlmostEqual(9.0, units.data_transfer_rate.bits_per_second.to_mega_bits_per_second(9000000.0), places=1)
		self.assertAlmostEqual(0.123456, units.data_transfer_rate.bits_per_second.to_mega_bits_per_second(123456.0), places=1)
		self.assertAlmostEqual(1.9, units.data_transfer_rate.bits_per_second.to_mega_bits_per_second(1900000.0), places=1)

	def test_convert_known_bits_per_second_to_giga_bits_per_second(self):
		self.assertAlmostEqual(0.19, units.data_transfer_rate.bits_per_second.to_giga_bits_per_second(190000000.0), places=1)
		self.assertAlmostEqual(8.009e-6, units.data_transfer_rate.bits_per_second.to_giga_bits_per_second(8009.0), places=1)
		self.assertAlmostEqual(0.987654321, units.data_transfer_rate.bits_per_second.to_giga_bits_per_second(987654321.0), places=1)

	def test_convert_known_bits_per_second_to_tera_bits_per_second(self):
		self.assertAlmostEqual(0.987654321234, units.data_transfer_rate.bits_per_second.to_tera_bits_per_second(987654321234.0), places=1)
		self.assertAlmostEqual(1234.567890123455982, units.data_transfer_rate.bits_per_second.to_tera_bits_per_second(1234567890123456.0), places=1)
		self.assertAlmostEqual(999.888777666555029, units.data_transfer_rate.bits_per_second.to_tera_bits_per_second(999888777666555.0), places=1)

	def test_convert_known_bits_per_second_to_kilo_bytes_per_second(self):
		self.assertAlmostEqual(0.1125, units.data_transfer_rate.bits_per_second.to_kilo_bytes_per_second(900.0), places=1)
		self.assertAlmostEqual(1.543125, units.data_transfer_rate.bits_per_second.to_kilo_bytes_per_second(12345.0), places=1)
		self.assertAlmostEqual(0.7501125, units.data_transfer_rate.bits_per_second.to_kilo_bytes_per_second(6000.9), places=1)

	def test_convert_known_bits_per_second_to_mega_bytes_per_second(self):
		self.assertAlmostEqual(0.015432, units.data_transfer_rate.bits_per_second.to_mega_bytes_per_second(123456.0), places=1)
		self.assertAlmostEqual(0.1126, units.data_transfer_rate.bits_per_second.to_mega_bytes_per_second(900800.0), places=1)
		self.assertAlmostEqual(124.986097125, units.data_transfer_rate.bits_per_second.to_mega_bytes_per_second(999888777.0), places=1)

	def test_convert_known_bits_per_second_to_giga_bytes_per_second(self):
		self.assertAlmostEqual(0.124986097125, units.data_transfer_rate.bits_per_second.to_giga_bytes_per_second(999888777.0), places=1)
		self.assertAlmostEqual(0.2375, units.data_transfer_rate.bits_per_second.to_giga_bytes_per_second(1.9e+9), places=1)
		self.assertAlmostEqual(0.010011259625, units.data_transfer_rate.bits_per_second.to_giga_bytes_per_second(80090077.0), places=1)

	def test_convert_known_bits_per_second_to_tera_bytes_per_second(self):
		self.assertAlmostEqual(0.12498609720825, units.data_transfer_rate.bits_per_second.to_tera_bytes_per_second(999888777666.0), places=1)
		self.assertAlmostEqual(1.5432098640431251, units.data_transfer_rate.bits_per_second.to_tera_bytes_per_second(12345678912345.0), places=1)
		self.assertAlmostEqual(13.9999028610416243, units.data_transfer_rate.bits_per_second.to_tera_bytes_per_second(111999222888333.0), places=1)

	def test_convert_known_bits_per_second_to_kibibits_per_second(self):
		self.assertAlmostEqual(1.757813, units.data_transfer_rate.bits_per_second.to_kibibits_per_second(1800.0), places=1)
		self.assertAlmostEqual(0.867188, units.data_transfer_rate.bits_per_second.to_kibibits_per_second(888.0), places=1)
		self.assertAlmostEqual(7.506836, units.data_transfer_rate.bits_per_second.to_kibibits_per_second(7687.0), places=1)

	def test_convert_known_bits_per_second_to_mebibits_per_second(self):
		self.assertAlmostEqual(0.953567505, units.data_transfer_rate.bits_per_second.to_mebibits_per_second(999888.0), places=1)
		self.assertAlmostEqual(1.17737484, units.data_transfer_rate.bits_per_second.to_mebibits_per_second(1234567.0), places=1)
		self.assertAlmostEqual(0.859069824, units.data_transfer_rate.bits_per_second.to_mebibits_per_second(900800.0), places=1)

if __name__ == '__main__':
    unittest.main()
