# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.data_transfer_rate.giga_bits_per_second

class TestGigaBitsPerSecondMethods(unittest.TestCase):

	def test_convert_known_giga_bits_per_second_to_bits_per_second(self):
		self.assertAlmostEqual(900000.0, units.data_transfer_rate.giga_bits_per_second.to_bits_per_second(0.0009), places=1)
		self.assertAlmostEqual(70000.0, units.data_transfer_rate.giga_bits_per_second.to_bits_per_second(0.00007), places=1)
		self.assertAlmostEqual(12000.0, units.data_transfer_rate.giga_bits_per_second.to_bits_per_second(1.2e-5), places=1)

	def test_convert_known_giga_bits_per_second_to_kilo_bits_per_second(self):
		self.assertAlmostEqual(10000.0, units.data_transfer_rate.giga_bits_per_second.to_kilo_bits_per_second(0.01), places=1)
		self.assertAlmostEqual(910000.0, units.data_transfer_rate.giga_bits_per_second.to_kilo_bits_per_second(0.91), places=1)
		self.assertAlmostEqual(6.1e+6, units.data_transfer_rate.giga_bits_per_second.to_kilo_bits_per_second(6.1), places=1)

	def test_convert_known_giga_bits_per_second_to_mega_bits_per_second(self):
		self.assertAlmostEqual(6100.0, units.data_transfer_rate.giga_bits_per_second.to_mega_bits_per_second(6.1), places=1)
		self.assertAlmostEqual(961.0, units.data_transfer_rate.giga_bits_per_second.to_mega_bits_per_second(0.961), places=1)
		self.assertAlmostEqual(1.2, units.data_transfer_rate.giga_bits_per_second.to_mega_bits_per_second(1.2e-3), places=1)

	def test_convert_known_giga_bits_per_second_to_tera_bits_per_second(self):
		self.assertAlmostEqual(1.2, units.data_transfer_rate.giga_bits_per_second.to_tera_bits_per_second(1200.0), places=1)
		self.assertAlmostEqual(90.012, units.data_transfer_rate.giga_bits_per_second.to_tera_bits_per_second(90012.0), places=1)
		self.assertAlmostEqual(8.0, units.data_transfer_rate.giga_bits_per_second.to_tera_bits_per_second(8000.0), places=1)

	def test_convert_known_giga_bits_per_second_to_kilo_bytes_per_second(self):
		self.assertAlmostEqual(150000.0, units.data_transfer_rate.giga_bits_per_second.to_kilo_bytes_per_second(1.2), places=1)
		self.assertAlmostEqual(112500.0, units.data_transfer_rate.giga_bits_per_second.to_kilo_bytes_per_second(0.9), places=1)
		self.assertAlmostEqual(125.0, units.data_transfer_rate.giga_bits_per_second.to_kilo_bytes_per_second(0.001), places=1)

	def test_convert_known_giga_bits_per_second_to_mega_bytes_per_second(self):
		self.assertAlmostEqual(112.5, units.data_transfer_rate.giga_bits_per_second.to_mega_bytes_per_second(0.9), places=1)
		self.assertAlmostEqual(150.0, units.data_transfer_rate.giga_bits_per_second.to_mega_bytes_per_second(1.2), places=1)
		self.assertAlmostEqual(10012.5, units.data_transfer_rate.giga_bits_per_second.to_mega_bytes_per_second(80.1), places=1)

	def test_convert_known_giga_bits_per_second_to_giga_bytes_per_second(self):
		self.assertAlmostEqual(12.375, units.data_transfer_rate.giga_bits_per_second.to_giga_bytes_per_second(99.0), places=1)
		self.assertAlmostEqual(15.390375, units.data_transfer_rate.giga_bits_per_second.to_giga_bytes_per_second(123.123), places=1)
		self.assertAlmostEqual(1000.1125, units.data_transfer_rate.giga_bits_per_second.to_giga_bytes_per_second(8000.9), places=1)

	def test_convert_known_giga_bits_per_second_to_tera_bytes_per_second(self):
		self.assertAlmostEqual(1.125, units.data_transfer_rate.giga_bits_per_second.to_tera_bytes_per_second(9000.0), places=1)
		self.assertAlmostEqual(154.320875, units.data_transfer_rate.giga_bits_per_second.to_tera_bytes_per_second(1234567.0), places=1)
		self.assertAlmostEqual(0.076625, units.data_transfer_rate.giga_bits_per_second.to_tera_bytes_per_second(613.0), places=1)

	def test_convert_known_giga_bits_per_second_to_kibibits_per_second(self):
		self.assertAlmostEqual(781250.0, units.data_transfer_rate.giga_bits_per_second.to_kibibits_per_second(0.8), places=1)
		self.assertAlmostEqual(11718.75, units.data_transfer_rate.giga_bits_per_second.to_kibibits_per_second(0.012), places=1)
		self.assertAlmostEqual(1953.125, units.data_transfer_rate.giga_bits_per_second.to_kibibits_per_second(0.002), places=1)

	def test_convert_known_giga_bits_per_second_to_mebibits_per_second(self):
		self.assertAlmostEqual(1.9073486, units.data_transfer_rate.giga_bits_per_second.to_mebibits_per_second(0.002), places=1)
		self.assertAlmostEqual(858.6, units.data_transfer_rate.giga_bits_per_second.to_mebibits_per_second(0.9), places=1)
		self.assertAlmostEqual(5819.4, units.data_transfer_rate.giga_bits_per_second.to_mebibits_per_second(6.1), places=1)

if __name__ == '__main__':
    unittest.main()
