# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.pressure.pascals

class TestPascalsMethods(unittest.TestCase):

	def test_convert_known_pascals_to_atmospheres(self):
		self.assertAlmostEqual(0.88823094, units.pressure.pascals.to_atmospheres(90000.0), places=1)
		self.assertAlmostEqual(12.18422897, units.pressure.pascals.to_atmospheres(1234567.0), places=1)
		self.assertAlmostEqual(2.01391562, units.pressure.pascals.to_atmospheres(204060.0), places=1)

	def test_convert_known_pascals_to_bars(self):
		self.assertAlmostEqual(0.1, units.pressure.pascals.to_bars(10000.0), places=1)
		self.assertAlmostEqual(0.12345, units.pressure.pascals.to_bars(12345.0), places=1)
		self.assertAlmostEqual(0.8, units.pressure.pascals.to_bars(80000.0), places=1)

	def test_convert_known_pascals_to_torrs(self):
		self.assertAlmostEqual(600.04935, units.pressure.pascals.to_torrs(80000.0), places=1)
		self.assertAlmostEqual(9.255761, units.pressure.pascals.to_torrs(1234.0), places=1)
		self.assertAlmostEqual(0.600049, units.pressure.pascals.to_torrs(80.0), places=1)

	def test_convert_known_pascals_to_psi(self):
		self.assertAlmostEqual(0.11603, units.pressure.pascals.to_psi(800.0), places=1)
		self.assertAlmostEqual(1.257477, units.pressure.pascals.to_psi(8670.0), places=1)
		self.assertAlmostEqual(0.145038, units.pressure.pascals.to_psi(1000.0), places=1)

if __name__ == '__main__':
    unittest.main()
