# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.data_storage.mebibits

class TestMebibitsMethods(unittest.TestCase):

	def test_convert_known_mebibits_to_bits(self):
		self.assertAlmostEqual(943718.4, units.data_storage.mebibits.to_bits(0.9), places=1)
		self.assertAlmostEqual(6291.456, units.data_storage.mebibits.to_bits(0.006), places=1)
		self.assertAlmostEqual(2097152.0, units.data_storage.mebibits.to_bits(2.0), places=1)

	def test_convert_known_mebibits_to_kilobits(self):
		self.assertAlmostEqual(838.861, units.data_storage.mebibits.to_kilobits(0.8), places=1)
		self.assertAlmostEqual(2097.15, units.data_storage.mebibits.to_kilobits(2.0), places=1)
		self.assertAlmostEqual(241.1725, units.data_storage.mebibits.to_kilobits(0.23), places=1)

	def test_convert_known_mebibits_to_megabits(self):
		self.assertAlmostEqual(0.943718, units.data_storage.mebibits.to_megabits(0.9), places=1)
		self.assertAlmostEqual(12.89748, units.data_storage.mebibits.to_megabits(12.3), places=1)
		self.assertAlmostEqual(8.49347, units.data_storage.mebibits.to_megabits(8.1), places=1)

	def test_convert_known_mebibits_to_gigabits(self):
		self.assertAlmostEqual(12.944671, units.data_storage.mebibits.to_gigabits(12345.0), places=1)
		self.assertAlmostEqual(0.104858, units.data_storage.mebibits.to_gigabits(100.0), places=1)
		self.assertAlmostEqual(1.0484711, units.data_storage.mebibits.to_gigabits(999.9), places=1)

	def test_convert_known_mebibits_to_terabits(self):
		self.assertAlmostEqual(0.104867037, units.data_storage.mebibits.to_terabits(100009.0), places=1)
		self.assertAlmostEqual(10.35630595, units.data_storage.mebibits.to_terabits(9876543.0), places=1)
		self.assertAlmostEqual(1.049519718, units.data_storage.mebibits.to_terabits(1000900.0), places=1)

	def test_convert_known_mebibits_to_kilobytes(self):
		self.assertAlmostEqual(524.288, units.data_storage.mebibits.to_kilobytes(4.0), places=1)
		self.assertAlmostEqual(190.0544, units.data_storage.mebibits.to_kilobytes(1.45), places=1)
		self.assertAlmostEqual(11548.754, units.data_storage.mebibits.to_kilobytes(88.11), places=1)

	def test_convert_known_mebibits_to_megabytes(self):
		self.assertAlmostEqual(14.2868, units.data_storage.mebibits.to_megabytes(109.0), places=1)
		self.assertAlmostEqual(7.2967782, units.data_storage.mebibits.to_megabytes(55.67), places=1)
		self.assertAlmostEqual(5987.1068, units.data_storage.mebibits.to_megabytes(45678.0), places=1)

	def test_convert_known_mebibits_to_gigabytes(self):
		self.assertAlmostEqual(0.524288311, units.data_storage.mebibits.to_gigabytes(4000.0), places=1)
		self.assertAlmostEqual(11.80959421, units.data_storage.mebibits.to_gigabytes(90100.0), places=1)
		self.assertAlmostEqual(0.132251727, units.data_storage.mebibits.to_gigabytes(1009.0), places=1)

	def test_convert_known_mebibits_to_terabytes(self):
		self.assertAlmostEqual(0.1310731796, units.data_storage.mebibits.to_terabytes(1000009.0), places=1)
		self.assertAlmostEqual(11.902396662, units.data_storage.mebibits.to_terabytes(90808080.0), places=1)
		self.assertAlmostEqual(681574.4, units.data_storage.mebibits.to_terabytes(5.2e12), places=1)

	def test_convert_known_mebibits_to_kibibits(self):
		self.assertAlmostEqual(5120.0, units.data_storage.mebibits.to_kibibits(5.0), places=1)
		self.assertAlmostEqual(1264189.44, units.data_storage.mebibits.to_kibibits(1234.56), places=1)
		self.assertAlmostEqual(517120.0, units.data_storage.mebibits.to_kibibits(505.0), places=1)

if __name__ == '__main__':
    unittest.main()
