# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.angle.seconds_of_arc

class TestSecondsOfArcMethods(unittest.TestCase):

	def test_convert_known_seconds_of_arc_to_degrees(self):
		self.assertAlmostEqual(0.25, units.angle.seconds_of_arc.to_degrees(900.0), places=1)
		self.assertAlmostEqual(0.034277778, units.angle.seconds_of_arc.to_degrees(123.4), places=1)
		self.assertAlmostEqual(2.222222, units.angle.seconds_of_arc.to_degrees(8000.0), places=1)

	def test_convert_known_seconds_of_arc_to_radians(self):
		self.assertAlmostEqual(0.921145994, units.angle.seconds_of_arc.to_radians(190000.0), places=1)
		self.assertAlmostEqual(0.43143569, units.angle.seconds_of_arc.to_radians(88990.0), places=1)
		self.assertAlmostEqual(0.48481368, units.angle.seconds_of_arc.to_radians(100000.0), places=1)

	def test_convert_known_seconds_of_arc_to_gradians(self):
		self.assertAlmostEqual(0.308642, units.angle.seconds_of_arc.to_gradians(1000.0), places=1)
		self.assertAlmostEqual(0.249691, units.angle.seconds_of_arc.to_gradians(809.0), places=1)
		self.assertAlmostEqual(0.483919761, units.angle.seconds_of_arc.to_gradians(1567.9), places=1)

	def test_convert_known_seconds_of_arc_to_milliradians(self):
		self.assertAlmostEqual(5.982601, units.angle.seconds_of_arc.to_milliradians(1234.0), places=1)
		self.assertAlmostEqual(4.40696, units.angle.seconds_of_arc.to_milliradians(909.0), places=1)
		self.assertAlmostEqual(921.189627, units.angle.seconds_of_arc.to_milliradians(190009.0), places=1)

	def test_convert_known_seconds_of_arc_to_minute_of_arc(self):
		self.assertAlmostEqual(1.66667, units.angle.seconds_of_arc.to_minute_of_arc(100.0), places=1)
		self.assertAlmostEqual(15.1333, units.angle.seconds_of_arc.to_minute_of_arc(908.0), places=1)
		self.assertAlmostEqual(134.85, units.angle.seconds_of_arc.to_minute_of_arc(8091.0), places=1)

if __name__ == '__main__':
    unittest.main()
