# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.data_transfer_rate.tera_bits_per_second

class TestTeraBitsPerSecondMethods(unittest.TestCase):

	def test_convert_known_tera_bits_per_second_to_bits_per_second(self):
		self.assertAlmostEqual(700000000.0, units.data_transfer_rate.tera_bits_per_second.to_bits_per_second(0.0007), places=1)
		self.assertAlmostEqual(1230000.0, units.data_transfer_rate.tera_bits_per_second.to_bits_per_second(1.23e-6), places=1)
		self.assertAlmostEqual(980000000.0, units.data_transfer_rate.tera_bits_per_second.to_bits_per_second(0.00098), places=1)

	def test_convert_known_tera_bits_per_second_to_kilo_bits_per_second(self):
		self.assertAlmostEqual(1000000.0, units.data_transfer_rate.tera_bits_per_second.to_kilo_bits_per_second(0.001), places=1)
		self.assertAlmostEqual(6100.0, units.data_transfer_rate.tera_bits_per_second.to_kilo_bits_per_second(6.1e-6), places=1)
		self.assertAlmostEqual(90000.0, units.data_transfer_rate.tera_bits_per_second.to_kilo_bits_per_second(0.00009), places=1)

	def test_convert_known_tera_bits_per_second_to_mega_bits_per_second(self):
		self.assertAlmostEqual(90000.0, units.data_transfer_rate.tera_bits_per_second.to_mega_bits_per_second(0.09), places=1)
		self.assertAlmostEqual(350.0, units.data_transfer_rate.tera_bits_per_second.to_mega_bits_per_second(3.5e-4), places=1)
		self.assertAlmostEqual(12300.0, units.data_transfer_rate.tera_bits_per_second.to_mega_bits_per_second(0.0123), places=1)

	def test_convert_known_tera_bits_per_second_to_giga_bits_per_second(self):
		self.assertAlmostEqual(900.0, units.data_transfer_rate.tera_bits_per_second.to_giga_bits_per_second(0.9), places=1)
		self.assertAlmostEqual(1450.0, units.data_transfer_rate.tera_bits_per_second.to_giga_bits_per_second(1.45), places=1)
		self.assertAlmostEqual(8190.0, units.data_transfer_rate.tera_bits_per_second.to_giga_bits_per_second(8.19), places=1)

	def test_convert_known_tera_bits_per_second_to_kilo_bytes_per_second(self):
		self.assertAlmostEqual(112500.0, units.data_transfer_rate.tera_bits_per_second.to_kilo_bytes_per_second(0.0009), places=1)
		self.assertAlmostEqual(392.5, units.data_transfer_rate.tera_bits_per_second.to_kilo_bytes_per_second(3.14e-6), places=1)
		self.assertAlmostEqual(125000.0, units.data_transfer_rate.tera_bits_per_second.to_kilo_bytes_per_second(0.001), places=1)

	def test_convert_known_tera_bits_per_second_to_mega_bytes_per_second(self):
		self.assertAlmostEqual(50000.0, units.data_transfer_rate.tera_bits_per_second.to_mega_bytes_per_second(0.4), places=1)
		self.assertAlmostEqual(487.5, units.data_transfer_rate.tera_bits_per_second.to_mega_bytes_per_second(3.9e-3), places=1)
		self.assertAlmostEqual(875.0, units.data_transfer_rate.tera_bits_per_second.to_mega_bytes_per_second(0.007), places=1)

	def test_convert_known_tera_bits_per_second_to_giga_bytes_per_second(self):
		self.assertAlmostEqual(1.125, units.data_transfer_rate.tera_bits_per_second.to_giga_bytes_per_second(0.009), places=1)
		self.assertAlmostEqual(0.15375, units.data_transfer_rate.tera_bits_per_second.to_giga_bytes_per_second(0.00123), places=1)
		self.assertAlmostEqual(1.0125, units.data_transfer_rate.tera_bits_per_second.to_giga_bytes_per_second(8.1e-3), places=1)

	def test_convert_known_tera_bits_per_second_to_tera_bytes_per_second(self):
		self.assertAlmostEqual(0.0375, units.data_transfer_rate.tera_bits_per_second.to_tera_bytes_per_second(0.3), places=1)
		self.assertAlmostEqual(1.75, units.data_transfer_rate.tera_bits_per_second.to_tera_bytes_per_second(14.0), places=1)
		self.assertAlmostEqual(0.1, units.data_transfer_rate.tera_bits_per_second.to_tera_bytes_per_second(0.8), places=1)

	def test_convert_known_tera_bits_per_second_to_kibibits_per_second(self):
		self.assertAlmostEqual(878906.25, units.data_transfer_rate.tera_bits_per_second.to_kibibits_per_second(0.0009), places=1)
		self.assertAlmostEqual(5957.031, units.data_transfer_rate.tera_bits_per_second.to_kibibits_per_second(6.1e-6), places=1)
		self.assertAlmostEqual(11.71875, units.data_transfer_rate.tera_bits_per_second.to_kibibits_per_second(12e-9), places=1)

	def test_convert_known_tera_bits_per_second_to_mebibits_per_second(self):
		self.assertAlmostEqual(858306.59999, units.data_transfer_rate.tera_bits_per_second.to_mebibits_per_second(0.9), places=1)
		self.assertAlmostEqual(4386.9, units.data_transfer_rate.tera_bits_per_second.to_mebibits_per_second(4.6e-3), places=1)
		self.assertAlmostEqual(1173.0194092, units.data_transfer_rate.tera_bits_per_second.to_mebibits_per_second(0.00123), places=1)

if __name__ == '__main__':
    unittest.main()
