# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.time.minutes

class TestMinutesMethods(unittest.TestCase):

	def test_convert_known_minutes_to_milliseconds(self):
		self.assertAlmostEqual(420.0, units.time.minutes.to_milliseconds(0.007), places=1)
		self.assertAlmostEqual(48000.0, units.time.minutes.to_milliseconds(0.8), places=1)
		self.assertAlmostEqual(540000.0, units.time.minutes.to_milliseconds(9.0), places=1)

	def test_convert_known_minutes_to_seconds(self):
		self.assertAlmostEqual(5400.0, units.time.minutes.to_seconds(90.0), places=1)
		self.assertAlmostEqual(54.0, units.time.minutes.to_seconds(0.9), places=1)
		self.assertAlmostEqual(7380.0, units.time.minutes.to_seconds(123.0), places=1)

	def test_convert_known_minutes_to_hours(self):
		self.assertAlmostEqual(2.05, units.time.minutes.to_hours(123.0), places=1)
		self.assertAlmostEqual(1.28333, units.time.minutes.to_hours(77.0), places=1)
		self.assertAlmostEqual(0.0133333, units.time.minutes.to_hours(0.8), places=1)

	def test_convert_known_minutes_to_days(self):
		self.assertAlmostEqual(0.555556, units.time.minutes.to_days(800.0), places=1)
		self.assertAlmostEqual(0.131944, units.time.minutes.to_days(190.0), places=1)
		self.assertAlmostEqual(0.0381944, units.time.minutes.to_days(55.0), places=1)

	def test_convert_known_minutes_to_weeks(self):
		self.assertAlmostEqual(0.1884921, units.time.minutes.to_weeks(1900.0), places=1)
		self.assertAlmostEqual(0.0793651, units.time.minutes.to_weeks(800.0), places=1)
		self.assertAlmostEqual(1.2247024, units.time.minutes.to_weeks(12345.0), places=1)

	def test_convert_known_minutes_to_months(self):
		self.assertAlmostEqual(0.02817349, units.time.minutes.to_months(1234.0), places=1)
		self.assertAlmostEqual(2.0547923, units.time.minutes.to_months(90000.0), places=1)
		self.assertAlmostEqual(0.1621003, units.time.minutes.to_months(7100.0), places=1)

	def test_convert_known_minutes_to_years(self):
		self.assertAlmostEqual(1.71385084, units.time.minutes.to_years(900800.0), places=1)
		self.assertAlmostEqual(0.023487443, units.time.minutes.to_years(12345.0), places=1)
		self.assertAlmostEqual(1.16230974, units.time.minutes.to_years(610910.0), places=1)

if __name__ == '__main__':
    unittest.main()
