# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.mass.grams

class TestGramsMethods(unittest.TestCase):

	def test_convert_known_grams_to_milligrams(self):
		self.assertAlmostEqual(1200.0, units.mass.grams.to_milligrams(1.2), places=1)
		self.assertAlmostEqual(900.0, units.mass.grams.to_milligrams(0.9), places=1)
		self.assertAlmostEqual(2000.0, units.mass.grams.to_milligrams(2.0), places=1)

	def test_convert_known_grams_to_kilograms(self):
		self.assertAlmostEqual(0.9, units.mass.grams.to_kilograms(900.0), places=1)
		self.assertAlmostEqual(12.345, units.mass.grams.to_kilograms(12345.0), places=1)
		self.assertAlmostEqual(0.67, units.mass.grams.to_kilograms(670.0), places=1)

	def test_convert_known_grams_to_tonnes(self):
		self.assertAlmostEqual(6.7, units.mass.grams.to_tonnes(6700000.0), places=1)
		self.assertAlmostEqual(0.123456, units.mass.grams.to_tonnes(123456.0), places=1)
		self.assertAlmostEqual(9.809789, units.mass.grams.to_tonnes(9809789.0), places=1)

	def test_convert_known_grams_to_ounces(self):
		self.assertAlmostEqual(0.151678, units.mass.grams.to_ounces(4.3), places=1)
		self.assertAlmostEqual(5.99657, units.mass.grams.to_ounces(170.0), places=1)
		self.assertAlmostEqual(0.317466, units.mass.grams.to_ounces(9.0), places=1)

	def test_convert_known_grams_to_pounds(self):
		self.assertAlmostEqual(0.17637, units.mass.grams.to_pounds(80.0), places=1)
		self.assertAlmostEqual(0.418878, units.mass.grams.to_pounds(190.0), places=1)
		self.assertAlmostEqual(9.920802, units.mass.grams.to_pounds(4500.0), places=1)

	def test_convert_known_grams_to_stones(self):
		self.assertAlmostEqual(1.259784, units.mass.grams.to_stones(8000.0), places=1)
		self.assertAlmostEqual(1.9440047, units.mass.grams.to_stones(12345.0), places=1)
		self.assertAlmostEqual(0.141726, units.mass.grams.to_stones(900.0), places=1)

	def test_convert_known_grams_to_carats(self):
		self.assertAlmostEqual(615.0, units.mass.grams.to_carats(123.0), places=1)
		self.assertAlmostEqual(450.5, units.mass.grams.to_carats(90.1), places=1)
		self.assertAlmostEqual(25000.0, units.mass.grams.to_carats(5000.0), places=1)

if __name__ == '__main__':
    unittest.main()
