# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.data_transfer_rate.kilo_bytes_per_second

class TestKiloBytesPerSecondMethods(unittest.TestCase):

	def test_convert_known_kilo_bytes_per_second_to_bits_per_second(self):
		self.assertAlmostEqual(987648.0, units.data_transfer_rate.kilo_bytes_per_second.to_bits_per_second(123.456), places=1)
		self.assertAlmostEqual(7.2e+6, units.data_transfer_rate.kilo_bytes_per_second.to_bits_per_second(900.0), places=1)
		self.assertAlmostEqual(801600000.0, units.data_transfer_rate.kilo_bytes_per_second.to_bits_per_second(100200.0), places=1)

	def test_convert_known_kilo_bytes_per_second_to_kilo_bits_per_second(self):
		self.assertAlmostEqual(32.0, units.data_transfer_rate.kilo_bytes_per_second.to_kilo_bits_per_second(4.0), places=1)
		self.assertAlmostEqual(9.6, units.data_transfer_rate.kilo_bytes_per_second.to_kilo_bits_per_second(1.2), places=1)
		self.assertAlmostEqual(704.8, units.data_transfer_rate.kilo_bytes_per_second.to_kilo_bits_per_second(88.1), places=1)

	def test_convert_known_kilo_bytes_per_second_to_mega_bits_per_second(self):
		self.assertAlmostEqual(0.7048, units.data_transfer_rate.kilo_bytes_per_second.to_mega_bits_per_second(88.1), places=1)
		self.assertAlmostEqual(0.0568, units.data_transfer_rate.kilo_bytes_per_second.to_mega_bits_per_second(7.1), places=1)
		self.assertAlmostEqual(0.1024, units.data_transfer_rate.kilo_bytes_per_second.to_mega_bits_per_second(12.8), places=1)

	def test_convert_known_kilo_bytes_per_second_to_giga_bits_per_second(self):
		self.assertAlmostEqual(0.08064, units.data_transfer_rate.kilo_bytes_per_second.to_giga_bits_per_second(10080.0), places=1)
		self.assertAlmostEqual(36000.0, units.data_transfer_rate.kilo_bytes_per_second.to_giga_bits_per_second(4.5e+9), places=1)
		self.assertAlmostEqual(2.170232, units.data_transfer_rate.kilo_bytes_per_second.to_giga_bits_per_second(271279.0), places=1)

	def test_convert_known_kilo_bytes_per_second_to_tera_bits_per_second(self):
		self.assertAlmostEqual(0.072072, units.data_transfer_rate.kilo_bytes_per_second.to_tera_bits_per_second(9009000.0), places=1)
		self.assertAlmostEqual(57.6, units.data_transfer_rate.kilo_bytes_per_second.to_tera_bits_per_second(7.2e9), places=1)
		self.assertAlmostEqual(800.8008072, units.data_transfer_rate.kilo_bytes_per_second.to_tera_bits_per_second(100100100900.0), places=1)

	def test_convert_known_kilo_bytes_per_second_to_mega_bytes_per_second(self):
		self.assertAlmostEqual(1.009, units.data_transfer_rate.kilo_bytes_per_second.to_mega_bytes_per_second(1009.0), places=1)
		self.assertAlmostEqual(8.899, units.data_transfer_rate.kilo_bytes_per_second.to_mega_bytes_per_second(8899.0), places=1)
		self.assertAlmostEqual(0.619, units.data_transfer_rate.kilo_bytes_per_second.to_mega_bytes_per_second(619.0), places=1)

	def test_convert_known_kilo_bytes_per_second_to_giga_bytes_per_second(self):
		self.assertAlmostEqual(0.9008, units.data_transfer_rate.kilo_bytes_per_second.to_giga_bytes_per_second(900800.0), places=1)
		self.assertAlmostEqual(1.234567, units.data_transfer_rate.kilo_bytes_per_second.to_giga_bytes_per_second(1234567.0), places=1)
		self.assertAlmostEqual(7900.0, units.data_transfer_rate.kilo_bytes_per_second.to_giga_bytes_per_second(7.9e9), places=1)

	def test_convert_known_kilo_bytes_per_second_to_tera_bytes_per_second(self):
		self.assertAlmostEqual(9e-10, units.data_transfer_rate.kilo_bytes_per_second.to_tera_bytes_per_second(0.9), places=1)
		self.assertAlmostEqual(0.14, units.data_transfer_rate.kilo_bytes_per_second.to_tera_bytes_per_second(140000000.0), places=1)
		self.assertAlmostEqual(7e-9, units.data_transfer_rate.kilo_bytes_per_second.to_tera_bytes_per_second(7.0), places=1)

	def test_convert_known_kilo_bytes_per_second_to_kibibits_per_second(self):
		self.assertAlmostEqual(0.0703125, units.data_transfer_rate.kilo_bytes_per_second.to_kibibits_per_second(0.009), places=1)
		self.assertAlmostEqual(46872.0, units.data_transfer_rate.kilo_bytes_per_second.to_kibibits_per_second(6e+3), places=1)
		self.assertAlmostEqual(9.609375, units.data_transfer_rate.kilo_bytes_per_second.to_kibibits_per_second(1.23), places=1)

	def test_convert_known_kilo_bytes_per_second_to_mebibits_per_second(self):
		self.assertAlmostEqual(0.534058, units.data_transfer_rate.kilo_bytes_per_second.to_mebibits_per_second(70.0), places=1)
		self.assertAlmostEqual(0.0686646, units.data_transfer_rate.kilo_bytes_per_second.to_mebibits_per_second(9.0), places=1)
		self.assertAlmostEqual(76.461792, units.data_transfer_rate.kilo_bytes_per_second.to_mebibits_per_second(10022.0), places=1)

if __name__ == '__main__':
    unittest.main()
