# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.volume.pints

class TestPintsMethods(unittest.TestCase):

	def test_convert_known_pints_to_millilitres(self):
		self.assertAlmostEqual(397.783, units.volume.pints.to_millilitres(0.7), places=1)
		self.assertAlmostEqual(3182.26, units.volume.pints.to_millilitres(5.6), places=1)
		self.assertAlmostEqual(3409.57, units.volume.pints.to_millilitres(6.0), places=1)

	def test_convert_known_pints_to_litres(self):
		self.assertAlmostEqual(3.40957, units.volume.pints.to_litres(6.0), places=1)
		self.assertAlmostEqual(0.069896134, units.volume.pints.to_litres(0.123), places=1)
		self.assertAlmostEqual(26.08319, units.volume.pints.to_litres(45.9), places=1)

	def test_convert_known_pints_to_kilolitres(self):
		self.assertAlmostEqual(0.259127, units.volume.pints.to_kilolitres(456.0), places=1)
		self.assertAlmostEqual(5.9383301, units.volume.pints.to_kilolitres(10450.0), places=1)
		self.assertAlmostEqual(5.11486269, units.volume.pints.to_kilolitres(9000.9), places=1)

	def test_convert_known_pints_to_teaspoons(self):
		self.assertAlmostEqual(480.0, units.volume.pints.to_teaspoons(5.0), places=1)
		self.assertAlmostEqual(28.8, units.volume.pints.to_teaspoons(0.3), places=1)
		self.assertAlmostEqual(18240.0, units.volume.pints.to_teaspoons(190.0), places=1)

	def test_convert_known_pints_to_tablespoons(self):
		self.assertAlmostEqual(5984.0, units.volume.pints.to_tablespoons(187.0), places=1)
		self.assertAlmostEqual(1743.999, units.volume.pints.to_tablespoons(54.5), places=1)
		self.assertAlmostEqual(10.56, units.volume.pints.to_tablespoons(0.33), places=1)

	def test_convert_known_pints_to_quarts(self):
		self.assertAlmostEqual(2.8, units.volume.pints.to_quarts(5.6), places=1)
		self.assertAlmostEqual(54.5, units.volume.pints.to_quarts(109.0), places=1)
		self.assertAlmostEqual(0.15, units.volume.pints.to_quarts(0.3), places=1)

	def test_convert_known_pints_to_gallons(self):
		self.assertAlmostEqual(0.0375, units.volume.pints.to_gallons(0.3), places=1)
		self.assertAlmostEqual(100.0, units.volume.pints.to_gallons(800.0), places=1)
		self.assertAlmostEqual(0.1875, units.volume.pints.to_gallons(1.5), places=1)

	def test_convert_known_pints_to_fluid_ounces(self):
		self.assertAlmostEqual(30.0, units.volume.pints.to_fluid_ounces(1.5), places=1)
		self.assertAlmostEqual(15780.0, units.volume.pints.to_fluid_ounces(789.0), places=1)
		self.assertAlmostEqual(20416.0, units.volume.pints.to_fluid_ounces(1020.8), places=1)

	def test_convert_known_pints_to_u_s_teaspoons(self):
		self.assertAlmostEqual(117689.298303295, units.volume.pints.to_u_s_teaspoons(1020.8), places=1)
		self.assertAlmostEqual(46.1165, units.volume.pints.to_u_s_teaspoons(0.4), places=1)
		self.assertAlmostEqual(11990.2890120912, units.volume.pints.to_u_s_teaspoons(104.0), places=1)

	def test_convert_known_pints_to_u_s_tablespoons(self):
		self.assertAlmostEqual(3996.76, units.volume.pints.to_u_s_tablespoons(104.0), places=1)
		self.assertAlmostEqual(215.21, units.volume.pints.to_u_s_tablespoons(5.6), places=1)
		self.assertAlmostEqual(15.3722, units.volume.pints.to_u_s_tablespoons(0.4), places=1)

	def test_convert_known_pints_to_u_s_quarts(self):
		self.assertAlmostEqual(0.3302612, units.volume.pints.to_u_s_quarts(0.55), places=1)
		self.assertAlmostEqual(48.39828, units.volume.pints.to_u_s_quarts(80.6), places=1)
		self.assertAlmostEqual(7.2057, units.volume.pints.to_u_s_quarts(12.0), places=1)

	def test_convert_known_pints_to_u_s_pints(self):
		self.assertAlmostEqual(14.4114, units.volume.pints.to_u_s_pints(12.0), places=1)
		self.assertAlmostEqual(5.64446, units.volume.pints.to_u_s_pints(4.7), places=1)
		self.assertAlmostEqual(0.528418, units.volume.pints.to_u_s_pints(0.44), places=1)

	def test_convert_known_pints_to_u_s_gallons(self):
		self.assertAlmostEqual(0.180142, units.volume.pints.to_u_s_gallons(1.2), places=1)
		self.assertAlmostEqual(1351.069, units.volume.pints.to_u_s_gallons(9000.0), places=1)
		self.assertAlmostEqual(16.272871, units.volume.pints.to_u_s_gallons(108.4), places=1)

	def test_convert_known_pints_to_u_s_fluid_ounces(self):
		self.assertAlmostEqual(2075.24, units.volume.pints.to_u_s_fluid_ounces(108.0), places=1)
		self.assertAlmostEqual(449.6357, units.volume.pints.to_u_s_fluid_ounces(23.4), places=1)
		self.assertAlmostEqual(166.2115, units.volume.pints.to_u_s_fluid_ounces(8.65), places=1)

	def test_convert_known_pints_to_u_s_cups(self):
		self.assertAlmostEqual(55.2437, units.volume.pints.to_u_s_cups(23.0), places=1)
		self.assertAlmostEqual(7.2057, units.volume.pints.to_u_s_cups(3.0), places=1)
		self.assertAlmostEqual(121.5361, units.volume.pints.to_u_s_cups(50.6), places=1)

if __name__ == '__main__':
    unittest.main()
