# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.angle.degrees

class TestDegreesMethods(unittest.TestCase):

	def test_convert_known_degrees_to_radians(self):
		self.assertAlmostEqual(1.724385, units.angle.degrees.to_radians(98.8), places=1)
		self.assertAlmostEqual(139.6263, units.angle.degrees.to_radians(8000.0), places=1)
		self.assertAlmostEqual(0.139626, units.angle.degrees.to_radians(8.0), places=1)

	def test_convert_known_degrees_to_gradians(self):
		self.assertAlmostEqual(136.667, units.angle.degrees.to_gradians(123.0), places=1)
		self.assertAlmostEqual(72.2222, units.angle.degrees.to_gradians(65.0), places=1)
		self.assertAlmostEqual(1000.0, units.angle.degrees.to_gradians(900.0), places=1)

	def test_convert_known_degrees_to_milliradians(self):
		self.assertAlmostEqual(15707.969, units.angle.degrees.to_milliradians(900.0), places=1)
		self.assertAlmostEqual(1326.45, units.angle.degrees.to_milliradians(76.0), places=1)
		self.assertAlmostEqual(78.5398, units.angle.degrees.to_milliradians(4.5), places=1)
		self.assertAlmostEqual(407239.5873, units.angle.degrees.to_milliradians(23333.11), places=1)

	def test_convert_known_degrees_to_minute_of_arc(self):
		self.assertAlmostEqual(5820.0, units.angle.degrees.to_minute_of_arc(97.0), places=1)
		self.assertAlmostEqual(519.0, units.angle.degrees.to_minute_of_arc(8.65), places=1)
		self.assertAlmostEqual(720.0, units.angle.degrees.to_minute_of_arc(12.0), places=1)

	def test_convert_known_degrees_to_seconds_of_arc(self):
		self.assertAlmostEqual(43200.0, units.angle.degrees.to_seconds_of_arc(12.0), places=1)
		self.assertAlmostEqual(3277440.0, units.angle.degrees.to_seconds_of_arc(910.4), places=1)
		self.assertAlmostEqual(20160.0, units.angle.degrees.to_seconds_of_arc(5.6), places=1)

if __name__ == '__main__':
    unittest.main()
