# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.energy.kilocalories

class TestKilocaloriesMethods(unittest.TestCase):

	def test_convert_known_kilocalories_to_kilojoules(self):
		self.assertAlmostEqual(280.328, units.energy.kilocalories.to_kilojoules(67.0), places=1)
		self.assertAlmostEqual(18.828, units.energy.kilocalories.to_kilojoules(4.5), places=1)
		self.assertAlmostEqual(419.6552, units.energy.kilocalories.to_kilojoules(100.3), places=1)

	def test_convert_known_kilocalories_to_joules(self):
		self.assertAlmostEqual(419655.2, units.energy.kilocalories.to_joules(100.3), places=1)
		self.assertAlmostEqual(3765.6, units.energy.kilocalories.to_joules(0.9), places=1)
		self.assertAlmostEqual(14225.6, units.energy.kilocalories.to_joules(3.4), places=1)

	def test_convert_known_kilocalories_to_btu(self):
		self.assertAlmostEqual(13.4833, units.energy.kilocalories.to_btu(3.4), places=1)
		self.assertAlmostEqual(432.2576846216055, units.energy.kilocalories.to_btu(109.0), places=1)
		self.assertAlmostEqual(90.77411377053717, units.energy.kilocalories.to_btu(22.89), places=1)

	def test_convert_known_kilocalories_to_calories(self):
		self.assertAlmostEqual(22800.0, units.energy.kilocalories.to_calories(22.8), places=1)
		self.assertAlmostEqual(76230.0, units.energy.kilocalories.to_calories(76.23), places=1)
		self.assertAlmostEqual(70.0, units.energy.kilocalories.to_calories(0.07), places=1)

	def test_convert_known_kilocalories_to_u_s_therms(self):
		self.assertAlmostEqual(0.4896388, units.energy.kilocalories.to_u_s_therms(12345.0), places=1)
		self.assertAlmostEqual(3.5700317, units.energy.kilocalories.to_u_s_therms(90002.0), places=1)
		self.assertAlmostEqual(7.14704457, units.energy.kilocalories.to_u_s_therms(180180.0), places=1)

	def test_convert_known_kilocalories_to_watt_hours(self):
		self.assertAlmostEqual(103.438, units.energy.kilocalories.to_watt_hours(89.0), places=1)
		self.assertAlmostEqual(27.42844, units.energy.kilocalories.to_watt_hours(23.6), places=1)
		self.assertAlmostEqual(1.046, units.energy.kilocalories.to_watt_hours(0.9), places=1)

	def test_convert_known_kilocalories_to_kilowatt_hours(self):
		self.assertAlmostEqual(0.529973, units.energy.kilocalories.to_kilowatt_hours(456.0), places=1)
		self.assertAlmostEqual(1.267752, units.energy.kilocalories.to_kilowatt_hours(1090.8), places=1)
		self.assertAlmostEqual(0.65909622, units.energy.kilocalories.to_kilowatt_hours(567.1), places=1)

	def test_convert_known_kilocalories_to_foot_pounds(self):
		self.assertAlmostEqual(336369.64, units.energy.kilocalories.to_foot_pounds(109.0), places=1)
		self.assertAlmostEqual(1542.98, units.energy.kilocalories.to_foot_pounds(0.5), places=1)
		self.assertAlmostEqual(7406.3, units.energy.kilocalories.to_foot_pounds(2.4), places=1)

	def test_convert_known_kilocalories_to_electronvolts(self):
		self.assertAlmostEqual(1740388069688132.2, units.energy.kilocalories.to_electronvolts(0.0000000666), places=1)
		self.assertAlmostEqual(52263905996640608.0, units.energy.kilocalories.to_electronvolts(0.000002), places=1)
		self.assertAlmostEqual(26105821045321988.0, units.energy.kilocalories.to_electronvolts(0.000000999), places=1)

if __name__ == '__main__':
    unittest.main()
