# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.volume.quarts

class TestQuartsMethods(unittest.TestCase):

	def test_convert_known_quarts_to_millilitres(self):
		self.assertAlmostEqual(1591.13, units.volume.quarts.to_millilitres(1.4), places=1)
		self.assertAlmostEqual(909218.37579999, units.volume.quarts.to_millilitres(800.0), places=1)
		self.assertAlmostEqual(795.566, units.volume.quarts.to_millilitres(0.7), places=1)

	def test_convert_known_quarts_to_litres(self):
		self.assertAlmostEqual(767.153, units.volume.quarts.to_litres(675.0), places=1)
		self.assertAlmostEqual(52.05273, units.volume.quarts.to_litres(45.8), places=1)
		self.assertAlmostEqual(0.909218, units.volume.quarts.to_litres(0.8), places=1)

	def test_convert_known_quarts_to_kilolitres(self):
		self.assertAlmostEqual(9.102409, units.volume.quarts.to_kilolitres(8009.0), places=1)
		self.assertAlmostEqual(14.03037, units.volume.quarts.to_kilolitres(12345.0), places=1)
		self.assertAlmostEqual(0.68305, units.volume.quarts.to_kilolitres(601.0), places=1)

	def test_convert_known_quarts_to_teaspoons(self):
		self.assertAlmostEqual(1152.0, units.volume.quarts.to_teaspoons(6.0), places=1)
		self.assertAlmostEqual(172.8, units.volume.quarts.to_teaspoons(0.9), places=1)
		self.assertAlmostEqual(5.759998, units.volume.quarts.to_teaspoons(0.03), places=1)

	def test_convert_known_quarts_to_tablespoons(self):
		self.assertAlmostEqual(377.6, units.volume.quarts.to_tablespoons(5.9), places=1)
		self.assertAlmostEqual(21.75999, units.volume.quarts.to_tablespoons(0.34), places=1)
		self.assertAlmostEqual(185.6, units.volume.quarts.to_tablespoons(2.9), places=1)

	def test_convert_known_quarts_to_pints(self):
		self.assertAlmostEqual(9.0, units.volume.quarts.to_pints(4.5), places=1)
		self.assertAlmostEqual(205.6, units.volume.quarts.to_pints(102.8), places=1)
		self.assertAlmostEqual(0.92, units.volume.quarts.to_pints(0.46), places=1)

	def test_convert_known_quarts_to_gallons(self):
		self.assertAlmostEqual(0.115, units.volume.quarts.to_gallons(0.46), places=1)
		self.assertAlmostEqual(47.5, units.volume.quarts.to_gallons(190.0), places=1)
		self.assertAlmostEqual(16.9, units.volume.quarts.to_gallons(67.6), places=1)

	def test_convert_known_quarts_to_fluid_ounces(self):
		self.assertAlmostEqual(2704.0, units.volume.quarts.to_fluid_ounces(67.6), places=1)
		self.assertAlmostEqual(40360.0, units.volume.quarts.to_fluid_ounces(1009.0), places=1)
		self.assertAlmostEqual(248.0, units.volume.quarts.to_fluid_ounces(6.2), places=1)

	def test_convert_known_quarts_to_u_s_teaspoons(self):
		self.assertAlmostEqual(1429.61, units.volume.quarts.to_u_s_teaspoons(6.2), places=1)
		self.assertAlmostEqual(161.408, units.volume.quarts.to_u_s_teaspoons(0.7), places=1)
		self.assertAlmostEqual(18515.77, units.volume.quarts.to_u_s_teaspoons(80.3), places=1)

	def test_convert_known_quarts_to_u_s_tablespoons(self):
		self.assertAlmostEqual(6148.86, units.volume.quarts.to_u_s_tablespoons(80.0), places=1)
		self.assertAlmostEqual(438.107, units.volume.quarts.to_u_s_tablespoons(5.7), places=1)
		self.assertAlmostEqual(33.81875, units.volume.quarts.to_u_s_tablespoons(0.44), places=1)

	def test_convert_known_quarts_to_u_s_quarts(self):
		self.assertAlmostEqual(0.528418, units.volume.quarts.to_u_s_quarts(0.44), places=1)
		self.assertAlmostEqual(15.25206, units.volume.quarts.to_u_s_quarts(12.7), places=1)
		self.assertAlmostEqual(130.904, units.volume.quarts.to_u_s_quarts(109.0), places=1)

	def test_convert_known_quarts_to_u_s_pints(self):
		self.assertAlmostEqual(43.2342, units.volume.quarts.to_u_s_pints(18.0), places=1)
		self.assertAlmostEqual(6.00475, units.volume.quarts.to_u_s_pints(2.5), places=1)
		self.assertAlmostEqual(0.96076, units.volume.quarts.to_u_s_pints(0.4), places=1)

	def test_convert_known_quarts_to_u_s_gallons(self):
		self.assertAlmostEqual(1.44114, units.volume.quarts.to_u_s_gallons(4.8), places=1)
		self.assertAlmostEqual(0.0900712, units.volume.quarts.to_u_s_gallons(0.3), places=1)
		self.assertAlmostEqual(0.450356, units.volume.quarts.to_u_s_gallons(1.5), places=1)

	def test_convert_known_quarts_to_u_s_fluid_ounces(self):
		self.assertAlmostEqual(230.582, units.volume.quarts.to_u_s_fluid_ounces(6.0), places=1)
		self.assertAlmostEqual(17.67798, units.volume.quarts.to_u_s_fluid_ounces(0.46), places=1)
		self.assertAlmostEqual(76.8608, units.volume.quarts.to_u_s_fluid_ounces(2.0), places=1)

	def test_convert_known_quarts_to_u_s_cups(self):
		self.assertAlmostEqual(9.6076, units.volume.quarts.to_u_s_cups(2.0), places=1)
		self.assertAlmostEqual(3847.3632, units.volume.quarts.to_u_s_cups(800.9), places=1)
		self.assertAlmostEqual(1.104874, units.volume.quarts.to_u_s_cups(0.23), places=1)

	def test_convert_known_quarts_to_cubic_metres(self):
		self.assertAlmostEqual(9.0, units.volume.quarts.to_cubic_metres(7918.89), places=1)
		self.assertAlmostEqual(1.363827, units.volume.quarts.to_cubic_metres(1200.0), places=1)
		self.assertAlmostEqual(9.09218, units.volume.quarts.to_cubic_metres(8000.0), places=1)

	def test_convert_known_quarts_to_cubic_feet(self):
		self.assertAlmostEqual(0.802718, units.volume.quarts.to_cubic_feet(20.0), places=1)
		self.assertAlmostEqual(32.1087, units.volume.quarts.to_cubic_feet(800.0), places=1)
		self.assertAlmostEqual(2.68911, units.volume.quarts.to_cubic_feet(67.0), places=1)

	def test_convert_known_quarts_to_cubic_inches(self):
		self.assertAlmostEqual(53888.75729, units.volume.quarts.to_cubic_inches(777.0), places=1)
		self.assertAlmostEqual(566.0, units.volume.quarts.to_cubic_inches(8.16093), places=1)
		self.assertAlmostEqual(5270.97, units.volume.quarts.to_cubic_inches(76.0), places=1)

	def test_convert_known_quarts_to_oil_barrels(self):
		self.assertAlmostEqual(6.0, units.volume.quarts.to_oil_barrels(839.336), places=1)
		self.assertAlmostEqual(0.3, units.volume.quarts.to_oil_barrels(41.9668), places=1)
		self.assertAlmostEqual(0.157267, units.volume.quarts.to_oil_barrels(22.0), places=1)

if __name__ == '__main__':
    unittest.main()
