# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.length.nautical_miles

class TestNauticalMilesMethods(unittest.TestCase):

	def test_convert_known_nautical_miles_to_millimetres(self):
		self.assertAlmostEqual(148160.0, units.length.nautical_miles.to_millimetres(0.08), places=1)
		self.assertAlmostEqual(1852.0, units.length.nautical_miles.to_millimetres(0.001), places=1)
		self.assertAlmostEqual(37040.0, units.length.nautical_miles.to_millimetres(0.02), places=1)

	def test_convert_known_nautical_miles_to_centimetres(self):
		self.assertAlmostEqual(166680.0, units.length.nautical_miles.to_centimetres(0.9), places=1)
		self.assertAlmostEqual(222240.0, units.length.nautical_miles.to_centimetres(1.2), places=1)
		self.assertAlmostEqual(18520.0, units.length.nautical_miles.to_centimetres(0.1), places=1)

	def test_convert_known_nautical_miles_to_metres(self):
		self.assertAlmostEqual(185.2, units.length.nautical_miles.to_metres(0.1), places=1)
		self.assertAlmostEqual(2222.4, units.length.nautical_miles.to_metres(1.2), places=1)
		self.assertAlmostEqual(164828.0, units.length.nautical_miles.to_metres(89.0), places=1)

	def test_convert_known_nautical_miles_to_kilometres(self):
		self.assertAlmostEqual(42.596, units.length.nautical_miles.to_kilometres(23.0), places=1)
		self.assertAlmostEqual(3.1484, units.length.nautical_miles.to_kilometres(1.7), places=1)
		self.assertAlmostEqual(103.712, units.length.nautical_miles.to_kilometres(56.0), places=1)

	def test_convert_known_nautical_miles_to_inches(self):
		self.assertAlmostEqual(7291.34, units.length.nautical_miles.to_inches(0.1), places=1)
		self.assertAlmostEqual(145826.7999, units.length.nautical_miles.to_inches(2.0), places=1)
		self.assertAlmostEqual(255196.899, units.length.nautical_miles.to_inches(3.5), places=1)

	def test_convert_known_nautical_miles_to_feet(self):
		self.assertAlmostEqual(8506.56, units.length.nautical_miles.to_feet(1.4), places=1)
		self.assertAlmostEqual(607.612, units.length.nautical_miles.to_feet(0.1), places=1)
		self.assertAlmostEqual(54077.4680, units.length.nautical_miles.to_feet(8.9), places=1)

	def test_convert_known_nautical_miles_to_yards(self):
		self.assertAlmostEqual(18228.329, units.length.nautical_miles.to_yards(9.0), places=1)
		self.assertAlmostEqual(3038.06, units.length.nautical_miles.to_yards(1.5), places=1)
		self.assertAlmostEqual(1620.3, units.length.nautical_miles.to_yards(0.8), places=1)

	def test_convert_known_nautical_miles_to_miles(self):
		self.assertAlmostEqual(0.57539, units.length.nautical_miles.to_miles(0.5), places=1)
		self.assertAlmostEqual(26.4679, units.length.nautical_miles.to_miles(23.0), places=1)
		self.assertAlmostEqual(9.43639, units.length.nautical_miles.to_miles(8.2), places=1)

if __name__ == '__main__':
    unittest.main()
