# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.area.square_yards

class TestSquareYardsMethods(unittest.TestCase):

	def test_convert_known_square_yards_to_square_kilometres(self):
		self.assertAlmostEqual(0.752514624, units.area.square_yards.to_square_kilometres(900000.0), places=1)
		self.assertAlmostEqual(0.159023063, units.area.square_yards.to_square_kilometres(190190.0), places=1)
		self.assertAlmostEqual(5.85289152, units.area.square_yards.to_square_kilometres(7000000.0), places=1)

	def test_convert_known_square_yards_to_square_metres(self):
		self.assertAlmostEqual(585.289, units.area.square_yards.to_square_metres(700.0), places=1)
		self.assertAlmostEqual(10.0335, units.area.square_yards.to_square_metres(12.0), places=1)
		self.assertAlmostEqual(7.60876, units.area.square_yards.to_square_metres(9.1), places=1)

	def test_convert_known_square_yards_to_square_miles(self):
		self.assertAlmostEqual(0.031863378, units.area.square_yards.to_square_miles(98700.0), places=1)
		self.assertAlmostEqual(2.869604855, units.area.square_yards.to_square_miles(8888888.0), places=1)
		self.assertAlmostEqual(32.3477208161, units.area.square_yards.to_square_miles(100200300.0), places=1)

	def test_convert_known_square_yards_to_square_feet(self):
		self.assertAlmostEqual(108.0, units.area.square_yards.to_square_feet(12.0), places=1)
		self.assertAlmostEqual(50.4, units.area.square_yards.to_square_feet(5.6), places=1)
		self.assertAlmostEqual(922.5, units.area.square_yards.to_square_feet(102.5), places=1)

	def test_convert_known_square_yards_to_square_inches(self):
		self.assertAlmostEqual(73483.2, units.area.square_yards.to_square_inches(56.7), places=1)
		self.assertAlmostEqual(2332.8, units.area.square_yards.to_square_inches(1.8), places=1)
		self.assertAlmostEqual(259.2, units.area.square_yards.to_square_inches(0.2), places=1)

	def test_convert_known_square_yards_to_hectares(self):
		self.assertAlmostEqual(0.84365251, units.area.square_yards.to_hectares(10090.0), places=1)
		self.assertAlmostEqual(8.2580119, units.area.square_yards.to_hectares(98765.0), places=1)
		self.assertAlmostEqual(0.2583634, units.area.square_yards.to_hectares(3090.09), places=1)

	def test_convert_known_square_yards_to_acres(self):
		self.assertAlmostEqual(0.206612, units.area.square_yards.to_acres(1000.0), places=1)
		self.assertAlmostEqual(0.185744, units.area.square_yards.to_acres(899.0), places=1)
		self.assertAlmostEqual(1.17314, units.area.square_yards.to_acres(5678.0), places=1)

if __name__ == '__main__':
    unittest.main()
