# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.volume.cubic_feet

class TestCubicFeetMethods(unittest.TestCase):

	def test_convert_known_cubic_feet_to_millilitres(self):
		self.assertAlmostEqual(2265.348, units.volume.cubic_feet.to_millilitres(0.08), places=1)
		self.assertAlmostEqual(169900.79, units.volume.cubic_feet.to_millilitres(6.0), places=1)
		self.assertAlmostEqual(6776.988, units.volume.cubic_feet.to_millilitres(0.2393275), places=1)

	def test_convert_known_cubic_feet_to_litres(self):
		self.assertAlmostEqual(8.49505, units.volume.cubic_feet.to_litres(0.3), places=1)
		self.assertAlmostEqual(169.901, units.volume.cubic_feet.to_litres(6.0), places=1)
		self.assertAlmostEqual(1585.74, units.volume.cubic_feet.to_litres(56.0), places=1)

	def test_convert_known_cubic_feet_to_kilolitres(self):
		self.assertAlmostEqual(8.49505, units.volume.cubic_feet.to_kilolitres(300.0), places=1)
		self.assertAlmostEqual(4.0, units.volume.cubic_feet.to_kilolitres(141.259), places=1)
		self.assertAlmostEqual(3.14317, units.volume.cubic_feet.to_kilolitres(111.0), places=1)

	def test_convert_known_cubic_feet_to_teaspoons(self):
		self.assertAlmostEqual(1435.12, units.volume.cubic_feet.to_teaspoons(0.3), places=1)
		self.assertAlmostEqual(19134.95, units.volume.cubic_feet.to_teaspoons(4.0), places=1)
		self.assertAlmostEqual(320510.579, units.volume.cubic_feet.to_teaspoons(67.0), places=1)

	def test_convert_known_cubic_feet_to_tablespoons(self):
		self.assertAlmostEqual(1116.21, units.volume.cubic_feet.to_tablespoons(0.7), places=1)
		self.assertAlmostEqual(1754.04, units.volume.cubic_feet.to_tablespoons(1.1), places=1)
		self.assertAlmostEqual(788.0, units.volume.cubic_feet.to_tablespoons(0.494174), places=1)

	def test_convert_known_cubic_feet_to_quarts(self):
		self.assertAlmostEqual(14.9492, units.volume.cubic_feet.to_quarts(0.6), places=1)
		self.assertAlmostEqual(5.0, units.volume.cubic_feet.to_quarts(0.20068), places=1)
		self.assertAlmostEqual(7.5, units.volume.cubic_feet.to_quarts(0.301019), places=1)

	def test_convert_known_cubic_feet_to_pints(self):
		self.assertAlmostEqual(29.8984, units.volume.cubic_feet.to_pints(0.6), places=1)
		self.assertAlmostEqual(44.0, units.volume.cubic_feet.to_pints(0.88299), places=1)
		self.assertAlmostEqual(900.0, units.volume.cubic_feet.to_pints(18.0612), places=1)

	def test_convert_known_cubic_feet_to_gallons(self):
		self.assertAlmostEqual(18.6865, units.volume.cubic_feet.to_gallons(3.0), places=1)
		self.assertAlmostEqual(13.0, units.volume.cubic_feet.to_gallons(2.08707), places=1)
		self.assertAlmostEqual(88.0, units.volume.cubic_feet.to_gallons(14.1278), places=1)

	def test_convert_known_cubic_feet_to_fluid_ounces(self):
		self.assertAlmostEqual(13952.6, units.volume.cubic_feet.to_fluid_ounces(14.0), places=1)
		self.assertAlmostEqual(6976.3, units.volume.cubic_feet.to_fluid_ounces(7.0), places=1)
		self.assertAlmostEqual(346.6, units.volume.cubic_feet.to_fluid_ounces(0.34777769), places=1)

	def test_convert_known_cubic_feet_to_u_s_teaspoons(self):
		self.assertAlmostEqual(28725.2, units.volume.cubic_feet.to_u_s_teaspoons(5.0), places=1)
		self.assertAlmostEqual(2298.02, units.volume.cubic_feet.to_u_s_teaspoons(0.4), places=1)
		self.assertAlmostEqual(52854.3679, units.volume.cubic_feet.to_u_s_teaspoons(9.2), places=1)

	def test_convert_known_cubic_feet_to_u_s_tablespoons(self):
		self.assertAlmostEqual(2681.02, units.volume.cubic_feet.to_u_s_tablespoons(1.4), places=1)
		self.assertAlmostEqual(7660.04, units.volume.cubic_feet.to_u_s_tablespoons(4.0), places=1)
		self.assertAlmostEqual(1234.0, units.volume.cubic_feet.to_u_s_tablespoons(0.6443821), places=1)

	def test_convert_known_cubic_feet_to_u_s_quarts(self):
		self.assertAlmostEqual(179.532, units.volume.cubic_feet.to_u_s_quarts(6.0), places=1)
		self.assertAlmostEqual(359.065, units.volume.cubic_feet.to_u_s_quarts(12.0), places=1)
		self.assertAlmostEqual(777.0, units.volume.cubic_feet.to_u_s_quarts(25.9674), places=1)

	def test_convert_known_cubic_feet_to_u_s_pints(self):
		self.assertAlmostEqual(412.925, units.volume.cubic_feet.to_u_s_pints(6.9), places=1)
		self.assertAlmostEqual(1376.42, units.volume.cubic_feet.to_u_s_pints(23.0), places=1)
		self.assertAlmostEqual(888.0, units.volume.cubic_feet.to_u_s_pints(14.8385), places=1)

	def test_convert_known_cubic_feet_to_u_s_gallons(self):
		self.assertAlmostEqual(576.0, units.volume.cubic_feet.to_u_s_gallons(77.0), places=1)
		self.assertAlmostEqual(336.623, units.volume.cubic_feet.to_u_s_gallons(45.0), places=1)
		self.assertAlmostEqual(29.9221, units.volume.cubic_feet.to_u_s_gallons(4.0), places=1)

	def test_convert_known_cubic_feet_to_u_s_fluid_ounces(self):
		self.assertAlmostEqual(19150.119, units.volume.cubic_feet.to_u_s_fluid_ounces(20.0), places=1)
		self.assertAlmostEqual(344.0, units.volume.cubic_feet.to_u_s_fluid_ounces(0.359266), places=1)
		self.assertAlmostEqual(670.0, units.volume.cubic_feet.to_u_s_fluid_ounces(0.699734), places=1)

	def test_convert_known_cubic_feet_to_u_s_cups(self):
		self.assertAlmostEqual(9084.99, units.volume.cubic_feet.to_u_s_cups(77.0), places=1)
		self.assertAlmostEqual(943.895, units.volume.cubic_feet.to_u_s_cups(8.0), places=1)
		self.assertAlmostEqual(566.0, units.volume.cubic_feet.to_u_s_cups(4.79714), places=1)

	def test_convert_known_cubic_feet_to_cubic_metres(self):
		self.assertAlmostEqual(0.8, units.volume.cubic_feet.to_cubic_metres(28.2517), places=1)
		self.assertAlmostEqual(1.27426, units.volume.cubic_feet.to_cubic_metres(45.0), places=1)
		self.assertAlmostEqual(77.0, units.volume.cubic_feet.to_cubic_metres(2719.23), places=1)

	def test_convert_known_cubic_feet_to_cubic_inches(self):
		self.assertAlmostEqual(11750.4, units.volume.cubic_feet.to_cubic_inches(6.8), places=1)
		self.assertAlmostEqual(9790848.0, units.volume.cubic_feet.to_cubic_inches(5666.0), places=1)
		self.assertAlmostEqual(1209.6, units.volume.cubic_feet.to_cubic_inches(0.7), places=1)

	def test_convert_known_cubic_feet_to_oil_barrels(self):
		self.assertAlmostEqual(11.9332, units.volume.cubic_feet.to_oil_barrels(67.0), places=1)
		self.assertAlmostEqual(7.83673, units.volume.cubic_feet.to_oil_barrels(44.0), places=1)
		self.assertAlmostEqual(12.0, units.volume.cubic_feet.to_oil_barrels(67.375), places=1)

if __name__ == '__main__':
    unittest.main()
