# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.pressure.dynes

class TestDynesMethods(unittest.TestCase):

	def test_convert_known_dynes_to_newtons(self):
		self.assertAlmostEqual(0.009, units.pressure.dynes.to_newtons(900.0), places=1)
		self.assertAlmostEqual(0.01234, units.pressure.dynes.to_newtons(1234.0), places=1)
		self.assertAlmostEqual(0.00046, units.pressure.dynes.to_newtons(46.0), places=1)

if __name__ == '__main__':
    unittest.main()
