# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.area.square_miles

class TestSquareMilesMethods(unittest.TestCase):

	def test_convert_known_square_miles_to_square_kilometres(self):
		self.assertAlmostEqual(7.76996, units.area.square_miles.to_square_kilometres(3.0), places=1)
		self.assertAlmostEqual(2.33099, units.area.square_miles.to_square_kilometres(0.9), places=1)
		self.assertAlmostEqual(258.999, units.area.square_miles.to_square_kilometres(100.0), places=1)

	def test_convert_known_square_miles_to_square_metres(self):
		self.assertAlmostEqual(23309.893, units.area.square_miles.to_square_metres(0.009), places=1)
		self.assertAlmostEqual(25899.88, units.area.square_miles.to_square_metres(0.010), places=1)
		self.assertAlmostEqual(1553.99287, units.area.square_miles.to_square_metres(0.0006), places=1)

	def test_convert_known_square_miles_to_square_yards(self):
		self.assertAlmostEqual(30976.0, units.area.square_miles.to_square_yards(0.01), places=1)
		self.assertAlmostEqual(3810.048, units.area.square_miles.to_square_yards(0.00123), places=1)
		self.assertAlmostEqual(278784.0, units.area.square_miles.to_square_yards(0.09), places=1)

	def test_convert_known_square_miles_to_square_feet(self):
		self.assertAlmostEqual(278784.0, units.area.square_miles.to_square_feet(0.01), places=1)
		self.assertAlmostEqual(139392.0, units.area.square_miles.to_square_feet(0.005), places=1)
		self.assertAlmostEqual(2230272.0, units.area.square_miles.to_square_feet(0.08), places=1)

	def test_convert_known_square_miles_to_square_inches(self):
		self.assertAlmostEqual(401448.96, units.area.square_miles.to_square_inches(0.0001), places=1)
		self.assertAlmostEqual(3934199.808, units.area.square_miles.to_square_inches(0.00098), places=1)
		self.assertAlmostEqual(28101.4272, units.area.square_miles.to_square_inches(0.000007), places=1)

	def test_convert_known_square_miles_to_hectares(self):
		self.assertAlmostEqual(25899.881103, units.area.square_miles.to_hectares(100.0), places=1)
		self.assertAlmostEqual(595.697, units.area.square_miles.to_hectares(2.3), places=1)
		self.assertAlmostEqual(233.099, units.area.square_miles.to_hectares(0.9), places=1)

	def test_convert_known_square_miles_to_acres(self):
		self.assertAlmostEqual(1280.0, units.area.square_miles.to_acres(2.0), places=1)
		self.assertAlmostEqual(64.0, units.area.square_miles.to_acres(0.1), places=1)
		self.assertAlmostEqual(2944.0, units.area.square_miles.to_acres(4.6), places=1)

if __name__ == '__main__':
    unittest.main()
