# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.volume.cubic_inches

class TestCubicInchesMethods(unittest.TestCase):

	def test_convert_known_cubic_inches_to_millilitres(self):
		self.assertAlmostEqual(63.9095, units.volume.cubic_inches.to_millilitres(3.9), places=1)
		self.assertAlmostEqual(65.5483, units.volume.cubic_inches.to_millilitres(4.0), places=1)
		self.assertAlmostEqual(88.0, units.volume.cubic_inches.to_millilitres(5.37009), places=1)

	def test_convert_known_cubic_inches_to_litres(self):
		self.assertAlmostEqual(9.17676, units.volume.cubic_inches.to_litres(560.0), places=1)
		self.assertAlmostEqual(9.09482, units.volume.cubic_inches.to_litres(555.0), places=1)
		self.assertAlmostEqual(122.0, units.volume.cubic_inches.to_litres(7444.9), places=1)

	def test_convert_known_cubic_inches_to_kilolitres(self):
		self.assertAlmostEqual(0.009176, units.volume.cubic_inches.to_kilolitres(560.0), places=1)
		self.assertAlmostEqual(0.09103014, units.volume.cubic_inches.to_kilolitres(5555.0), places=1)
		self.assertAlmostEqual(1.6387064, units.volume.cubic_inches.to_kilolitres(100000.0), places=1)

	def test_convert_known_cubic_inches_to_teaspoons(self):
		self.assertAlmostEqual(13.8419, units.volume.cubic_inches.to_teaspoons(5.0), places=1)
		self.assertAlmostEqual(16.6102, units.volume.cubic_inches.to_teaspoons(6.0), places=1)
		self.assertAlmostEqual(32.0, units.volume.cubic_inches.to_teaspoons(11.5591), places=1)

	def test_convert_known_cubic_inches_to_tablespoons(self):
		self.assertAlmostEqual(31.3749, units.volume.cubic_inches.to_tablespoons(34.0), places=1)
		self.assertAlmostEqual(11.0, units.volume.cubic_inches.to_tablespoons(11.9204), places=1)
		self.assertAlmostEqual(91.3562246, units.volume.cubic_inches.to_tablespoons(99.0), places=1)

	def test_convert_known_cubic_inches_to_quarts(self):
		self.assertAlmostEqual(11.5349, units.volume.cubic_inches.to_quarts(800.0), places=1)
		self.assertAlmostEqual(1.11023, units.volume.cubic_inches.to_quarts(77.0), places=1)
		self.assertAlmostEqual(66.0, units.volume.cubic_inches.to_quarts(4577.42), places=1)

	def test_convert_known_cubic_inches_to_pints(self):
		self.assertAlmostEqual(2.58093, units.volume.cubic_inches.to_pints(89.5), places=1)
		self.assertAlmostEqual(666.0, units.volume.cubic_inches.to_pints(23095.2), places=1)
		self.assertAlmostEqual(77.0, units.volume.cubic_inches.to_pints(2670.16), places=1)

	def test_convert_known_cubic_inches_to_gallons(self):
		self.assertAlmostEqual(3.24419, units.volume.cubic_inches.to_gallons(900.0), places=1)
		self.assertAlmostEqual(2.4007, units.volume.cubic_inches.to_gallons(666.0), places=1)
		self.assertAlmostEqual(77.0, units.volume.cubic_inches.to_gallons(21361.3), places=1)

	def test_convert_known_cubic_inches_to_fluid_ounces(self):
		self.assertAlmostEqual(44.4093, units.volume.cubic_inches.to_fluid_ounces(77.0), places=1)
		self.assertAlmostEqual(31.7209, units.volume.cubic_inches.to_fluid_ounces(55.0), places=1)
		self.assertAlmostEqual(16.0, units.volume.cubic_inches.to_fluid_ounces(27.7419), places=1)

	def test_convert_known_cubic_inches_to_u_s_teaspoons(self):
		self.assertAlmostEqual(2254.13, units.volume.cubic_inches.to_u_s_teaspoons(678.0), places=1)
		self.assertAlmostEqual(182.857, units.volume.cubic_inches.to_u_s_teaspoons(55.0), places=1)
		self.assertAlmostEqual(88.0, units.volume.cubic_inches.to_u_s_teaspoons(26.4687), places=1)

	def test_convert_known_cubic_inches_to_u_s_tablespoons(self):
		self.assertAlmostEqual(73.1429, units.volume.cubic_inches.to_u_s_tablespoons(66.0), places=1)
		self.assertAlmostEqual(60.9524, units.volume.cubic_inches.to_u_s_tablespoons(55.0), places=1)
		self.assertAlmostEqual(12.0, units.volume.cubic_inches.to_u_s_tablespoons(10.8281), places=1)

	def test_convert_known_cubic_inches_to_u_s_quarts(self):
		self.assertAlmostEqual(5.97403, units.volume.cubic_inches.to_u_s_quarts(345.0), places=1)
		self.assertAlmostEqual(0.571429, units.volume.cubic_inches.to_u_s_quarts(33.0), places=1)
		self.assertAlmostEqual(55.0, units.volume.cubic_inches.to_u_s_quarts(3176.25), places=1)

	def test_convert_known_cubic_inches_to_u_s_pints(self):
		self.assertAlmostEqual(3.08225, units.volume.cubic_inches.to_u_s_pints(89.0), places=1)
		self.assertAlmostEqual(110.0, units.volume.cubic_inches.to_u_s_pints(3176.25), places=1)
		self.assertAlmostEqual(16.0, units.volume.cubic_inches.to_u_s_pints(462.0), places=1)

	def test_convert_known_cubic_inches_to_u_s_gallons(self):
		self.assertAlmostEqual(2.5974, units.volume.cubic_inches.to_u_s_gallons(600.0), places=1)
		self.assertAlmostEqual(2.0, units.volume.cubic_inches.to_u_s_gallons(462), places=1)
		self.assertAlmostEqual(3.89177, units.volume.cubic_inches.to_u_s_gallons(899.0), places=1)

	def test_convert_known_cubic_inches_to_u_s_fluid_ounces(self):
		self.assertAlmostEqual(498.700607, units.volume.cubic_inches.to_u_s_fluid_ounces(900.0), places=1)
		self.assertAlmostEqual(430.544858, units.volume.cubic_inches.to_u_s_fluid_ounces(777.0), places=1)
		self.assertAlmostEqual(98.99982822, units.volume.cubic_inches.to_u_s_fluid_ounces(178.664), places=1)

	def test_convert_known_cubic_inches_to_u_s_cups(self):
		self.assertAlmostEqual(0.477956, units.volume.cubic_inches.to_u_s_cups(7.0), places=1)
		self.assertAlmostEqual(5.25752, units.volume.cubic_inches.to_u_s_cups(77.0), places=1)
		self.assertAlmostEqual(8.39837, units.volume.cubic_inches.to_u_s_cups(123.0), places=1)

	def test_convert_known_cubic_inches_to_cubic_metres(self):
		self.assertAlmostEqual(0.4, units.volume.cubic_inches.to_cubic_metres(24409.5), places=1)
		self.assertAlmostEqual(0.1274422, units.volume.cubic_inches.to_cubic_metres(7777.0), places=1)
		self.assertAlmostEqual(6.0, units.volume.cubic_inches.to_cubic_metres(366142), places=1)

	def test_convert_known_cubic_inches_to_cubic_feet(self):
		self.assertAlmostEqual(6.8, units.volume.cubic_inches.to_cubic_feet(11750.4), places=1)
		self.assertAlmostEqual(33.0, units.volume.cubic_inches.to_cubic_feet(57024.0), places=1)
		self.assertAlmostEqual(0.7141204, units.volume.cubic_inches.to_cubic_feet(1234.0), places=1)

	def test_convert_known_cubic_inches_to_oil_barrels(self):
		self.assertAlmostEqual(9.2764378, units.volume.cubic_inches.to_oil_barrels(90000.0), places=1)
		self.assertAlmostEqual(0.9160998, units.volume.cubic_inches.to_oil_barrels(8888.0), places=1)
		self.assertAlmostEqual(1.2, units.volume.cubic_inches.to_oil_barrels(11642.4), places=1)

if __name__ == '__main__':
    unittest.main()
