# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.time.seconds

class TestSecondsMethods(unittest.TestCase):

	def test_convert_known_seconds_to_milliseconds(self):
		self.assertAlmostEqual(9000.0, units.time.seconds.to_milliseconds(9.0), places=1)
		self.assertAlmostEqual(3100.0, units.time.seconds.to_milliseconds(3.1), places=1)
		self.assertAlmostEqual(900.0, units.time.seconds.to_milliseconds(0.9), places=1)

	def test_convert_known_seconds_to_minutes(self):
		self.assertAlmostEqual(1.66667, units.time.seconds.to_minutes(100.0), places=1)
		self.assertAlmostEqual(150.0, units.time.seconds.to_minutes(9000.0), places=1)
		self.assertAlmostEqual(38.33333, units.time.seconds.to_minutes(2300.0), places=1)

	def test_convert_known_seconds_to_hours(self):
		self.assertAlmostEqual(0.6388889, units.time.seconds.to_hours(2300.0), places=1)
		self.assertAlmostEqual(2.7775, units.time.seconds.to_hours(9999.0), places=1)
		self.assertAlmostEqual(10.0, units.time.seconds.to_hours(36000.0), places=1)

	def test_convert_known_seconds_to_days(self):
		self.assertAlmostEqual(0.41666667, units.time.seconds.to_days(36000.0), places=1)
		self.assertAlmostEqual(1.0416667, units.time.seconds.to_days(90000.0), places=1)
		self.assertAlmostEqual(2.19907407, units.time.seconds.to_days(190000.0), places=1)

	def test_convert_known_seconds_to_weeks(self):
		self.assertAlmostEqual(0.314153439, units.time.seconds.to_weeks(190000.0), places=1)
		self.assertAlmostEqual(2.041281415, units.time.seconds.to_weeks(1234567.0), places=1)
		self.assertAlmostEqual(0.165674603, units.time.seconds.to_weeks(100200.0), places=1)

	def test_convert_known_seconds_to_months(self):
		self.assertAlmostEqual(0.380517087, units.time.seconds.to_months(1000000.0), places=1)
		self.assertAlmostEqual(3.75819337, units.time.seconds.to_months(9876543.0), places=1)
		self.assertAlmostEqual(0.0764458827, units.time.seconds.to_months(200900.0), places=1)

	def test_convert_known_seconds_to_years(self):
		self.assertAlmostEqual(3.91478909817, units.time.seconds.to_years(123456789.0), places=1)
		self.assertAlmostEqual(0.00319951801, units.time.seconds.to_years(100900.0), places=1)
		self.assertAlmostEqual(0.0313183029, units.time.seconds.to_years(987654.0), places=1)

if __name__ == '__main__':
    unittest.main()
