# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

import unittest
import units.magnetomotive_force.gilberts

class TestGilbertsMethods(unittest.TestCase):

	def test_convert_known_gilberts_to_ampereturns(self):
		self.assertAlmostEqual(0.6366197721, units.magnetomotive_force.gilberts.to_ampereturns(0.8), places=1)
		self.assertAlmostEqual(53.316905912, units.magnetomotive_force.gilberts.to_ampereturns(67.0), places=1)
		self.assertAlmostEqual(1.8302818447, units.magnetomotive_force.gilberts.to_ampereturns(2.3), places=1)

if __name__ == '__main__':
    unittest.main()
