# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_newtons(value): 
	return value / 100000.0
def to_poundals(value): 
	return value / 13825.4954376
def to_kilogramforce(value): 
	return value / 980665.0

