# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_newtons(value): 
	return value * 9.80665
def to_dynes(value): 
	return value * 980665.0
def to_poundals(value): 
	return value * 70.93163528397

