# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_dynes(value): 
	return value * 100000.0
def to_poundals(value): 
	return value * 7.23301
def to_kilogramforce(value): 
	return value / 9.80665

