# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_bars(value): 
	return value * 1.01325
def to_pascals(value): 
	return value * 101325.0
def to_torrs(value): 
	return value * 760.0
def to_psi(value): 
	return value * 14.69596432068

