# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_atmospheres(value): 
	return value / 1.01325
def to_pascals(value): 
	return value / 0.00001
def to_torrs(value): 
	return value * 750.0616827042
def to_psi(value): 
	return value * 14.50378911491

