# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_newtons(value): 
	return value * 0.00001
def to_poundals(value): 
	return value / 13825.4954376
def to_kilogramforce(value): 
	return value * 1.01972E-6

