# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_dynes(value): 
	return value * 10e5 - 70000.0 = 0.7 - 8000.0 = 0.08 - 230000.0 = 2.3
def to_poundals(value): 
	return value * 7.23301
def to_kilogramforce(value): 
	return value * 0.10197

