# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_atmospheres(value): 
	return value / 101325.0
def to_bars(value): 
	return value * 0.00001
def to_torrs(value): 
	return value * 0.007500616827042
def to_psi(value): 
	return value * 0.0001450378911491

