# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_newtons(value): 
	return value * 0.1382549544
def to_dynes(value): 
	return value * 13825.4954376
def to_kilogramforce(value): 
	return value * 0.01409808185017
