# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_bars(value): 
	return value / 14.50378911491
def to_pascals(value): 
	return value / 0.0001450378911491
def to_atmospheres(value): 
	return value / 14.69596432068
def to_torrs(value): 
	return value / 0.01933679515879

