# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_bars(value): 
	return value / 750.0616827042
def to_pascals(value): 
	return value / 0.007500616827042
def to_atmospheres(value): 
	return value / 760.0
def to_psi(value): 
	return value * 0.01933679515879
