# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_talbot(value): 
	return value * 60.0
def to_lumen_hour(value): 
	return value / 60.0
def to_lumen_second(value): 
	return value * 60.0

