# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_hertz(value): 
	return value * 1e+6
def to_kilohertz(value): 
	return value * 1000.0
def to_gigahertz(value): 
	return value / 1000.0
