# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_milligrams(value): 
	return value * 1000.0
def to_kilograms(value): 
	return value / 1000.0
def to_tonnes(value): 
	return value * 1e-6
def to_ounces(value): 
	return value / 28.3495231
def to_pounds(value): 
	return value / 453.59237
def to_stones(value): 
	return value / 6350.29318
def to_carats(value): 
	return value * 5.0

