# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_milligrams(value): 
	return value * 1e+6
def to_grams(value): 
	return value * 1000.0
def to_tonnes(value): 
	return value * 0.001
def to_ounces(value): 
	return value * 35.274
def to_pounds(value): 
	return value * 2.20462
def to_stones(value): 
	return value / 6.35029
def to_carats(value): 
	return value * 5000.0

