# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_milligrams(value): 
	return value * 28349.5231
def to_grams(value): 
	return value * 28.3495231
def to_kilograms(value): 
	return value / 35.274
def to_tonnes(value): 
	return value * 0.0000283495231
def to_pounds(value): 
	return value * 0.0625
def to_stones(value): 
	return value / 224.0
def to_carats(value): 
	return value / 0.00705479

