# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_milligrams(value): 
	return value * 453592.37
def to_grams(value): 
	return value * 453.59237
def to_kilograms(value): 
	return value / 2.20462
def to_tonnes(value): 
	return value / 2204.62
def to_ounces(value): 
	return value * 16.0
def to_stones(value): 
	return value / 14.0
def to_carats(value): 
	return value / 0.000440925

