# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_milligrams(value): 
	return value * 6350293.18
def to_grams(value): 
	return value * 6350.29318
def to_kilograms(value): 
	return value * 6.35029
def to_tonnes(value): 
	return value / 157.473
def to_ounces(value): 
	return value * 224.0
def to_pounds(value): 
	return value * 14.0
def to_carats(value): 
	return value / 3.1495e-5

