# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_bits(value): 
	return value * 1e+9
def to_kilobits(value): 
	return value * 1e+6
def to_megabits(value): 
	return value * 1000.0
def to_terabits(value): 
	return value / 1000.0
def to_kilobytes(value): 
	return value * 125000.0
def to_megabytes(value): 
	return value * 125.0
def to_gigabytes(value): 
	return value / 8.0
def to_terabytes(value): 
	return value / 8000.0
def to_kibibits(value): 
	return value * 976562.5
def to_mebibits(value): 
	return value * 953.67431640625

