# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_bits(value): 
	return value * 1024.0
def to_kilobits(value): 
	return value * 1.024
def to_megabits(value): 
	return value / 976.563
def to_gigabits(value): 
	return value / 976562.5
def to_terabits(value): 
	return value / 976562500.0
def to_kilobytes(value): 
	return value / 7.812
def to_megabytes(value): 
	return value / 7812.5
def to_gigabytes(value): 
	return value / 7812500.0
def to_terabytes(value): 
	return value / 7812500000.0
def to_mebibits(value): 
	return value / 1024.0

