# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_bits(value): 
	return value * 1048576.0
def to_kilobits(value): 
	return value * 1048.58
def to_megabits(value): 
	return value * 1.04858
def to_gigabits(value): 
	return value / 954.0
def to_terabits(value): 
	return value / 953674.0
def to_kilobytes(value): 
	return value / 0.00762939
def to_megabytes(value): 
	return value / 7.62939
def to_gigabytes(value): 
	return value / 7629.39
def to_terabytes(value): 
	return value * 0.000000131072
def to_kibibits(value): 
	return value * 1024.0

