# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

from math import pi

def to_degrees(value): 
	return value * 180.0/200.0
def to_radians(value): 
	return value * pi/200.0
def to_milliradians(value): 
	return value * (1000.0*pi)/200.0
def to_minute_of_arc(value): 
	return value * 54.0
def to_seconds_of_arc(value): 
	return value * 3240.0

