# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

from math import pi

def to_degrees(value): 
	return value / 60.0
def to_radians(value): 
	return value * pi/(60.0 * 180.0)
def to_gradians(value): 
	return value / 54.0
def to_milliradians(value): 
	return value * (1000.0 * pi) / (60.0 * 180.0)
def to_seconds_of_arc(value): 
	return value * 60.0

