# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_u_s_miles_per_gallon(value): 
	return value * 2.35215
def to_miles_per_gallon(value): 
	return value * 2.82481
def to_litres_per100_kilometres(value): 
	return 100.0 / value

