# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_kilometre_per_litre(value): 
	return 100.0 / value
def to_miles_per_gallon(value): 
	return 282.481 / value
def to_u_s_miles_per_gallon(value): 
	return 235.215 / value

