# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_kilometre_per_litre(value): 
	return value / 2.35215
def to_miles_per_gallon(value): 
	return value * 1.20095
