# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_kilo_bits_per_second(value): 
	return value / 1000.0
def to_mega_bits_per_second(value): 
	return value / 1e+6
def to_giga_bits_per_second(value): 
	return value / 1e+9
def to_tera_bits_per_second(value): 
	return value / 1e+12
def to_kilo_bytes_per_second(value): 
	return value / 8000.0
def to_mega_bytes_per_second(value): 
	return value / 8e+6
def to_giga_bytes_per_second(value): 
	return value / 8e+9
def to_tera_bytes_per_second(value): 
	return value / 8e+12
def to_kibibits_per_second(value): 
	return value / 1024.0
def to_mebibits_per_second(value): 
	return value / 1048576.0

