# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_bits_per_second(value): 
	return value * 1024.0
def to_kilo_bits_per_second(value): 
	return value * 1.024
def to_mega_bits_per_second(value): 
	return value / 976.563
def to_giga_bits_per_second(value): 
	return value / 976562.5
def to_tera_bits_per_second(value): 
	return value / 976562500.0
def to_kilo_bytes_per_second(value): 
	return value / 7.812
def to_mega_bytes_per_second(value): 
	return value / 7812.5
def to_giga_bytes_per_second(value): 
	return value / 7812500.0
def to_tera_bytes_per_second(value): 
	return value / 7812500000.0
def to_mebibits_per_second(value): 
	return value / 1024.0

