# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_bits_per_second(value): 
	return value * 1048576.0
def to_kilo_bits_per_second(value): 
	return value * 1048.58
def to_mega_bits_per_second(value): 
	return value * 1.04858
def to_giga_bits_per_second(value): 
	return value / 954.0
def to_tera_bits_per_second(value): 
	return value / 953674.0
def to_kilo_bytes_per_second(value): 
	return value / 0.00762939
def to_mega_bytes_per_second(value): 
	return value / 7.62939
def to_giga_bytes_per_second(value): 
	return value / 7629.39
def to_tera_bytes_per_second(value): 
	return value * 0.000000131072
def to_kibibits_per_second(value): 
	return value * 1024.0

