# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_kilojoules(value): 
	return value * 1.0550559
def to_kilocalories(value): 
	return value / 3.9673727240424
def to_joules(value): 
	return value * 1055.06
def to_calories(value): 
	return value * 252.164
def to_u_s_therms(value): 
	return value / 99976.12448781215
def to_watt_hours(value): 
	return value * 0.293071
def to_kilowatt_hours(value): 
	return value / 3412.14
def to_foot_pounds(value): 
	return value * 778.169

