# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_kilojoules(value): 
	return value / 239.0057
def to_kilocalories(value): 
	return value / 1000.0
def to_joules(value): 
	return value * 4.184
def to_btu(value): 
	return value / 252.1644007218
def to_u_s_therms(value): 
	return value / 25210420.0
def to_watt_hours(value): 
	return value * 0.00116222
def to_kilowatt_hours(value): 
	return value / 860421.0
def to_foot_pounds(value): 
	return value * 3.08596
def to_electronvolts(value): 
	return value * 2.6131936951817e+19

