# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_kilojoules(value): 
	return value / 737.562
def to_kilocalories(value): 
	return value / 3085.96
def to_joules(value): 
	return value * 1.35582
def to_btu(value): 
	return value / 778.169
def to_calories(value): 
	return value / 3.08596
def to_u_s_therms(value): 
	return value / 77816937.099186
def to_watt_hours(value): 
	return value / 2655.22
def to_kilowatt_hours(value): 
	return value * 0.00000037662

