# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_kilojoules(value): 
	return value / 1000.0
def to_kilocalories(value): 
	return value / 4184.0
def to_btu(value): 
	return value / 1055.06
def to_calories(value): 
	return value / 4.184
def to_u_s_therms(value): 
	return value / 105480400.0
def to_watt_hours(value): 
	return value / 3600.0
def to_kilowatt_hours(value): 
	return value / 3.6e+6
def to_foot_pounds(value): 
	return value / 1.35582

