# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_kilojoules(value): 
	return value * 3600.0
def to_kilocalories(value): 
	return value * 860.421
def to_joules(value): 
	return value * 3.6e+6
def to_btu(value): 
	return value * 3412.14
def to_calories(value): 
	return value * 860421.0
def to_u_s_therms(value): 
	return value / 29.3
def to_watt_hours(value): 
	return value * 1000.0
def to_foot_pounds(value): 
	return value / 0.00000037662

