# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_kilojoules(value): 
	return value * 105480.04
def to_kilocalories(value): 
	return value * 25210.44007218
def to_joules(value): 
	return value * 105480400.0
def to_btu(value): 
	return value * 99976.12448781215
def to_calories(value): 
	return value * 25210420.0
def to_watt_hours(value): 
	return value * 29300.1
def to_kilowatt_hours(value): 
	return value * 29.3001
def to_foot_pounds(value): 
	return value * 77816937.099186
def to_electronvolts(value): 
	return value * 6.5835660010911e+26

