# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_kilojoules(value): 
	return value * 3.6
def to_kilocalories(value): 
	return value / 1.16222
def to_joules(value): 
	return value * 3600.0
def to_btu(value): 
	return value / 0.293071
def to_calories(value): 
	return value / 0.00116222
def to_u_s_therms(value): 
	return value / 29300.1
def to_kilowatt_hours(value): 
	return value / 1000.0
def to_foot_pounds(value): 
	return value * 2655.22
def to_electronvolts(value): 
	return value * 2.2469422907138e+22
