# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_millimetres(value): 
	return value * 10.0
def to_metres(value): 
	return value / 100.0
def to_kilometres(value): 
	return value / 100000.0
def to_inches(value): 
	return value / 2.54
def to_feet(value): 
	return value / 30.48
def to_yards(value): 
	return value / 91.44
def to_miles(value): 
	return value / 160934.4
def to_nautical_miles(value): 
	return value / 185200.0

