# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_millimetres(value): 
	return value * 304.8
def to_centimetres(value): 
	return value * 30.48
def to_metres(value): 
	return value * 0.3048
def to_kilometres(value): 
	return value * 0.0003048
def to_inches(value): 
	return value * 12.0
def to_yards(value): 
	return value / 3.0
def to_miles(value): 
	return value / 5280.0
def to_nautical_miles(value): 
	return value / 6076.12

