# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_millimetres(value): 
	return value * 25.4
def to_centimetres(value): 
	return value * 2.54
def to_metres(value): 
	return value / 39.3701
def to_kilometres(value): 
	return value / 39370.07874
def to_feet(value): 
	return value / 12.0
def to_yards(value): 
	return value / 36.0
def to_miles(value): 
	return value / 63360.0
def to_nautical_miles(value): 
	return value / 72913.4

