# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_millimetres(value): 
	return value * 1000.0
def to_centimetres(value): 
	return value * 100.0
def to_kilometres(value): 
	return value / 1000.0
def to_inches(value): 
	return value / 0.0254
def to_feet(value): 
	return value / 0.3048
def to_yards(value): 
	return value / 0.9144
def to_miles(value): 
	return value / 1609.344
def to_nautical_miles(value): 
	return value / 1852.0

