# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_millimetres(value): 
	return value * 1609344.0
def to_centimetres(value): 
	return value * 160934.4
def to_metres(value): 
	return value * 1609.344
def to_kilometres(value): 
	return value * 1.609344
def to_inches(value): 
	return value * 63360.0
def to_feet(value): 
	return value * 5280.0
def to_yards(value): 
	return value * 1760.0
def to_nautical_miles(value): 
	return value / 1.15078

