# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_millimetres(value): 
	return value * 1852000.0
def to_centimetres(value): 
	return value * 185200.0
def to_metres(value): 
	return value * 1852.0
def to_kilometres(value): 
	return value * 1.85200
def to_inches(value): 
	return value * 72913.4
def to_feet(value): 
	return value * 6076.12
def to_yards(value): 
	return value * 2025.37
def to_miles(value): 
	return value * 1.15078

