# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_millimetres(value): 
	return value * 914.4
def to_centimetres(value): 
	return value * 91.44
def to_metres(value): 
	return value * 0.9144
def to_kilometres(value): 
	return value * 0.0009144
def to_inches(value): 
	return value * 36.0
def to_feet(value): 
	return value * 3.0
def to_miles(value): 
	return value / 1760.0
def to_nautical_miles(value): 
	return value / 2025.37
