# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_square_kilometres(value): 
	return value / 247.105
def to_square_metres(value): 
	return value * 4046.86
def to_square_miles(value): 
	return value / 640.0
def to_square_yards(value): 
	return value * 4840.0
def to_square_feet(value): 
	return value * 43560.0
def to_square_inches(value): 
	return value * 6272640.0
def to_hectares(value): 
	return value / 2.471

