# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_square_kilometres(value): 
	return value / 100.0
def to_square_metres(value): 
	return value * 10000.0
def to_square_miles(value): 
	return value / 259.0
def to_square_yards(value): 
	return value * 11959.900463011
def to_square_feet(value): 
	return value * 107639.0
def to_square_inches(value): 
	return value * 15500031.0
def to_acres(value): 
	return value * 2.471

