# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_square_kilometres(value): 
	return value / 10763910.41671
def to_square_metres(value): 
	return value / 10.76391042
def to_square_miles(value): 
	return value / 27878400.0
def to_square_yards(value): 
	return value / 9.0
def to_square_inches(value): 
	return value * 144.0
def to_hectares(value): 
	return value / 107639.0
def to_acres(value): 
	return value / 43560.0

