# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_square_kilometres(value): 
	return value / 1550003100.00
def to_square_metres(value): 
	return value / 1550.0
def to_square_miles(value): 
	return value / 4014489600.0
def to_square_yards(value): 
	return value / 1296.0
def to_square_feet(value): 
	return value / 144.0
def to_hectares(value): 
	return value / 15500031.0
def to_acres(value): 
	return value / 6272640.0

