# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_square_metres(value): 
	return value * 1e+6
def to_square_miles(value): 
	return value / 2.58999
def to_square_yards(value): 
	return value * 1195990.05
def to_square_feet(value): 
	return value * 10763910.41671
def to_square_inches(value): 
	return value * 1550003100.00
def to_hectares(value): 
	return value * 100.0
def to_acres(value): 
	return value * 247.105

