# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_square_kilometres(value): 
	return value / 1e+6
def to_square_miles(value): 
	return value / 2589988.10
def to_square_yards(value): 
	return value * 1.196
def to_square_feet(value): 
	return value * 10.764
def to_square_inches(value): 
	return value * 1550.0
def to_hectares(value): 
	return value / 10000.0
def to_acres(value): 
	return value / 4046.86

