# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_square_kilometres(value): 
	return value * 2.58999
def to_square_metres(value): 
	return value * 2589988.10
def to_square_yards(value): 
	return value * 3097600.0
def to_square_feet(value): 
	return value * 27878400.0
def to_square_inches(value): 
	return value * 4014489600.0
def to_hectares(value): 
	return value * 259.0
def to_acres(value): 
	return value * 640.0

