# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_square_kilometres(value): 
	return value / 1195990.05
def to_square_metres(value): 
	return value / 1.1959900463
def to_square_miles(value): 
	return value / 3097600.0
def to_square_feet(value): 
	return value * 9.0
def to_square_inches(value): 
	return value * 1296.0
def to_hectares(value): 
	return value / 11959.900463011
def to_acres(value): 
	return value / 4840.0
