# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_nanoseconds(value): 
	return value * 8.64e+13
def to_microseconds(value): 
	return value * 8.64e+10
def to_milliseconds(value): 
	return value * 8.64e+7
def to_seconds(value): 
	return value * 86400.0
def to_minutes(value): 
	return value * 1440.0
def to_hours(value): 
	return value * 24.0
def to_weeks(value): 
	return value / 7.0
def to_months(value): 
	return value / 30.4167
def to_years(value): 
	return value / 365.0
def to_decades(value): 
	return value / 3650.0
def to_centuries(value): 
	return value / 36500.0

