# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_seconds(value): 
	return value * 3.154e+8
def to_minutes(value): 
	return value * 5.256e+6
def to_hours(value): 
	return value * 87600.0
def to_days(value): 
	return value * 3650.0
def to_weeks(value): 
	return value * 521.0
def to_months(value): 
	return value * 120.0
def to_years(value): 
	return value * 10.0
def to_centuries(value): 
	return value / 10.0

