# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_seconds(value): 
	return value * 3600.0
def to_minutes(value): 
	return value * 60.0
def to_days(value): 
	return value / 24.0
def to_weeks(value): 
	return value / 168.0
def to_months(value): 
	return value / 730.0
def to_years(value): 
	return value / 8760.0
def to_decades(value): 
	return value / 87600.0
def to_centuries(value): 
	return value / 876000.0

