# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_seconds(value): 
	return value * 60.0
def to_hours(value): 
	return value / 60.0
def to_days(value): 
	return value / 1440.0
def to_weeks(value): 
	return value / 10080.0
def to_months(value): 
	return value / 43800.0
def to_years(value): 
	return value / 525600.0
def to_decades(value): 
	return value / 5.256e+6
def to_centuries(value): 
	return value / 5.256e+7

