# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_minutes(value): 
	return value / 60.0
def to_hours(value): 
	return value / 3600.0
def to_days(value): 
	return value / 86400.0
def to_weeks(value): 
	return value / 604800.0
def to_months(value): 
	return value / 2.628e+6
def to_years(value): 
	return value / 3.1536e+7
def to_decades(value): 
	return value / 3.154e+8
def to_centuries(value): 
	return value / 3.154e+9

