# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_seconds(value): 
	return value * 604800.0
def to_minutes(value): 
	return value * 10080.0
def to_hours(value): 
	return value * 168.0
def to_days(value): 
	return value * 7.0
def to_months(value): 
	return value / 4.34524
def to_years(value): 
	return value / 52.143
def to_decades(value): 
	return value / 521.429
def to_centuries(value): 
	return value / 5214.29

