# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

def to_seconds(value): 
	return value * 3.1536e+7
def to_minutes(value): 
	return value * 525600.0
def to_hours(value): 
	return value * 8760.0
def to_days(value): 
	return value * 365.0
def to_weeks(value): 
	return value * 52.143
def to_months(value): 
	return value * 12.0
def to_decades(value): 
	return value / 10.0
def to_centuries(value): 
	return value / 100.0
